Lib various changes

diff --git a/zsh_libs/zsh_aliases b/zsh_libs/zsh_aliases
--- a/zsh_libs/zsh_aliases
+++ b/zsh_libs/zsh_aliases
@@ -5,7 +5,7 @@ alias op="xdg-open"
 alias open="xdg-open"
 alias vmake="make SHELL='$$SHELL -x'"
 alias web="cd gp3320/app/bcm-webconf ; . venv/bin/activate ; ./webconf.py &"
-alias sv="sudo vim"
+alias sv="v -s"
 alias pytags="ctags -R --python-kinds=-i ."
 alias cfg="cd $CFG"
 alias s="sudo"
@@ -159,7 +159,7 @@ function mkscript()
 	fi
 
 	echo ${data}$'\n' >> $file
-	$isLib && source $file && { type $func ; which $func }
+	$isLib && source $file && { type $func ; which $func; }
 
 	# setup file
 	[[ -x "$file" || $isLib ]] || chmod +x $file
@@ -217,8 +217,8 @@ function edfunc()
 {
 	local arg
 	arg=($(type $1))
-	[[ $? -ne 0 ]] && { echo $arg; return 1 }
-	[[ "${arg[5]}" != "function" ]] && { echo "$1 is not a function:\n\t$arg"; return 2 }
+	[[ $? -ne 0 ]] && { echo $arg; return 1; }
+	[[ "${arg[5]}" != "function" ]] && { echo "$1 is not a function:\n\t$arg"; return 2; }
 	edalias "function $1\(\)" 2 ${arg[-1]}
 }
 comp+=("vw=exec")
@@ -229,7 +229,7 @@ function vw()
 	ret=`which $fpath`
 	if [ -f "$ret" ]; then
 		mime=$(getmime $fpath)
-		[[ "$mime" == "application/x-sharedlib" ]] && { echo "$fpath is binary executable" ; return 1 }
+		[[ "$mime" == "application/x-sharedlib" ]] && { echo "$fpath is binary executable" ; return 1; }
 		gvim $ret
 	else
 		ret=`which -w $@`
@@ -293,7 +293,7 @@ function forvim()
 }
 function f()
 {
-	local d i s p g
+	local d i s p g dir
 	zparseopts -D - d:=d i=i s=s p=p g:=g
 	#if [ "${1:0:2}" = "-d" ]; then
 	#	d=${1:2}
@@ -301,13 +301,20 @@ function f()
 	[[ -n $s ]] && s="sudo"
 	[[ -n $d ]] && d[1]='-maxdepth'
 	[[ -n $i ]] && name="-iname" || name="-name"
+	dir=()
+	while [[ -d $1 ]]; do
+		dir+=($1)
+		shift
+	done
+	if [[ -z $dir ]]; then
+		dir+=(.)
+	fi
 	#[[ $1 = - ]] && shift
 	#$s find ${=d} \( -path ./bckup_extensions -or -path ./extensions \) -prune -or $name $@ -print
 	
 	[[ -n $g ]] && {
-		$s find ${=d} $name $@ $p | group $g
-
-	} || $s find ${=d} $name $@ $p
+		$s find $dir ${=d} $name $@ $p | group $g
+	} || $s find $dir ${=d} $name $@ $p
 }
 function aldd() {
 	local R=$USER_HOME/clp
@@ -356,25 +363,30 @@ function ge()
 function duh()
 {
 	local sudo
-	[[ "$1" == '-s' ]] && { shift; sudo='sudo' }
+	[[ "$1" == '-s' ]] && { shift; sudo='sudo'; }
 	$sudo du -csh "$@" | sort -h
 }
+
+# call vim to each file:line argument
+# file1:l4 file2:l66 
 function v()
 {
-	local opt
+	local opt sudo
 	if [ "${1:0:1}" = "-" ]; then
-		opt=$1
+		if [[ $1 = -s ]]; then
+			sudo='sudo'
+		else
+			opt=$1
+		fi
 		shift
 	fi
-	# convert "filename:linenum" to "filename" "+linenum"
-	# file1:l4 file2:l66 
 	for arg; do
 		if [[ "$arg" =~ ":" ]]; then
 			line=+$(echo $arg | cut -d: -f2)
 			file=$(echo $arg | cut -d: -f1)
-			gvim $opt $line $file
+			$sudo gvim $opt $line $file
 		else
-			gvim $opt $arg
+			$sudo gvim $opt $arg
 		fi
 	done
 }
@@ -384,9 +396,9 @@ function extract_cpio_image()
 {
     local ret name mime sourceDir imgfile=$(getfullpath "$1") targetroot targetDir uncompressed tmp
 	[[ -n $imgfile ]] || abort 1 "No image given"
-	[[ -s $imgfile ]] || { abort 127 "$imgfile: not found" ; return }
+	[[ -s $imgfile ]] || { abort 127 "$imgfile: not found" ; return; }
 	sourceDir=$(getpath "$imgfile")
-	name=${$(getfilename "${(L)imgfile}")#u}
+	name=${$(getfilename "${(L)imgfile%.img}")#u}
     targetDir=${2:-$PWD/$name}
     (
 		if [[ -f "$targetDir" ]]; then
@@ -399,18 +411,18 @@ function extract_cpio_image()
 		if [[ -d "$targetDir" ]]; then
 			isEmptyDir "$targetDir" || {
 				confirm "Dir $targetDir not empty. $C[lred]Remove files and continue" \
-					|| { cancel ; return }
-				run -s rm -rf "$targetDir"/* || { abort $? ; return }
+					|| { cancel ; return; }
+				run -s rm -rf "$targetDir"/* || { abort $? ; return; }
 			}
 		else
 			confirm Create dir '"$targetDir"' && \
-				run -s mkdir -p "$targetDir" || { abort $? ; return }
+				run -s mkdir -p "$targetDir" || { abort $? ; return; }
 		fi
 		#uncompressed="$imgfile.cpio"
 		#if [[ "$imgfile" -ot "$uncompressed" ]] && [[ -s "$uncompressed" ]] && \
 		#	! confirm -c warn "$uncompressed is newer than $imgfile\nOverwrite it"
 		#then
-		#	{ cancel ; return }
+		#	{ cancel ; return; }
 		#fi
 		mime=$(getmime "$imgfile")
 		tmp="$imgfile"
@@ -447,7 +459,7 @@ function extract_cpio_image()
 function compress()
 {
     local alg sudo
-	[[ $1 == -s ]] && { sudo=sudo ; shift }
+	[[ $1 == -s ]] && { sudo=sudo ; shift; }
 	alg=$1 ; shift
     case "$alg" in
         "gzip")
@@ -515,66 +527,6 @@ function pbar()
 	else
 		return 1
 	fi
-}
-
-function tobin
-{
-    #@TODO pad to 8-multiple, sep 8-bit groups by space
-    printf "%08d" $(([##2]$1))
-}
-function tooct
-{
-    echo -n $(([##8]$1))
-}
-function tohex
-{
-    echo -n $(([##16]$1))
-}
-function chartoint()
-{
-    local i=`printf %3d \'"$1"`
-    #printf %d \'"$1""\n"
-    printf "$i 0x%2x %s\n" $i $(tobin $i)
-
-    # Bizarre:
-    # function chartoint()
-    # {
-    #     printf %d \'$1\n
-    # }
-    # Does not work for T: 
-    #   chartoint T
-    #   0
-
-    # Quoting the argument solves the problem:
-    #   printf %d \'"$1"\n
-    # function chartoint()
-    # {
-    #     printf %d \'$1\n
-    # }
-    # But directly on prompt without the function:
-    #   printf %d \'T
-    #   84
-    # Any other char works:
-    #   chartoint U
-    #   85
-    # Quoted works
-    #   chartoint 'T'
-    #   84
-    # works: for l in {A..Z}; do [[ "$l" == "T" ]] && e "Attention:"; echo -n "$l="; chartoint $l; echo ; done
-    #   
-    # What is this sorcery?
-}
-function hextochar()
-{
-    local i str
-	for ((i=0; i<$#1 ; i+=2)); do 
-		str+="\x${1:$i:2}"
-	done
-    printf "$str"
-}
-function inttochar()
-{
-    [[ $(ishex $1) ]] && hextochar $1 || printf "\\$(printf %o $1)"
 }
 
 # Added 2019-02-20 09:23:39 @TODO
@@ -653,18 +605,13 @@ function procmon()
 # Added 2019-04-11 01:43
 function logs()
 {
-	tail logs/{api,debug}.txt -f &
-}
-
-# Added 2019-06-06 15:21
-function todo()
-{
-	# message syncDirs warn empty dirs
+	tail {.,$(git root)}/logs/{api,debug}.txt -f &
 }
 
 # Added 2019-06-07 17:27
 function fordo()
 {
+	e FIXME
 	local v
 	cmd=$1 ; shift
 	for v; do
diff --git a/zsh_libs/zsh_functions b/zsh_libs/zsh_functions
--- a/zsh_libs/zsh_functions
+++ b/zsh_libs/zsh_functions
@@ -40,14 +40,28 @@ OK=" [${C[ok]}OK$C_]"
 
 function input()
 {
-	local var ret p
-	zparseopts -M -D - p:=p
-	[[ -n $p ]] && p[2]="${C[head]}${p[2]}:$C_ "
-	var="$@"
-	vared "$p[@]" var || return
-	ret=$?
-	echo $var
-	return $ret
+	local var ret p gui z colors args tit
+	zparseopts -M -D - p:=p s:=set g=gui z=z t:=tit
+	colors=(-fg $C[head] -bg black)
+	p=${p[2]:-Edit text}
+	tit=${tit[2]:-Edit text}
+	var=${(P)set[2]:-"$@"}
+	techo -c head $p
+	if [[ -n $z ]] && type zenity>/dev/null; then
+		var=$(zenity -title "$title" --entry --text="$p" --entry-text="$var") || return
+	elif type gxmessage >/dev/null; then
+		args=($colors -center -ontop -wrap -buttons Cancel:1,Ok:0)
+		var=$(gxmessage $args -title "$title" -entrytext "$var" "$p") || return
+	else
+		vared var || read -r var || return
+	fi
+
+	if [[ -n $set[2] ]]; then
+		${(P)set[2]::=$var}
+	else
+		echo $var
+	fi
+	return 0
 }
 
 function confirm()
@@ -56,14 +70,16 @@ function confirm()
 	if [[ "$1" != -c ]]; then
 		c=(-c lcyan)
 	fi
+	while read -t 0 -k -r a; do : ; done # clear buffer
+	[[ -n $a ]] && echo
 	techo -n $c "$@" "(y/N)? "
-	if [ -n "$BASH" ]; then
-		while [ "$a" != 'y' ] && [ "$a" != 'n' ]; do
+	if [[ -n "$BASH" ]]; then
+		while [[ "$a" != 'y' ]] && [[ "$a" != 'n' ]]; do
 			read -n 1 -r a
 		done
 		return $ret
 	fi
-	read -q -r "a?$str"
+	read -q -r "a"
 	ret=$?
 	echo
 	return $ret
@@ -84,22 +100,15 @@ function chooser()
 		chosen="$1"
 	fi
 	ret=$?
-	if [ -z "$regex" ]; then
+	if [[ -z $regex ]]; then
 		[ -z "$chosen" ] && return 1
 		echo "$chosen"
 		return 0
-	elif [ "$chosen" =~ "$regex[2]" ]; then
+	elif [[ $chosen =~ $regex[2] ]]; then
 		echo "$match[@]"
 		return 0
 	fi
 	return 1
-}
-
-function lnecho()
-{
-	for i; do
-		echo $i
-	done
 }
 
 function chkCmdInstall()
@@ -147,7 +156,8 @@ function sndplay()
 # Say the file, line number and optional message for debugging
 # Inspired by bash's `caller` builtin
 # Thanks to https://unix.stackexchange.com/a/453153/143394
-function yelp() {
+function yelp()
+{
 	# shellcheck disable=SC2154  # undeclared zsh variables in bash
 	if [ -n "$BASH_VERSION" ]; then
 		local file=${BASH_SOURCE[1]} func=${FUNCNAME[1]} line=${BASH_LINENO[0]}
@@ -156,7 +166,7 @@ function yelp() {
 		# $funcfiletrace has format:  file:line
 		local file=${funcfiletrace[1]%:*} line=${funcfiletrace[1]##*:}
 		local func=${funcstack[2]}
-		[ "$func" =~ '/' ] && func=source  # $func may be filename. Use bash behaviour
+		[[ "$func" =~ '/' ]] && func=source  # $func may be filename. Use bash behaviour
 	fi
 	techo "${file##*/}:$func:$line $*"
 }
@@ -211,91 +221,129 @@ function run_end()
 	fi
 }
 
+# Verbose levels
+# 0: Quiet
+# 1: Only errors
+# 2: Show errors. Show header if given a string (-p something)
+# 3: Errors and header
+# 4: Above, plus finishing message
+# 5: Above, plus associated command
+# 6: Above, plus full command with arguments
 function run()
 {
-	local ret cmd fullcmd sudo dryrun quiet color alert print cmdinst
+	local ret cmd fullcmd logfile watch
+	local sudo trysudo dryrun verbose color alert print
+	local cmdinst workdir skipErrors
 
-	if [ "${1:0:1}" = '-' ]; then
-	zparseopts -M -D - s=sudo S=trysudo n=dryrun q=quiet c:=color a=alert p:=print I:=cmdinst
-	[ "$1" = '-' ] && shift
+	if [[ "${1:0:1}" == - ]]; then
+		zparseopts -M -D - v:=verbose c:=color a=alert p:=print \
+			s=sudo S=trysudo n=dryrun I:=cmdinst -cd:=workdir E=skipErrors \
+			l:=logfile w:=watch
+
+		[[ "$1" == - ]] && shift
+		[[ ${1:0:1} == - ]] && { abort 1 "Invalid command: $1"; return }
 	fi
+	verbose=${verbose[2]:-6}
 
 	cmd=$1
-	if [ -n "$sudo" ]; then
-		fullcmd="sudo $@"
+	if [[ -n "$sudo" ]]; then
+		fullcmd=(sudo "$@")
 		trysudo=
 	else
-		fullcmd="$@"
+		fullcmd=("$@")
 	fi
 
-	if [ -z "$color" ]; then
+	if [[ -z "$color" ]]; then
 		color=(-c head)
-	elif [ "$color" = 'none' ]; then
+	elif [[ "$color" = 'none' ]]; then
 		color=''
 	fi
-	if [ -z "$quiet" ]; then
-		[ -n "$print" ] && techo $=color $print[2] || techo $=color $fullcmd
+	[[ -n $print ]] && print=$print[2]
+	if [[ $verbose -ge 3 ]] || [[ $verbose -ge 2 && -n $print ]] ; then
+		if [[ $verbose -ge 6 ]]; then
+			[[ -n $print ]] && techo $color $print
+			techo $color $fullcmd
+		elif [[ -n $print ]]; then
+			[[ $verbose -ge 5 ]] && techo $color "$print ($cmd)" || techo $color $print
+		else
+			techo $color $cmd
+		fi
 	fi
-	[ -n "$print" ] && print="$print[2] : $cmd" || print=$cmd
-
+	[[ -n "$print" ]] && print="$print : $cmd" || print=$cmd
 	{
 		[[ -n $dryrun ]] && return 0
 
-		if [ -n "$color" ]; then
-			color ${=fullcmd} # | colorify
+		if [[ -n $workdir ]]; then
+			workdir=$workdir[2]
+			if [[ ! -d $workdir ]]; then
+				confirm "$workdir does not exist. Create" && mkdir "$workdir" || throw $?
+			fi
+			cd "$workdir" || throw $?
+		fi
+
+		# # # # # # # # # #
+		# Execute command #
+		# # # # # # # # # #
+		if [[ -n "$color" ]]; then
+			if [[ -n $watch ]]; then
+				#waitPid -c "dirtyMem -P" color $fullcmd
+				color $fullcmd
+			else
+				color $fullcmd
+			fi
 		else
-			${=fullcmd}
+			$fullcmd
 		fi
 		ret=$?
 
-		[ $ret -eq 130 ] && throw $ret
-		if [ $ret -eq 127 ]; then
+		[[ -n $DEBUG ]] && set -x
+		[[ $ret -eq 130 ]] && throw $ret
+		if [[ $ret -eq 127 ]]; then
 			chkCmdInstall $cmd $cmdinst[2]
 			ret=$?
-			if [ $ret -eq 0 ]; then
-				if [ -n "$color" ]; then
-					color ${=fullcmd}
+			if [[ $ret -eq 0 ]]; then
+				if [[ -n "$color" ]]; then
+					color $fullcmd
 				else
-					${=fullcmd}
+					$fullcmd
 				fi
 				ret=$?
 			fi
 		fi
+		[[ -n $DEBUG ]] && { set +x ; return $ret }
 
-		if [ $ret -ne 0 ]; then
-			if [ -n "$trysudo" ]; then
+		if [[ $ret -ne 0 ]]; then
+			if [[ -n "$trysudo" ]]; then
 				techo "Trying with sudo"
-				color sudo ${=fullcmd}
+				color sudo $fullcmd
 				ret=$?
-				[ $ret -ne 0 ] && throw $ret
-			else
-				throw $ret
 			fi
+			[[ $ret -ne 0 ]] && throw $ret
 		fi
 	} always {
 		if catch '*'; then
-			CAUGHT=(${=CAUGHT})
-			ret=$CAUGHT[1]
-			if [ $ret -eq 130 ]; then
-				cancel $quiet "$print $CANCEL"
-				return $ret
+			local data=(${=CAUGHT})
+			ret=$data[1]
+			if [[ $ret -eq 130 ]]; then
+				cancel $verbose "$print $CANCEL"
+				return
 			fi
-			[ -z "$quiet" ] && techo "$print $FAIL ($CAUGHT)"
-			[ -n "$alert" ] && error "$print error: $CAUGHT"
-			abort $ret
-			return $ret
+			[[ $verbose -ge 1 ]] && techo "$print $FAIL ($data)"
+			[[ -n "$alert" ]] && error "$print error: $data"
+			abort $skipErrors $ret
+			return
 		fi
 	}
 
 	case $ret in
 	0)
-		[[ -z $quiet && -z $dryRun ]] && techo "$cmd $OK"
-		[ -n "$alert" ] && success "$cmd finished successfully."
+		[[ $verbose -ge 4 ]] && techo "$cmd $OK"
+		[[ -n "$alert" ]] && success "$cmd finished successfully."
 	;;
 	*)
-		[ -z "$quiet" ] && techo "$print $FAIL"
-		[ -n "$alert" ] && error "$print error: ret=$ret"
-		abort $ret
+		[[ $verbose -ge 1  ]] && techo "$print $FAIL"
+		[[ -n "$alert" ]] && error "$print error: ret=$ret"
+		abort $skipErrors $ret
 	;;
 	esac
 
@@ -341,7 +389,18 @@ function banner()
 		$cmd -f pagga "$@" >$TTY
 	fi
 }
+function group()
+{
+	local line opt
+	local integer i=0 num=${1:-1}
+	zparseopts -D -M - g:=opt
 
+	[[ -n $opt ]] && num=$opt[2]
+	while read -r line; do
+		echo $line
+		((++i % num == 0)) && echo ――――――――――――――――――――――――
+	done
+}
 function color()
 {
 	{ "$@" 2>&1 1>&3 | sed $'s,.*,\e[91m&\e[0m,' 1>&2 } 3>&1
diff --git a/zsh_libs/zsh_sql b/zsh_libs/zsh_sql
--- a/zsh_libs/zsh_sql
+++ b/zsh_libs/zsh_sql
@@ -1,4 +1,4 @@
-VERSION=1.0
+VERSION=1.0.3
 # databases data dir
 DB_DATA_DIR=/var/lib/mysql
 
@@ -21,42 +21,45 @@ function mklist()
 	first=$1
 	list=($1)
 	shift
-	for i; do
-		[[ "$i" != "$first" ]] && list+=($i)
-	done
-	echo ${list[@]}
+	for i; do [[ "$i" != "$first" ]] && list+=($i) ; done
+	echo "${list[@]}"
 }
-
+sqlPass='my7866'
 # execute mysql command
-# usage: sql [-d mydatabase] 'SELECT * FROM table1'
+# sql [-d dbname] [-f file.sql] SELECT ...
 function sql()
 {
-	if [[ "$1" == "-d" ]]; then
-		usedb $2
-        shift 2
-	elif [[ "$1" == "-n" ]]; then
-		shift
+	local file name sql nodb verbose pass silent
+	zparseopts -D - f:=file d:=name n=nodb v=verbose p:=pass s=silent
+	pass="${pass[2]:-$sqlPass}"
+	[[ -n $nodb ]] || usedb $name[2]
+	if [[ -n $file ]]; then
+		file=$file[2]
+		# [[ $file size greater than X lines ]] && 
+			#  run mysqlimport -u $user -p$pass ql $db
+			#  return
+		sql=$(<$file)
 	else
-        #dbname=${${dbname:-$(proj get dbname)}}
-		usedb
+		sql="$*"
 	fi
-	mysql -u root -pmy7866 -e "$*" $db
+
+	mysql $silent -u root -p$pass -e $sql $db
 }
+
 function isdb()
 {
 	[[ -n "$1" ]] && [[ -d "$DB_DATA_DIR/$1" ]]
 }
+
 function usedb()
 {
-	isdb $db && return
+	#${${dbname:-$(proj get dbname)}}
+	[[ $1 == '-s' ]] && { db= ; shift }
 	if [ $# -gt 0 ]; then
-		db=$1
-	else
-		[[ -n $DBNAME ]] && isdb $DBNAME && return
-		db=$dbname
+		isdb $1 && db=$1 || abort "$1: database not found"
+	elif [[ -z $db ]]; then
+		db=$(chooser $(mklist $DBNAME $(dblist)))
 	fi
-	db=$(zsh-select $(mklist $db $(dblist)))
-	dbname=$db
 }
 function dblist()
 {
@@ -70,9 +73,7 @@ function istable()
 }
 function tablelist()
 {
-	local args
-	[[ $1 == '-d' ]] && usedb $2 && shift 2
-	sql $args 'show tables' | tail -n +2
+	sql 'show tables' | tail -n +2
 }
 
 function gettable()
@@ -83,20 +84,19 @@ function gettable()
 
 function tableshow()
 {
-	local tblname args t
+	local tblname args t result
 	if [[ "$1" == "-d" ]]; then
-		usedb $2 || return
+		usedb $2
 		shift 2
 	else
-		usedb || return
+		usedb
 	fi
 	[[ "$1" == '-t' ]] && { shift; t=1 }
 	tblname=$(gettable $1)
 	if [[ -n "$t" ]]; then
 		sql "describe $tblname"
 	else
-		echo "CREATE TABLE $tblname ("
-		echo $(sql show create table "$tblname" | tail -n +2) | tail -n +2
+		echo $(tail -n +2 <(sql "show create table $tblname") | cut -f2-)
 	fi
 }
 
@@ -104,20 +104,20 @@ function tableshow()
 # usage: dbsize mydatabase
 function dbsize()
 {
-	sql 'SELECT table_name AS "Table Name", ROUND(((data_length + index_length) / 1024 / 1024), 2) AS "Size in (MB)" FROM information_schema.TABLES WHERE table_schema = "'$1'" ORDER BY (data_length + index_length)'
+	usedb "$@"
+	sql -n 'SELECT table_name AS "Table Name", ROUND(((data_length + index_length) / 1024 / 1024), 2) AS "Size in (MB)" FROM information_schema.TABLES WHERE table_schema = "'$db'" ORDER BY (data_length + index_length)'
 }
 
 # Added 2019-03-23 23:36
 function sqldbdump()
 {
-	[ $# -gt 1 ] && { echo "Usage: $0 database_name"; return }
-	dbname=${1:-${DBNAME:-$(usedb $dbname)}}
-	if [[ -f "$dbname.sql.bkup" ]]; then
-		techo -c warn "Saving backup $dbname.sql.bkup"
-		mv $dbname.sql $dbname.sql.bkup
+	usedb "$@"
+	if [[ -f "$db.sql.bkup" ]]; then
+		techo -c warn "Saving backup $db.sql.bkup"
+		mv $db.sql $db.sql.bkup
 	fi
-	mysqldump $dbname --no-data --single-transaction --skip-add-drop-table | \
+	mysqldump $db --no-data --single-transaction --skip-add-drop-table | \
 		sed -e 's/ AUTO_INCREMENT=[0-9]*\b//g' | \
-		grep -v '^\/\*![0-9]\{5\}.*character_set_client.*\/;$' > $dbname.sql
+		grep -v '^\/\*![0-9]\{5\}.*character_set_client.*\/;$' > $db.sql
 }
-
+DBNAME=idiomus
