Many bug fixes

diff --git a/zsh_libs/zsh_git b/zsh_libs/zsh_git
--- a/zsh_libs/zsh_git
+++ b/zsh_libs/zsh_git
@@ -1,5 +1,6 @@
 VERSION=1.0.2
-
+#lazyload=gclone,github,gh,gpush,pull,push
+[[ ! -v comp ]] && typeset -g -a comp
 export github_token='b2e74253b94398066f3938bb63120f51ca7745ee'
 
 alias pull="git pull"
@@ -7,9 +8,8 @@ alias push="gpush"
 alias gdiff="git diff --ignore-space-at-eol -b -w --ignore-blank-lines --minimal"
 alias gadd="git add"
 alias gadd-modified="git add \$(git diff --name-only --relative)"
-alias gshow="git show"
-alias gunstage="git reset HEAD --"
-alias unstage="git reset HEAD --"
+alias gshow="git show --color=always"
+alias unstage="gunstage"
 alias git_get_tag='git describe --tags $(git rev-list --tags --max-count=1)'
 alias gchk='git checkout'
 alias glog2='git log --date=iso -g'
@@ -17,6 +17,12 @@ alias glog2='git log --date=iso -g'
 alias maquina="cd ~/MaquinaDeConversao/www/api.maquinadeconversao.com.br"
 alias idiomus="cd ~/xdata/idiomusAPI"
 alias q48="cd ~/Q48API"
+
+comp+=('gunstage=git')
+function gunstage()
+{
+	git restore --staged "$@"
+}
 
 function gfollow()
 {
@@ -38,13 +44,13 @@ function gtag()
 	git tag -a $tag $hash
 }
 
-function gmerge()
+function gmerge() #@TODO
 {
 	local branch=${1:-$(chooser $(git branch))}
 	[[ -n $branch ]] && run git merge $branch --no-ff --no-commit
 }
 
-function ggrep()
+function ggrep() #@TODO
 {
 	local files pattern
 	pattern=$(echo "$@" | awk -F' - ' '// {print $1}')
@@ -60,7 +66,7 @@ function ggrep()
 	set +x
 }
 
-function commit()
+function commit() #@TODO
 {
 	local m args
 	zparseopts -D -M - m:=m
@@ -80,27 +86,27 @@ function croot()
 
 # Added 2019-01-25 11:17:01
 # https://github.com/search?q=
-alias gh='github'
-[[ ! -v comp ]] && typeset -g -a comp
 comp+=('github=cd' 'gh=cd')
 function github()
 {
 	local url repo search echo
 	zparseopts -D -M - r=repo s=search e=echo
 	if [[ $# -eq 0 ]]; then
-		open "https://github.com/"
+		url=$(gitgetrepo .) || url='https://github.com/'
+		open $url
 	elif [[ -n $search ]]; then
 		open "https://github.com/search?q=$(omz_urlencode $*)"
 	elif [[ -n $repo ]]; then
 		url="https://github.com/$*"
-		[[ -n $echo ]] && echo $url || open $url
+		[[ -n $echo || ! -t 1 ]] && echo $url || open $url
 	elif url=$(gitgetrepo "$*"); then
-		[[ -n $echo ]] && echo $url || open $url
+		[[ -n $echo || ! -t 1 ]] && echo $url || open $url
 	else
 		githubAPI $echo "$@"
 	fi
 }
-
+alias gh='github'
+typeset -Tf github
 #
 function githubAPI()
 {
@@ -127,11 +133,12 @@ function githubAPI()
 	request=${request//$'\n'/}
 	response=$(curl -sS -H "Authorization: bearer $GITHUB_API_TOKEN" -X POST -d $request $endpoint)
 	ret=$?
-	(( $#verbose )) && {
-		jq -r >$TTY <<<$request
-		jq -r >$TTY <<<$response
+	type jq >/dev/null || chkCmdInstall jq 
+	(($#verbose)) && {
+		jq -r <<<$request
+		jq -r <<<$response
 	}
-	if (( ret == 0 )); then
+	if ((ret == 0)); then
 		local field
 		typeset -a repos tmp
 		while read -r field; do
@@ -141,28 +148,43 @@ function githubAPI()
 				tmp=
 			fi
 		done < <(jq -cr "$fields" <<<$response)
-		
-		if [[ $#repos -eq 0 ]]; then
-			techo "No repositories found"
-		elif [[ $#repos -eq 1 ]]; then
+
+		if ((!$#repos)); then
+			abort 10 'No repositories found'
+		elif (($#repos == 1)); then
 			github -r $echo $(explode "$repos" ' ' 1)
 		else
 			name=$(chooser -s' ' -f1 $repos "Open this search in github") || cancel
-			[[ "$name" == 'Open' ]] && github -s "$*" || github -r $echo $name
+			if [[ $name == 'Open' ]]; then
+				github -s "$*"
+			else
+				github -r $echo $name
+			fi
 		fi
 	fi
 }
 
 function gitgetrepo()
 {
-	local repo d q
+	local repo d remote
 	zparseopts -D -M - d:=d
 	(
-	[[ -n "$d" ]] && d=$d[2] || d="$*"
-		[[ -d "$d" ]] && cd $1 || { techo -c err "Directory not found: $1"; return 1 }
-		repo=$(git remote show origin 2>/dev/null) || return 1
-		repo=$(echo $repo | awk '/Fetch URL/{print $3}')
-		[[ -n $repo ]] && echo "$repo"
+		d=${d[2]:-"$*"}
+		if [[ -n $d && -d $d ]]; then
+			cd $1 || {
+				[ -t 1 ] && techo -c err "Directory not found: $1"
+				return 1
+			}
+		fi
+		gremote || { techo -c warn 'No remotes'; return 10 }
+		repo=$(git remote get-url $remote[1] 2>/dev/null) || {
+			[ -t 1 ] && techo -c err 'Git repository not found'
+			return 1
+		}
+		[[ -n $repo ]] && echo $repo || {
+			[ -t 1 ] && techo -c err 'No remotes'
+			return 10
+		}
 	)
 }
 
@@ -210,24 +232,6 @@ function gremote()
 	#zparseopts c=current
 	
 	remote=($(git remote))
-}
-
-function url() {
-	local schemes=(ssh git http https ftp ftps)
-	local getscheme gethost getuser userhostpat='(([-[:alnum:]]+)@)?([-.[:alnum:]]+)'
-	zparseopts -D -M - -s=getscheme h=gethost u=getuser
-	if (( $#getscheme )); then
-		if [[ $2 =~ (${(j.|.)schemes})'://'$~userhostpat ]]; then
-			echo $match[1]
-			return
-		fi
-	fi
-
-	if [[ $2 =~ $~userhostpat ]]; then
-		(( $#getscheme )) && echo 'git'
-		(( $#getuser )) && echo $match[2]
-		(( $#gethost )) && echo $match[3]
-	fi
 }
 
 # Added 2019-09-03 19:04
diff --git a/zsh_libs/zsh_main b/zsh_libs/zsh_main
--- a/zsh_libs/zsh_main
+++ b/zsh_libs/zsh_main
@@ -120,15 +120,11 @@ function vartype() {
 # Set info for a lib
 function lib_set_info()
 {
-	local name info
-	integer ll=$6 err
-	if [[ $1 == '-E' ]]; then
-		err=1
-		shift
-	fi
-	name=${(U)1}
-	typeset -Ag ZSH_${name}_INFO
-	set -A ZSH_${name}_INFO ver $2 path "$3" required $4 mtime "$5" lazyload $ll err $err
+	local name info ll err
+	zparseopts -D - E=err l=ll
+	err=$#err; ll=$#ll; name=${(U)1}
+	typeset -Ag "ZSH_${name}_INFO"
+	set -A "ZSH_${name}_INFO" ver $2 path "$3" required $4 mtime "$5" lazyload $ll err $err
 }
 
 function getmime()
@@ -234,6 +230,7 @@ function parseErrors()
 	while read line; do
 		#echo line=${(q)line}
 		[[ $line == 'EOF' ]] && return
+		techo line=${(q)line}
 		if [[ $line =~ $'^(.+):([0-9]+): (parse error near) `(.*)\'' ]]; then
 		elif [[ $line =~ $'^(.+):([0-9]+): (condition expected): "(.*)"' ]]; then
 		elif [[ $line =~ $'^(.+):([0-9]+): (not an identifier):(.*)' ]]; then
@@ -273,9 +270,8 @@ function include()
 	required=$#required
 
 	if [[ ! -f $lpath ]]; then
-		techo -P "[%1K%F{15}FAIL%f%k] %F{11}$lpath %F{9}not found%f"
+		techo -P "[%K{1}%F{15}FAIL%f%k] ${${required:#0}:+%F\{9\}Required }%F{11}$lpath %F{9}not found%f"
 		if ((required)); then
-			techo -P "%F{9}Required %F{11}$name %F{9}not loaded%f"
 			[[ ! -o interactive ]] && abort 127
 		fi
 		return 127
@@ -287,7 +283,10 @@ function include()
 	if [[ -z ${(P)info} ||  # not loaded
 		-n $force ||  # force load 
 		${${(P)info}[mtime]} -lt $mtime ]] || # file was modified
-		((${${(P)info}[lazyload]} && ! $#lazyload)) # was lazy loaded 
+		((
+			${${(P)info}[err]} ||
+			( ${${(P)info}[lazyload]} && ! $#lazyload )
+		)) # has error or was lazy loaded 
 	then 
 		if ! zshLibReadHeader $lpath; then
 			techo -P "%F{11}$lpath %F{9}is not a zsh library%f"
@@ -300,45 +299,53 @@ function include()
 
 		if (($#lazyload)); then # @TODO
 			local llfuncs func
-			if [[ -n $HEADER[lazyload] ]]; then
+			if (($#HEADER[lazyload])); then
+				# register a autoload function for each lazy load function
 				explode -v llfuncs ${HEADER[lazyload]} ','
 				for func in $llfuncs; do
 					functions[$func]="include $name && $func \$@"
 				done
 			fi
-			lib_set_info $name $VERSION "$lpath" ${required:-0} "$mtime" 1
+			lib_set_info -l $name $VERSION "$lpath" $required "$mtime"
 			return 0
 		fi
 
 		#[[ -o interactive ]] && 
 		techo -P -r "Including %F{11}$name%f ("${lpath/$ZSH_LIBS/"\\$"ZSH_LIBS}") [%F{2}$VERSION%f]"
-		if source $lpath; then
-			lib_set_info $name $VERSION "$lpath" ${required:-0} "$mtime"
+		typeset -Tf parseErrors
+		coproc parseErrors
+		if source $lpath 2>&p; then
+			lib_set_info $name $VERSION "$lpath" $required "$mtime"
+			echo EOF >&p
 			#[[ -o interactive ]] &&
 		else
 			local error error2 file line tmp split
-			lib_set_info -E $name $VERSION "$lpath" ${required:-0} "$mtime"
-			techo -P "%F{11}$name%f [%K{1}%F{15}FAIL%f%k]"
+			lib_set_info -E $name $VERSION "$lpath" $required "$mtime"
+			echo EOF >&p
 			(
 				#@TODO sort errors by file before opening files
-				while read -pr tmp; do
-					split=(${(z)tmp})
+				set -x
+				while read -p tmp; do
+					split=(${(Q)${(z)tmp}})
 					file=$split[1]; line=$split[2]; error=$split[3]; error2=$split[4]
-					techo -Pr "%F{3}$file:$line %F{9}${error} %K{1}%F{15}${error2}%f%k"
-					if type v 2>&1 >/dev/null; then
-						v $file:$line &
-					else
-						${EDITOR:-vim} $file +$line &
-					fi
+					techo -Pr "%F{3}$file:$line %F{9}${error}%f${error2:+" %K{1}%F{15}${error2}%f%k"}"
+					#@TODO this is going to run once per terminal. Wanted: once total.
+					#@idea run this part only on current terminal, if there is one focused.
 				done
-				echo EOF >&p
+				if type v 2>&1 >/dev/null; then
+					#v $file:$line &
+				else
+					#${EDITOR:-vim} $file +$line &
+				fi
+				set +x
 			)
 
 			if ((required)); then
-				techo -P "\n%F{9}Required %F{11}\"zsh_$name\"%F{9} not loaded%f"
+				techo -P "[%K{1}%F{15}FAIL%f%k] %F{9}Required %F{11}zsh_$name%F{9} not loaded%f"
 				[[ -o interactive ]] || abort 2
 				return 2
 			fi
+			techo -P "[%K{1}%F{15}FAIL%f%k] %F{11}zsh_$name%F{9} not loaded%f"
 			return $ret
 		fi
 	fi
@@ -433,17 +440,18 @@ function aptinst()
 # Added 2019-09-03 19:29
 function libmonitor()
 {
-	# last   t       last+1.5   
-	# | DIFF | SLEEP |
-	local name evt pids
-	float t lastt=0 diff
-	while read -r evt name; do
+	local name lastname evt pids
+	float t lastt diff
+	integer ts=0 lastts=0
+	while read -r evt name ts; do
 		[[ $evt == 'exit' ]] && break
 		pids=($(pidof inotifywait 2>/dev/null))
 		if (($#pids > 1)); then
 			command kill ${pids:0:-1}
 		fi
-		techo -c warn "$evt $name $$"
+		((ts <= lastts)) && [[ $name == $lastname ]] && continue
+		techo -c warn "$evt $name $ts"
+		((lastts = ts))
 		t=$(date '+%s.%3N')
 		((diff = t - lastt))
 		if ((diff < 1.5)); then
@@ -453,7 +461,7 @@ function libmonitor()
 		fi
 		((lastt = t))
 		killall -HUP zsh
-	done < <(inotifywait -m -q -e modify -r --format '%e %f' $ZSH_LIBS || echo "exit $?")
+	done < <(inotifywait -m -q -e modify -r --format '%e %f %T' --timefmt '%s' $ZSH_LIBS || echo "exit $?")
 	return $name
 }
 
diff --git a/zsh_libs/zsh_sql b/zsh_libs/zsh_sql
--- a/zsh_libs/zsh_sql
+++ b/zsh_libs/zsh_sql
@@ -1,8 +1,16 @@
-VERSION=1.0.3
+VERSION=1.0.4
 # databases data dir
 DB_DATA_DIR=/var/lib/mysql
-DBNAME=idiomus
-sqlPass='my7866'
+DBNAME='idiomus'
+
+typeset -gA sqlPass=(
+	'sparc' 'my!7866'
+	'idiomus' '#58dhAms$3xx'
+)
+typeset -gA sqlUser=(
+	'root' 'sparc'
+	'idiomus' 'idiomus'
+)
 
 # get last modification time of dbname(s)
 # usage: dbtstamp dbname
@@ -19,8 +27,8 @@ alias sqlmaq="noglob sql --ssh maquina"
 # sql [-d dbname] [-f file.sql] SELECT ...
 function sql()
 {
-	local file name sql nodb verbose pass silent host
-	zparseopts -D - f:=file d:=name n=nodb v=verbose p:=pass s=silent -ssh:=host
+	local file name sql nodb verbose user pass silent host
+	zparseopts -D - f:=file d:=name n=nodb v=verbose u:=user p:=pass s=silent -ssh:=host
 	if [[ -n $file ]]; then
 		file=$file[2]
 		# [[ $file size greater than X lines ]] && 
@@ -32,11 +40,17 @@ function sql()
 	fi
 
 	if [[ -n $host ]]; then
-		ssh $host[2] "noglob sql $sql"
+		ssh $host[2] "noglob sql ${(qqq)sql}"
 	else
 		[[ -n $nodb ]] || usedb $name[2]
-		pass="${pass[2]:-$sqlPass}"
-		mysql $silent -u root -p$pass -e "$sql" $db
+		if [[ -n $db ]]; then
+			user=${user[2]:-${sqlUser[$db]:-root}}
+			pass=${pass[2]:-$sqlPass[$user]}
+		else
+			user=${user[2]:-$sqlUser[root]}
+			pass=${pass[2]:-$sqlPass[$user]}
+		fi
+		mysql $silent ${user:+-u$user} ${pass:+-p"$pass"} -e "$sql" $db
 	fi
 }
 
@@ -49,10 +63,10 @@ function usedb()
 {
 	#${${dbname:-$(proj get dbname)}}
 	[[ $1 == '-s' ]] && { db= ; shift }
-	if [ $# -gt 0 ]; then
-		isdb $1 && db=$1 || abort "$1: database not found"
+	if (($#)); then
+		isdb $1 && db=$1 || abort 127 "$1: database not found"
 	elif [[ -z $db ]]; then
-		db=$(chooser $(mklist $DBNAME $(dblist)))
+		db=$(chooser ${DBNAME:+-D $DBNAME} $(dblist))
 	fi
 }
 function dblist()
