many fixes and changes

diff --git a/zsh_libs/zsh_android b/zsh_libs/zsh_android
--- a/zsh_libs/zsh_android
+++ b/zsh_libs/zsh_android
@@ -1,36 +1,104 @@
-VERSION=1.0.0
+VERSION=1.0.1
 
-export ANDROID_SDK_ROOT=$(getfullpath $HOME/androidSDK)
-if ! [[ -d $ANDROID_SDK_ROOT && -d $ANDROID_SDK_ROOT/tools ]]; then
-	echo "Android SDK not found"
-	return 1
+integer ret
+local dir dirs location
+
+include file
+include functions
+
+location=$HOME/androidSDK # will be the sdk dir or a symlink to it
+ANDROID_SDK_ROOT=$(getfullpath $location)
+
+function isAndroidSDK()
+{
+	local desc
+	[[ -n $1 && -d $1/tools && -f $1/tools/source.properties ]] || return 1
+	desc="$(egrep '^Pkg.Desc' $1/tools/source.properties)"
+	[[ $desc == 'Pkg.Desc=Android SDK Tools' ]]
+}
+
+if ! isAndroidSDK $ANDROID_SDK_ROOT; then
+	ANDROID_SDK_ROOT=
+	dirs=$(run -v6 find $HOME -type d -iname android\* -and -not -iname androidSDK)
+	for dir in $dirs; do
+		if isAndroidSDK $dir; then
+			ANDROID_SDK_ROOT=$dir
+			break
+		fi
+	done
+
+	[[ -z $ANDROID_SDK_ROOT && ! -o interactive ]] && abort 127 'Android SDK not found'
 fi
+
+while ! isAndroidSDK $ANDROID_SDK_ROOT; do
+	#chooser -p 'Android SDK not found.' 'Copy from external drive' Download
+	#list=($HOME /usr/lib/android-sdk )
+
+	if [[ -n $ANDROID_SDK_ROOT ]]; then
+		techo -c warn "'$ANDROID_SDK_ROOT' does not look like an Android SDK folder. It should contain the subfolder $C[lred]\"tools\""
+	fi
+
+	[[ -o interactive ]] || abort 127 'Android SDK not found'
+	chooser -v ANDROID_SDK_ROOT --dir; ret=$?
+	if ((ret)) ; then
+		((ret==130)) && cancel
+		((ret>=127)) && abort
+	fi
+done
+
+if [[ ! -d $location ]]; then
+	[[ -h $location ]] && rm -f $location
+	ln -s $ANDROID_SDK_ROOT $location
+fi
+
+export ANDROID_SDK_ROOT
 export ANDROID_HOME=$ANDROID_SDK_ROOT
 export ANDROID_PLATFORM_TOOLS=$ANDROID_SDK_ROOT/platform-tools
 path+=($ANDROID_HOME/emulator $ANDROID_HOME/tools $ANDROID_HOME/tools/bin $ANDROID_PLATFORM_TOOLS)
 
-tmp=($ANDROID_HOME/build-tools/*(/On[1]))
-export ANDROID_BUILD_TOOLS=$tmp
+techo -c head ANDROID_HOME$C_="$C[warn]'$ANDROID_HOME'$C_"
+
+[[ -f /lib/udev/rules.d/51-android.rules ]] || { techo "Installing udev rules"; run apt install android-sdk-platform-tools-common & }
+
+ANDROID_BUILD_TOOLS=($ANDROID_HOME/build-tools/*(/On[1]))
+export ANDROID_BUILD_TOOLS
 if [[ -d $ANDROID_BUILD_TOOLS ]]; then
 	alias aapt=$ANDROID_BUILD_TOOLS/aapt
+	techo -c head ANDROID_BUILD_TOOLS$C_="$C[warn]'$ANDROID_BUILD_TOOLS'$C_"
 else
-	echo 'Build tools dir not found'
+	techo -c warn 'Build tools dir not found'
 fi
 
-alias gcloud='source $HOME/google-cloud-sdk/completion.zsh.inc; path+=($HOME/google-cloud-sdk/bin); unalias gcloud'
+#alias gcloud='source $HOME/google-cloud-sdk/completion.zsh.inc; path+=($HOME/google-cloud-sdk/bin); unalias gcloud'
 
 # Get package name from apk file
 function getPkg()
 {
     #chkCmdInst aapt
-    aapt dump badging $1 | grep package:\ name | cut -f2 -d\'
+    aapt dump badging $1 | grep 'package: name' | cut -f2 -d"'"
 }
-return
+
+function vscode()
+{
+	code &
+}
+
+function androidenv()
+{
+	local var vars=()
+	for var in ANDROID_SDK_ROOT ANDROID_HOME ANDROID_PLATFORM_TOOLS; do
+		var+=($var="'${(P)var}'")
+	done
+
+	echo $var
+	echo "export PATH=$PATH"
+
+}
 
 #APPS="${ANDROID_APPS:-$HOME/PeD/android}"
 #[ -d "$APPS" ] || APPS="$HOME/apps"
 #ANDROID_APPS="$APPS"
-export ANDROID_APPS APPS CLOUD_APPS CLOUD_INBRAMED
+# export ANDROID_APPS APPS CLOUD_APPS CLOUD_INBRAMED
 
 #export TREADMILL=$APPS/Treadmill
 #export TREADMILL_RES=$TREADMILL/app/src/main/res
diff --git a/zsh_libs/zsh_functions b/zsh_libs/zsh_functions
--- a/zsh_libs/zsh_functions
+++ b/zsh_libs/zsh_functions
@@ -47,13 +47,17 @@ function regex {
 
 # --okcodes button codes
 # --bcb button callback - cb args: ret str buttons
+#@TODO: gxmessage returns 1 on ESC... why?
 function input()
 {
 	local _var _opts p gui z c title raw _buttons okcodes tmp
-	local colors args str current gx cb ret
-	zparseopts -M -D -A _opts - c:=c p:=p v:=_var I: -save-index:=I D:=current \
-		g=gui z=z t:=title r=raw \
+	local args str current gx cb cprompt
+	integer ret
+	zparseopts -M -D -A _opts - c: p:=p v:=_var I: -save-index:=I D:=current \
+		g=gui z=z t:=title r=raw -clear-buffer \
 		b:=_buttons -buttons:=b -bcb:=cb N:=okcodes -okcodes:=N
+
+	# [[ -t
 
 	typeset -A buttons=(Cancel 130 Ok 0)
 	if (($#_buttons)); then
@@ -66,7 +70,6 @@ function input()
 		okcodes=($=okcodes[2]) #@TODO also split on comma
 	fi
 
-	colors=(-fg white -bg black)
 	p=${p[2]:-Input text}
 	title=$title[2]:-Input} # window title
 	if (($#_var)); then
@@ -77,26 +80,37 @@ function input()
 		str="$@"
 	fi
 
+	if (($+_opts[--cprompt])); then
+		cprompt=$_opts[--cprompt]
+		p=$(stripcolors $cprompt)
+	elif [[ $p[-1] != ' ' ]]; then # if last char is not a space
+		c=${_opts[-c]:-head}
+		cprompt=$C[$c]$p"$C_: "
+	fi
+
 	{
-		if [[ -n $DISPLAY && -z $raw ]] && type gxmessage >/dev/null && ; then
-			gx=1
-			if [[ ${p: -1} != ' ' ]]; then # if last char is not a space
-				techo -n -c ${c[2]:-head} "$p$C_: "
+#		if [[ -n $DISPLAY && -z $raw ]] && type gxmessage >/dev/null && ; then
+		if [[ -t 0 && -c $TTY ]]; then
+			#print "${(k)buttons}: "
+			(($+_opts[--clear-buffer])) && clearBuffer
+			if [[ -o zle ]]; then
+				# @bug vared -p $cprompt -e str # not working with prompt and read at same line
+				techo $cprompt
+				vared -e str
 			else
-				techo -n $c $p
+				techo $cprompt
+				read -r str
 			fi
+		elif [[ -n $DISPLAY ]]; then
+			type gxmessage >/dev/null || chkCmd gxmessage
+			local colors=(-fg white -bg black)
+			gx=1
+			techo -n $cprompt
 			args=($colors -name name -center -ontop -wrap -buttons "$(implode -A':' buttons ',')")
 			str=$(gxmessage $args -title "$title" -entrytext "$str" "$p")
 			#@ is returning 1, should be ok, but empty str, but since code is 1, we can manually set str
 		else
-			#print "\n$title\n"${(k)buttons}": "
-			print "$p: "
-			if [[ -o zle ]]; then
-				#techo # newline, because vared clears the line
-				vared -e str
-			else
-				read -r str
-			fi
+			abort 127 'No X or terminal attached'
 		fi
 		ret=$?
 	} always {
@@ -124,16 +138,18 @@ function input()
 
 	#(($#str)) || return 10
 	if ((gx && $#str)) && techo -r -c warn $str
-	
+
+	# output value entered
 	if (($#_var)); then
 		typeset -g "$_var=$str"
 	else
 		echo $str
 	fi
 
+	# output return code
 	if (($+_opts[-I])); then
 		typeset -gi "$_opts[-I]=$ret"
-		techo -c warn "Selected index: $ret"
+		dbgecho -c warn "Selected index: $ret"
 	fi
 
 	return 0
@@ -148,27 +164,24 @@ function confirm()
 {
 	local ret a c
 	if [[ "$1" != -c ]]; then
-		c=(-c lcyan)
+		c=(-c warn)
 	fi
-
-	clearBuffer
 
 	techo -n $c "$@" "(y/N)? "
-	if [[ -n "$BASH" ]]; then
-		while [[ "$a" != 'y' ]] && [[ "$a" != 'n' ]]; do
-			read -n 1 -r a
-		done
-		return $ret
-	fi
 	readkey -C -q; ret=$?
-	echo
+	clearBuffer # consume any garbage
+	if ((ret)); then
+		techo 'n'
+	else
+		techo 'y'
+	fi
 	return $ret
 }
 
 function readkey()
 {
 	local _k1 _k2 _k3 _k4 _k5 _k6 _k7 # _k8 _k9
-	
+
 	function _cancel() { throw 130 }
 
 	{
@@ -186,7 +199,7 @@ function readkey()
 			read -krs -t 0.0001 _k7 # && read -krs -t 0.0001 _k2 && read -krs -t 0.0001 _k3 &&
 
 		KEY+="$_k1$_k2$_k3$_k4$_k5$_k6$_k7"
-		((DEBUG)) && techo -r - "${(q)KEY}"
+		dbgecho -r - "${(q)KEY}"
 		return 0
 	} always {
 		ret=$?
@@ -201,20 +214,21 @@ function readkey()
 function chooser()
 {
 	local noSelect sep field bytes search current head foot
-	local _olist chosen chosenList selectors ofs
-	local file opt _opts selected selected_idx list_keys events
+	local _olist chosen selectors ofs
+	local file opt _opts selected selected_idx list_keys events items
 	integer multi i j noAutoSelect
 
 	selectors=(${${(@uM)@#-[bfsR]}#-}) # keep options order
 
 	zparseopts -D -M -A _opts - n:=noSelect S: \
-		 I: -save-index:=I v: D:=current -ifs: \
+		 I: -save-index:=I v: D:=current -ifs: -items: \
 		 s:=sep f:=field R:=regex b:=bytes ofs:=ofs \
 		 H:=head -head:=H p:=H F:=foot -foot:=F \
 		 -simple -multi -use-keys -selected: E:=events -events:=E \
 		 -file -files -dir -no-auto-select -strip-color
 
 	typeset -g ACTION=''
+	typeset -a chosenList
 	multi=$+_opts[--multi]
 
 	if (($+_opts[--dir])); then
@@ -222,6 +236,7 @@ function chooser()
 		multi=1
 		_opts[--file]=1
 	fi
+	(($+_opts[--items])) && items=$_opts[--items]
 	search=$_opts[-S]
 	(($#events || $+_opts[--no-auto-select])) && noAutoSelect=1
 
@@ -239,44 +254,80 @@ function chooser()
 
 	typeset -A list_keys
 	if (($+_opts[--file] || $+_opts[--dir])); then
-		local out="$TMPDIR/ranger.out" ropts=()
-		if (($+_opts[--dir])); then
-			ropts+=(--choosedir $out --show-only-dirs)
-		elif ((multi)); then
-			ropts+=(--choosefiles $out)
-		else
-			ropts+=(--choosefile $out)
-		fi
+		if ((use_ranger)); then
+			local out="${TMPDIR:-${TMP:-/tmp}}/ranger.out" ropts=()
+			if (($+_opts[--dir])); then
+				ropts+=(--choosedir $out --show-only-dirs)
+			elif ((multi)); then
+				ropts+=(--choosefiles $out)
+			else
+				ropts+=(--choosefile $out)
+			fi
 			#--list-tagged-files=tag
-		if (($+_opts[--selected])); then
-			ropts+=(--selectfile "$=_opts[--selected]")
-		elif (($#)); then
-			ropts+=(--selectfile "$1")
+			if (($+_opts[--selected])); then
+				ropts+=(--selectfile "$=_opts[--selected]")
+			elif (($#)); then
+				ropts+=(--selectfile "$1")
+			fi
+			if ! type ranger >/dev/null; then
+				chkCmd ranger --git 'ranger/ranger' || abort $?
+			fi
+			ranger "$ropts[@]" || return
+			explode -v chosenList "$(<$out)" $'\n'
+		else
+			local _chTmp="$1"
+			if (($+_opts[--file])); then
+				while [[ ! -f $_chTmp ]]; do
+					(($#_chTmp)) && techo -c lred "$_chTmp is not a file."
+					input -v _chTmp -p "${head[2]:-Enter file}" || abort $?
+				done
+			elif (($+_opts[--dir])); then
+				while [[ ! -d $_chTmp ]]; do
+					(($#_chTmp)) && techo -c lred "$_chTmp is not a directory."
+					input -v _chTmp -p "${head[2]:-Enter directory}" || abort $?
+				done
+			fi
+			chosenList=($_chTmp)
 		fi
-		if ! type ranger >/dev/null; then
-			chkCmd ranger --git 'ranger/ranger' || abort $?
-		fi
-		ranger "$ropts[@]" || return
-		explode -v chosenList "$(<$out)" $'\n'
 	else
 		if (($+_opts[--use-keys])); then # keyboard shortcuts
 			if (($+_opts[--ifs])); then
 				abort -v3 2 'Not implemented --use-keys option together with --ifs'
 			fi
-			
-			(($# % 2)) && abort -v3 1 "Odd number of options with --use-keys: ""$@"
+
 			_olist=()
-			for ((i=1; i<=$#; )); do
-				local glob="$@[i++]"
-				if [[ -n $glob ]]; then
-					# keys are globs and value is element index
-					list_keys+=("$glob" $((i/2)))
-				fi
-				# element values
-				_olist+=("$@[i++]")
-			done
+			(($# % 2)) && abort -v3 1 "Odd number of options with --use-keys: ""$@"
+
+			if (($#items)); then
+				integer len=${(P)#items}
+				for ((i=1; i<=len; )); do
+					local glob= "${${(P)items}[i++]}"
+					if [[ -n $glob ]]; then
+						# keys are globs and value is element index
+						list_keys+=("$glob" $((i/2)))
+					fi
+					# element values
+					 _olist=("${${(P)items}[i++]}")
+				done
+			else
+				for ((i=1; i<=$#; )); do
+					local glob="$@[i++]"
+					if [[ -n $glob ]]; then
+						# keys are globs and value is element index
+						list_keys+=("$glob" $((i/2)))
+					fi
+					# element values
+					_olist+=("$@[i++]")
+				done
+			fi
 		else
-			if (($+_opts[--ifs])); then
+			if (($#items)); then
+				if (($+_opts[--ifs])); then
+					explode -v _olist "${${(P)items}[*]}" $_opts[--ifs]
+				else
+					_olist=("${${(P)items}[@]}")
+				fi
+			elif (($+_opts[--ifs])); then
 				explode -v _olist "$*" $_opts[--ifs]
 			else
 				_olist=("$@")
@@ -284,7 +335,7 @@ function chooser()
 		fi
 	fi
 
-	if (($+_opts[--file])); then
+	if (($+_opts[--file] || $+_opts[--dir])); then
 
 	elif (($#_olist > 1 || noAutoSelect)); then
 		chosenList=()
@@ -325,6 +376,7 @@ function chooser()
 				integer num_elem first last begin_idx end_idx noSelectAlign
 
 				max_lines=${PAGE_SIZE:-15}
+				((page_size=LINES>max_lines?max_lines:LINES))
 
 				typeset -A keys=(
 					'UP' $'\e[A' 'PGUP' $'\e[5~' 'HOME' $'\e[1~'
@@ -344,7 +396,7 @@ function chooser()
 						elif ((j < 36)); then
 							opt=$(inttochar $j + 55) # letter
 						else
-							techo '@TODO - ran out of key shortcuts: j='$j
+							#techo '@TODO - ran out of key shortcuts: j='$j
 							continue
 						fi
 						list_keys+=($opt $i)
@@ -357,7 +409,7 @@ function chooser()
 				((DEBUG)) && array_dump noSelect
 				((DEBUG)) && array_dump list_keys
 
-				#typeset -R $opt_wid opt
+				#typeset -R $opt_wid opt  # right justification, left padded value
 				((noSelectAlign=opt_wid+1))
 				if ((multi)); then
 					list_keys+=(' ' 'CHECK')
@@ -371,55 +423,6 @@ function chooser()
 					list_keys+=(${(U)events})
 				fi
 
-				# # # # # # # # #
-				# FIND ELEMENTS #
-				# # # # # # # # #
-				if [[ -z $search || $search != $last_search ]]; then
-					elem_show=() # clear
-					# elem_show has nothing to do with pagination. It indicates it's not filtered out.
-					# begin_idx and end_idx are used for that.
-					((num_elem=first=last=0))
-					for ((i=1; i<=$#_olist; i++)); do
-						if [[ $_olist[i] == (#i)*$search* ]]; then # case insensitive
-							elem_show[i]=1
-							#elem_show+=($i)
-							((num_elem++))
-							((first==0)) && first=$i
-							last=$i
-						fi
-					done
-					last_search=$search
-					((elem_show[current_key])) || current_key=$first
-				fi
-				#	first=1
-				#	last=$#_olist
-				#	elem_show=() # clear
-				#	for ((i=1; i<=$#_olist; i++)); do
-				#		elem_show[i]=1
-				#		#elem_show+=($i)
-				#	done
-				#	num_elem=$#_olist
-
-				# putting this here, as we might need to dynamically change page_size according to data
-				((page_size=LINES>max_lines?max_lines:LINES))
-
-				# TODO: find page where current_key belongs to
-				# at the beginning we draw all pages until we find it
-				#begin_idx=
-				begin_idx=$first
-				((end_idx=i-1))
-					#techo "begin=$begin_idx, end=$end_idx, current=$current_key"
-
-				# for page_size = 5: end = page_size - foot = 5 - 1 = 4
-				# in case of hidden elements (search filter)
-				# i j                     i j
-				#   header                  header
-				# 1 2  begin              5 2  begin
-				# 2   <- hidden elem      6 3
-				# 3 3                     7   <- hidden elem
-				# 4 4  end  j<page_size   8 4  end  j<page_size
-				#   footer                  footer
-				(($#head)) && techo -c head "$head[2]"
 				while ((loop)); do
 					if ((next_key)); then
 						last_key=current_key
@@ -515,7 +518,7 @@ function chooser()
 					(($#foot)) && techo -c head "$foot[2]"
 
 					# # # # # # # # # #
-					# iNPUT  HANDLING #
+					# INPUT  HANDLING #
 					# # # # # # # # # #
 					while readkey; do
 						case $KEY in
@@ -746,7 +749,7 @@ function chooser()
 		((DEBUG)) && array_dump _olist
 	else
 		print -r -- $_olist
-		((DEBUG)) && techo "chosen: $_olist"
+		dbgecho "chosen: $_olist"
 	fi
 
 	# Save index
@@ -757,9 +760,10 @@ function chooser()
 		else
 			typeset -gi "$_opts[-I]=$selected_idx"
 		fi
-		((DEBUG)) && techo "idx: $selected_idx"
+		dbgecho "idx: $selected_idx"
 	fi
 	#[[ ! -t 1 || -z $var ]] && print -r $_olist
+	(($#chosenList)) || return 10
 	return 0
 }
 
@@ -879,7 +883,7 @@ function chkCmd()
 			continue
 			;;
 		esac
-		
+
 		pkgList[i+1]=$tmp[1] # version
 		in_array -v n ';' tmp || n=2
 		desc=("${(@fqq)tmp[n+1,-1]}") # description
@@ -991,8 +995,9 @@ function run()
 {
 	local ret cmd fullcmd logfile watch cmdPrefix
 	local sudo trysudo dryrun color alert print
-	local cmdinst workdir okcodes debug noEx _opts
+	local cmdinst workdir okcodes debug noEx
 	integer verbose
+	typeset -A _opts
 
 	if [[ ${1:0:1} == - ]]; then
 		zparseopts -M -D -A _opts - v: c:=color a=alert p: e=noEx A=noAbort \
@@ -1018,7 +1023,12 @@ function run()
 	elif [[ $color[2] == (0|) ]] || ; then
 		color=''
 	fi
-	(($+_opts[-p])) && print=$_opts[-p]
+
+	if (($+_opts[-p])); then
+		print=$_opts[-p]
+	else
+		unset print
+	fi
 	if ((verbose>=3-$+print)); then
 		if ((verbose>=6)); then
 			if (($+print)) && [[ $print != $fullcmd ]]; then
@@ -1149,7 +1159,7 @@ function banner()
 		fi
 		return
 	fi
-	
+
 	if [ -n "$c" ]; then
 		$cmd -f pagga "$@" | colorify -c $c >$TTY
 	elif type lolcat >/dev/null; then
