Ajuste

diff --git a/zsh_libs/zsh_file b/zsh_libs/zsh_file
--- a/zsh_libs/zsh_file
+++ b/zsh_libs/zsh_file
@@ -1,5 +1,5 @@
 VERSION=1.0.9
-#lazyload=syncDirs,awkWrapper,getfullpath,getpath,getext,getfilename,isDir,isEmptyDir,box,ddiff
+#lazyload=syncDirs,awkWrapper,getfullpath,getpath,getext,getfilename,isDir,isEmptyDir,box,ddiff,syncFile
 
 alias fullpath='getfullpath'
 alias full='getfullpath'
@@ -259,6 +259,15 @@ typeset -A rsyncCodes=(
 	35 'Timeout waiting for daemon connection'
 )
 
+function syncFile()
+{
+	local file=$1
+	local base=$(git root)
+	croot
+	local projName=$(basename $PWD)
+	syncDirs -cf $file 192.168.10.11:$projName/$file
+}
+
 # Added 2019-05-03 16:50
 comp+=("syncDirs=rsync")
 function syncDirs()
@@ -271,7 +280,7 @@ function syncDirs()
 	zparseopts -D -M -A _opts - q=quiet s=sudo d=dry 'R' -relative=R 'z' -compress=z \
 		c=checksum -reverse=reverse -no-add-slash=noSlash -no-delete=noDelete \
 		E:=excludeFrom -exclude-from:=E e:=exclude -exclude:=e -port: \
-		-no-perms -no-user -no-group
+		-no-perms -no-user -no-group f=dontAsk
 
 	[[ -z "$sudo" ]] && sudo='-S'
 	(($# >= 2)) || abort 1 "usage: $0 source1 [.. sourceN] target1[,target2]"
@@ -330,38 +339,38 @@ function syncDirs()
 			#	sshArgs=(ssh $sshCFG[$host])
 			#fi
 
-			ret=($(ssh $host \
-				"if [[ -d $p ]]; then
-					glob=("$p"(N/F))
-					v=\$#glob
-					if ((v)) && [[ -f $p/rsync.ignore ]]; then
-						echo -n 1i
-					else
-						echo -n \$v
-					fi
-				elif [[ -f $p ]]; then
-					echo -n f
-				fi"
-			))
-			case $ret in
-				1*) # dir
-					((!$#noSlash)) && [[ ${dir: -1} != / ]] && src[$n]+='/'
-					if [[ $ret == '1i' ]]; then
-						#@TODO: scp $dir/rsync.ignore /tmp)
-						#rsArgs+=(--exclude-from=$fIgnore)
-					fi
-					;;
-				f) ;; # file
-				0)
-					confirm -c warn "@TODO Empty remote directory$C_: '$C[lred]$host:$p$C_'. Create dir" || cancel
-					src[$n]=(); ((n--))
-					;;
-				'')
-					confirm -c warn "Source '$C[lred]$host:$p$C_' not found. Ignore and continue" || cancel
-					src[$n]=(); ((n--))
-					;;
-				*) abort 1 "Invalid response from $host: '$C[lred]$ret$C_'" ;;
-			esac
+			#ret=($(ssh $host \
+			#	"if [[ -d $p ]]; then
+			#		glob=("$p"(N/F))
+			#		v=\$#glob
+			#		if ((v)) && [[ -f $p/rsync.ignore ]]; then
+			#			echo -n 1i
+			#		else
+			#			echo -n \$v
+			#		fi
+			#	elif [[ -f $p ]]; then
+			#		echo -n f
+			#	fi"
+			#))
+			#case $ret in
+			#	1*) # dir
+			#		((!$#noSlash)) && [[ ${dir: -1} != / ]] && src[$n]+='/'
+			#		if [[ $ret == '1i' ]]; then
+			#			#@TODO: scp $dir/rsync.ignore /tmp)
+			#			#rsArgs+=(--exclude-from=$fIgnore)
+			#		fi
+			#		;;
+			#	f) ;; # file
+			#	0)
+			#		confirm -c warn "@TODO Empty remote directory$C_: '$C[lred]$host:$p$C_'. Create dir" || cancel
+			#		src[$n]=(); ((n--))
+			#		;;
+			#	'')
+			#		confirm -c warn "Source '$C[lred]$host:$p$C_' not found. Ignore and continue" || cancel
+			#		src[$n]=(); ((n--))
+			#		;;
+			#	*) abort 1 "Invalid response from $host: '$C[lred]$ret$C_'" ;;
+			#esac
 		elif [[ -d $dir ]]; then
 			if isEmptyDir $dir; then
 				confirm -c warn "Empty directory$C_: '$C[lred]$dir$C_'. Ignore and continue" || cancel
@@ -383,10 +392,12 @@ function syncDirs()
 	[[ -n $excludeFrom ]] && excludePatterns+=("${(@f)$(egrep -v '^ *#' $excludeFrom[2])}")
 	#(--exclude-from="${excludeFrom[2]}")
 	excludePatterns+=('backup*' '*.local' '.git' 'node_modules')
-	chooser -v excludePatterns --multi --selected "$excludePatterns" $excludePatterns
-	cod=$?
-	if ((cod && cod!=10)); then
-		confirm 'Cancel' && cancel
+	if [[ -z $dontAsk ]]; then
+		chooser -v excludePatterns --multi --selected "$excludePatterns" $excludePatterns
+		cod=$?
+		if ((cod && cod!=10)); then
+			confirm 'Cancel' && cancel
+		fi
 	fi
 	# Parameter Expansion -> $^ RC_EXPAND_PARAM
 	(($#excludePatterns)) && rsArgs+=(--exclude=$^excludePatterns)
@@ -427,7 +438,7 @@ function syncDirs()
 		if (($#data)); then
 			nothing=0
 			echo $data
-			if confirm "Do it"; then
+			if [[ -n $dontAsk ]] || confirm "Do it"; then
 				run $sudo rsync --info=PROGRESS2 $rsArgs $permFlags "$src[@]" $dir ; cod=$?
 				if ((cod)); then
 					techo $rsyncCodes[$cod]
@@ -486,7 +497,13 @@ function syncDirs()
 	[[ $nothing -eq 1 ]] && techo -c cyan "Nothing to do"
 	return 0
 }
-
+function sshdiff()
+{
+	local file base
+	file=$1
+	base=$(basename $PWD)
+	ssh 192.168.10.11 "cat $base/$file" | diff -u - $file
+}
 function boxconfig()
 {
 	local cfgfile arg val opts _var
@@ -567,6 +584,7 @@ function box()
 				return
 			;;
 			list|search)
+				(($#VSCODE_ZDOTDIR || $#NOBOX)) && return 0 # ignore vscode
 				search=$box
 				if [[ -n $search && -d $base/$search ]]; then
 					cmd='open'; box=$search
diff --git a/zsh_libs/zsh_git b/zsh_libs/zsh_git
--- a/zsh_libs/zsh_git
+++ b/zsh_libs/zsh_git
@@ -17,10 +17,12 @@ alias gstat='gstatus'
 alias grest='grestore'
 alias staged='gstaged'
 alias gds='gstaged'
+alias gdsw='g diff --staged --word-diff=color --word-diff-regex=.'
+alias master="git checkout master"
 #local tmp=$(git rev-parse --short HEAD || echo '')
 typeset -gi hashAbbvLen=7
 
-export github_token='b2e74253b94398066f3938bb63120f51ca7745ee'
+export github_token=''
 
 [[ ! -v comp ]] && typeset -g -a comp
 
@@ -71,7 +73,7 @@ function croot()
 
 gFormat=(
 	'%h'				# short hash
-	'%<(3,trunc)%cn'	# author
+	'%<(5,trunc)%cn'	# author
 	'%C(auto)%d%Creset'	# ref names
 	'%s'				# subject
 	'(%Cgreen%ci %C(#4579aa)%cr%Creset)' # date
@@ -99,11 +101,11 @@ function glog()
 	fi
 
 	hashP='[a-f0-9]{5,}'
-	authorP='[A-Z]'
+	authorP='[A-Z][a-z][a-z]'
 	refsP='\(.*\)'
 	subjectP='.*'
 	dateP='\(.*\)'
-	typeset -A authorColor=('E' yellow 'P' warn) # '*' lcyan)
+	typeset -A authorColor=('Eli' yellow 'Vin' lcyan 'Kas' lred)
 	for color in $authorColor; do colorSet $color; done  # setup colors
 	#lcolors=('' yellow '' '' '')
 	while read -r line; do
@@ -112,13 +114,14 @@ function glog()
 		if [[ $line =~ '(.*) ('$~hashP') ('$~authorP').. ('$~refs')? ?('$subjectP') ('$~dateP')' ]]
 		then
 			author=$match[3]
+			[[ $author == 'Jef' ]] && author='Kas'
 			color=$authorColor[$author]
+			[[ -z $color ]] && color='head'
 			match[3]=$C[$color]$author$C_
 
 			hash=$match[2]
 			match[2]=$(colorhash $hash)
 
-			#TODO save colors and data in separated arrays
 			aline="$match"
 		else
 			aline="$line"
@@ -176,6 +179,7 @@ function gpull()
 				*)	;;
 		esac
 	}
+	echo $tmp
 }
 
 function gshow()
@@ -569,26 +573,34 @@ function gmerge() #@TODO
 	fi
 }
 
-function ggrep() #@TODO
+function ggrep()
 {
-	local files pattern
-	pattern=$(echo "$@" | awk -F' - ' '// {print $1}')
-	files=$(echo "$@" | awk -F' - ' '// {print $2}')
-	#pattern="${@%%_*}"
-	#files="${@#*_}"
-	#while arg in "$@"; do
-	#    [[ "$arg" != "--" ]]
-	#    [[ ]] && files+=" $arg"
-	#done
-	set -x
-	git grep "$pattern" $(git rev-list --all -- ${=files}) -- ${=files}
-	set +x
+#	local files pattern
+#	pattern=$(echo "$@" | awk -F' - ' '// {print $1}')
+#	files=$(echo "$@" | awk -F' - ' '// {print $2}')
+#	#pattern="${@%%_*}"
+#	#files="${@#*_}"
+#	#while arg in "$@"; do
+#	#    [[ "$arg" != "--" ]]
+#	#    [[ ]] && files+=" $arg"
+#	#done
+#	set -x
+#	git grep "$pattern" $(git rev-list --all -- ${=files}) -- ${=files}
+#	set +x
+	grep -rn "$1" $(echo $(git diff --name-only))
 }
 
 function commit() #@TODO
 {
 	local m args amend
 	zparseopts -D -M - m:=m A=amend -amend=A
+
+	getbranch -q
+
+	[[ $branch == 'master' ]] && {
+		confirm "Commit to master branch" || cancel
+	}
+
 	[[ $amend[1] == '-A' ]] && amend='--amend'
 	#@TODO check for empty changes
 	if [[ -n "$1" && ${1:0:1} != - ]]; then
@@ -764,10 +776,11 @@ function gpush()
 		if [[ -z $remote ]]; then
 			gremote || { techo -c warn 'No remotes'; return 10 }
 		fi
-		branch=${2:-$VCS_STATUS_LOCAL_BRANCH}
-		if [[ -z $branch ]]; then
-			getbranch || { techo -c warn 'No branches'; return 10 }
-		fi
+		[[ -n "$2" ]] && branch=$2 || {
+			getbranch -q || abort 10 'No branches'
+		}
+
+		[[ $branch == 'master' ]] && abort 2 "Can't push to master branch"
 		run git push --set-upstream ${(kv)_opts} $remote[1] $branch
 		[[ $branch != main && $branch != master ]] && gpr
 	fi
@@ -817,6 +830,35 @@ function gswitch()
 	return 1
 }
 
+function remove_local_unused_branches()
+{
+	git fetch -p && {
+		for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do
+			confirm "Remove branch $branch" && git branch -d $branch
+		done
+	}
+}
+
+function remove_remote_branch()
+{
+	local br
+
+	gremote
+	#while chooser -f1 -v br $(g branch --merged $remote[1]/master -r | grep -v master); do
+	while chooser --strip-color --ifs $'\n' -f1 -v br "$(listbranch --merged -r | grep -v '/master')"; do
+		gshow -l $br
+		br=${br#origin/}
+		confirm "Remove remote branch $br" && run -v6 git push $remote[1] -d $br
+	done
+}
+
+function remove_local_branch()
+{
+	local br
+	br=$(git for-each-ref --format "%(refname:short) %(upstream:track)" refs/heads | grep -F " [gone]" | cut -d" " -f1)
+	confirm "Remove these local branches: $br" && for v in $(echo $br); do git branch -d $v; done
+}
+
 function gbranch() #@TODO
 {
 	local list delete cmd get current opts
@@ -844,6 +886,7 @@ function gbranch() #@TODO
 		-l) listbranch "$@" ;;
 		-d)
 			#(())
+			echo git fetch -p
 			git fetch -p
 			#git branch -d $1
 			#gremote || { [ -t 1 ] && techo -c warn 'No remotes'; return 10 }
@@ -858,7 +901,7 @@ function listbranch()
 	local _cols head merged to compare_to all _opts opts=()
 	zparseopts -M -D -A _opts - -no-merged::=merged -merged::=merged a -all=a O:
 	#zparseopts -M -D -A _opts - -no-merged::=N m:: -merged::=m 'a' -all=a O:
-	gremote || return
+	gremote
 	compare_to="$remote[1]/master"
 	#@TODO get "main" branch
 	if (($+_opts[-a])); then
@@ -887,8 +930,10 @@ function listbranch()
 		_cols+=($=_opts[-O])
 	fi
 
-	[[ -n $_cols[(r)author] ]]
-	#%(authorname)
+	if [[ -n $_cols[(r)author] ]]; then
+		#%(authorname)
+	fi
+
 	for tmp in $_cols; do
 
 	done
@@ -899,8 +944,10 @@ function listbranch()
 		'%(color:yellow)%(align:20,left)%(refname:short)%(end)%(color:reset)'
 		'%(color:red)%(objectname:short)%(color:reset)'
 		'%(color:reset)%(contents:subject)'
+		'%(authorname)'	# author
 		'(%(color:green)%(committerdate:iso) %(color:#4579aa)%(committerdate:relative)%(color:reset))'
 	)
+#	%(authorname)
 	git --no-pager branch --sort=committerdate --format="$glineFormat" --color=always $opts "$@"
 	#todo colorhash
 }
@@ -1276,11 +1323,12 @@ function gdiff()
 # @return revision, if found
 function gfind()
 {
-	local rev revs file filehash hash since=(--since='34 days ago')
+	local rev revs file filehash hash since=(--since='200 days ago')
 	file="$1"; shift 1
 	# git hash for file
 	{
-		[[ -f file ]] && filehash=$(git hash-object $file) || filehash=$(git ls-tree HEAD $file) || return 1
+		[[ -f $file ]] && filehash=$(git hash-object $file) || \
+			filehash=$(git ls-tree HEAD $file | explode -z --stdin ' ' 3) || return 1
 	} 2>/dev/null
 	revs=($(git log $since --all --pretty=%H -- "$file"))
 	for rev in $revs; do
@@ -1372,7 +1420,7 @@ function gstatus()
 			fi
 		fi
 		if (($+_opts[--branch])); then
-			dev_diff_b=$(git diff --color=never $_opts[--branch] -- $f)
+			dev_diff_b=$(git diff --color=never $_opts[--branch] -- $groot/$f)
 			ndev_diff_b=$#dev_diff_b
 			if ((!ndev_diff_b)); then
 				diffs+=("$C[ok]== $_opts[--branch]")
@@ -1381,7 +1429,7 @@ function gstatus()
 				diffs+=("$C[lred]$ndev_diff_b != $_opts[--branch]")
 			fi
 		fi
-		if revfound=($(gfind $f)); then
+		if revfound=($(gfind $groot/$f)); then
 			rev=$revfound[1]
 			diffs+=("$C[ok]== * $(colorhash $rev)")
 			case $revfound[2] in
@@ -1402,7 +1450,8 @@ function gstatus()
 			((alerts++))
 			k=$C[lred]
 		fi
-		techo $stat $k$f $diffs
+		filedatelastchange=$C[warn]$(stat -c '%y' $groot/$f | cut -d'.' -f 1)
+		techo $stat $k$f $filedatelastchange$C_ $diffs
 		#$(($#changed - $#dev_diff)) $diff_changed_dev
 	done
 	if ((alerts)); then techo -c lred "Non $C[warn]recoverable changes found"; \
diff --git a/zsh_libs/zsh_idiomus b/zsh_libs/zsh_idiomus
--- a/zsh_libs/zsh_idiomus
+++ b/zsh_libs/zsh_idiomus
@@ -291,3 +291,54 @@ function hotmartCSVImport()
 	((j)) && echo "$out;" # flush
 
 }
+
+function create_include_file()
+{
+	[[ $# -eq 0 ]] && {
+		echo "Usage: $0 <newversion> <file>"
+		echo "\tExample: $0 37 transaction.utils"
+		exit 0
+	}
+
+	[[ -d $PWD/.git ]] || cd $(git rev-parse --show-toplevel)
+
+	version="$1"
+	filenoext="${2%%.php}"
+	file="$filenoext.php"
+	vdir="v$version"
+
+	[[ -d $vdir ]] || {
+		confirm "Create $PWD/$vdir" || cancel
+		mkdir "$vdir" 
+	}
+
+	newfile="$vdir/$file"
+	oldversion=$((version - 1))
+
+
+	oldfile=$oldversion/$file
+	olddata=$(< $oldfile)
+	IFS="\n" olddatalines=(($olddata))
+
+	oldisinclude=0
+	[[ $#olddatalines == 2 || $#olddatalines == 3 ]] && oldisinclude=1
+
+	if [[ -f $newfile ]]; then
+		cat $newfile
+		if ((oldisinclude)); then
+			diff -q $newfile $oldfile
+		fi
+		abort 'Existent file. Aborting';
+	fi
+
+	echo $#olddatalines lines
+
+
+	if [[ $#olddatalines == 2 || $#olddatalines == 3 ]]; then
+		# is a include, so we just copy file
+		echo -n $olddata > $newfile;
+	else
+		# create include
+
+	fi
+}
