more fixes

diff --git a/zsh_libs/zsh_proc b/zsh_libs/zsh_proc
--- a/zsh_libs/zsh_proc
+++ b/zsh_libs/zsh_proc
@@ -4,30 +4,45 @@ VERSION=1.0.2
 
 function cwdof()
 {
-	for p in $(pidof $1); do
-		ls -ld /proc/$p/cwd 2>/dev/null
-	done | awk -F'-> ' '{print $2}' | uniq
+	local arg
+	for arg; do
+		if [[ $arg != [0-9]# ]]; then
+			p=$(pidof -s $arg) || { techo -c warn "$arg not found"; continue }
+		else
+			p=$arg
+		fi
+		#ls -ld /proc/$p/cwd 2>/dev/null
+		getfullpath /proc/$p/cwd 2>/dev/null
+	done
 }
 
-function ps()
+comp+=(p=ps)
+function p()
 {
 	local kern select search user pid ppid tty cmd
-	local cols args
+	local cols appendcols args
 
 	[[ -o interactive ]] || { command ps "$@" ; return }
-	zparseopts -D - c:=cmd k=kern u::=user p:=pid P:=ppid t:=tty o:=cols
+	zparseopts -D -M - c:=cmd k=kern u::=user t::=tty \
+		p:=pid P:=ppid -ppid:=P o:=cols O:=appendcols
 	
 	# # # # # # #
 	# selection #
 	# # # # # # #
 	if [[ -n $user ]]; then
-		[[ -n $user[2] ]] || user[2]=(${UID:-$USER})
+		(($#user[1] > 2)) && user=(-u ${user[1]:2}) || user[2]=(${UID:-$USER})
 	fi
-	if [[ -z "$pid" && $1 = [0-9]## ]]; then
+
+	if (($#tty)); then
+		(($#tty[1] > 2)) || tty[2]=($TTY)
+	fi
+
+	(($#cmd)) && cmd=(-C "$(getfilename $cmd[2])")
+	if [[ -z $pid && $1 == [0-9]## ]]; then
 		pid=(-p $1)
 		shift
-	elif ((! $#cmd )) && [[ ${1:0:1} = [[:alnum:]_]## ]]; then
-		cmd=(-C "$1")
+	elif ((! $#cmd )) && [[ ${1:0:1} = [[:alpha:]_]## ]]; then
+		cmd=(-C $1)
 		shift
 	fi
 	#if in_array args '-C'; then
@@ -45,17 +60,18 @@ function ps()
 	##  ##  ##
 	# output #
 	##  ##  ##
-	if [[ -n $o ]]; then
-		cols=($(explode "$o[2]" ','))
+	if [[ -n $cols ]]; then
+		cols=($(explode "$cols[2]" ','))
 		#elif in_array args --any '-o,-O'; then
 	else
-		cols=(pid ppid %cpu stat cmd) # euid if not -u or -u $x with $x != $UID
+		cols=(pid ppid %cpu stat cmd)
+		[[ -n $user[2] ]] && cols+=() # euid if not -u or -u $x with $x != $UID
 	fi
 	if [[ -n $appendcols ]]; then
 		cols+=($(explode "$appendcols[2]" ','))
 		#elif in_array args --any '-o,-O'; then
 	fi
-	args+=(-o "${(j.,.)${(u)cols}}")
+	args+=(-o "${(uj.,.)cols}")
 
 	run command ps $args
 }
@@ -82,22 +98,27 @@ function waitOnPids()
 # Check command (-c): run periodically a command until main program ends
 function waitPid()
 {
-	local ret pid cmd retCheck=2 checkCmd delay=0.4 killSent
-	integer ret=0 pid killSent=0
-	zparseopts -D - p:=pid c:=checkCmd d:=delay
-	cmd=(${(z)@})
-	[[ -n $checkCmd ]] && checkCmd=(${(z)checkCmd})
-	$cmd & pid=$!
+	local cmd checkCmd delay force
+	integer ret=0 pid killSent=0 retCheck=2
+	zparseopts -D - c:=checkCmd d:=delay f=force
+	pid=$1
+	[[ -n $checkCmd ]] && checkCmd=(${(z)checkCmd[2]})
+	delay=${delay[2]:-1}
 	while kill -0 $pid 2>/dev/null; do
 		sleep $delay
-		if [[ -n $checkCmd ]]; then
-			if [[ "$killSent" -gt 3 ]]; then
-				confirm "Force kill $cmd" && kill -9 $pid && break ||
+		if (($#checkCmd)); then
+			if ((killSent > 3)); then
+				if (($#force)) || {
+					[[ -o interactive ]] && confirm "Force kill $cmd"
+				}; then
+					kill -9 $pid && break
+				else
 					killSent=0
+				fi
 			fi
 			$checkCmd ; ret=$?
-			if [[ -n $retCheck && $ret -gt $retCheck ]]; then
-				techo -c warn "Killing ${cmd[1]} ($pid)"
+			if ((retCheck && ret > retCheck)); then
+				techo -c warn "Killing $cmd[1] ($pid)"
 				kill $pid ; sleep 1
 				((killSent++))
 			fi
diff --git a/zsh_libs/zsh_sql b/zsh_libs/zsh_sql
--- a/zsh_libs/zsh_sql
+++ b/zsh_libs/zsh_sql
@@ -1,4 +1,9 @@
 VERSION=1.0.4
+#lazyload=sql,tableshow,tablelist
+alias sql="noglob sql"
+alias sqlmaq="noglob sql --ssh maquina"
+#head
+
 # databases data dir
 DB_DATA_DIR=/var/lib/mysql
 DBNAME='idiomus'
@@ -21,8 +26,6 @@ function dbtstamp()
 		awk '{print $6,$7,$8}' | sort --numeric-sort
 }
 
-alias sql="noglob sql"
-alias sqlmaq="noglob sql --ssh maquina"
 # execute mysql command
 # sql [-d dbname] [-f file.sql] SELECT ...
 function sql()
@@ -39,36 +42,108 @@ function sql()
 		sql="$*"
 	fi
 
+	typeset -Tf parseSqlErrors
+	coproc parseSqlErrors
 	if [[ -n $host ]]; then
-		ssh $host[2] "noglob sql ${(qqq)sql}"
+		ssh $host[2] "noglob sql ${(qqq)sql}" 2>&p
 	else
 		[[ -n $nodb ]] || usedb $name[2]
 		if [[ -n $db ]]; then
-			user=${user[2]:-${sqlUser[$db]:-root}}
+			user=${user[2]:-${sqlUser[$db]:-$root}}
 			pass=${pass[2]:-$sqlPass[$user]}
 		else
 			user=${user[2]:-$sqlUser[root]}
 			pass=${pass[2]:-$sqlPass[$user]}
 		fi
-		mysql $silent ${user:+-u$user} ${pass:+-p"$pass"} -e "$sql" $db
+		mysql $silent ${user:+-u$user} ${pass:+-p"$pass"} -e "$sql" $db 2>&p
 	fi
+	echo EOF >&p
+	{
+		local tmp split errCode sqlState line msg
+		#@TODO sort errors by file before opening files
+		while read -p errCode sqlState line tmp msg; do
+			split=(${(Q)${(z)tmp}})
+			#m=$split[1]; sqlState=$split[2]; line=$split[3]
+			techo -c lred  "ERROR $errCode ($sqlState) at line $line: $C[warn]$msg$C_"
+			#@TODO this is going to run once per terminal. Wanted: once total.
+			#@idea run this part only on current terminal, if there is one focused.
+		done
+		if type v 2>&1 >/dev/null; then
+			#v $file:$line &
+		else
+			#${EDITOR:-vim} $file +$line &
+		fi
+	}
+
+	#ERROR 1452 (23000) at line 1: Cannot add or update a child row: a foreign key constraint fails (`idiomus`.`#sql-426_49`, CONSTRAINT `#sql-426_49_ibfk_1` FOREIGN KEY (`review_id`) REFERENCES `review` (`review_id`))
+}
+
+function parseSqlErrors()
+{
+	local line
+	while read line; do
+		[[ $line == 'EOF' ]] && return
+		techo line=${(q)line}
+		if [[ $line =~ $'^ERROR ([0-9]{4}) \\(([0-9A-Z]{5})\\) at line ([0-9]+): (.*)' ]]; then
+			local rx msg errCode sqlState msgFormat
+			msg=$match[4]
+			errCode=$match[1]
+			sqlState=$match[2]
+			line=$match[3]
+
+			case $errCode in
+			1064)
+				msgFormat="near '(.*)'" ;;
+				# ".* error.* near '(.*)'" ;;
+				# "(Unknown) (column) '(\w+)' in '.+" ;;
+			*)
+				if msgFormat=${"$(perror $errCode)"##*: }; then
+					rx=(
+						'%(l#[du])'       '(-?[0-9]+)'
+						'%-#.#[0-9]#[sM]' '(.*)'
+					)
+					msgFormat=${msgFormat//${~rx[1]}/$rx[2]}
+					msgFormat=${msgFormat//${~rx[3]}/$rx[4]}
+				else
+					techo -Pr "Unknown error: %F{9}$errCode%f ($sqlState)"
+					continue
+				fi
+				;;
+			esac
+
+			if [[ $msg =~ $msgFormat ]]; then
+				techo -c lred -r "format: $msgFormat"
+				techo -c lred -r "match: ($match)"
+				print -Pr $errCode $sqlState $line ${(@qqq)match} - $msg
+			else
+				techo -c lred -r "Error message format doesn't match line"
+				techo -c lred -r $msgFormat
+				techo -c lred -r $msg
+				techo -c lred -Pr "Unknown error: %F{9}$errCode%f ($sqlState)"
+			fi
+		else
+			techo -Pr "%F{9}${line}%f"
+		fi
+	done
 }
 
 function isdb()
 {
-	[[ -n "$1" ]] && [[ -d "$DB_DATA_DIR/$1" ]]
+	[[ -n $1 ]] && [[ -d "$DB_DATA_DIR/$1" ]]
 }
 
 function usedb()
 {
+	#@TODO
 	#${${dbname:-$(proj get dbname)}}
 	[[ $1 == '-s' ]] && { db= ; shift }
 	if (($#)); then
 		isdb $1 && db=$1 || abort 127 "$1: database not found"
 	elif [[ -z $db ]]; then
-		db=$(chooser ${DBNAME:+-D $DBNAME} $(dblist))
+		db=$(chooser ${DBNAME:+-D$DBNAME} $(dblist))
 	fi
 }
+
 function dblist()
 {
 	sql -n 'show databases' | tail -n +2
@@ -79,6 +154,7 @@ function istable()
 	[[ -n $db ]] || return 
 	sql "describe $1" >/dev/null 2>&1
 }
+
 function tablelist()
 {
 	sql 'show tables' | tail -n +2
@@ -86,22 +162,26 @@ function tablelist()
 
 function gettable()
 {
-	istable $1 && echo $1 && return
-	echo $(zsh-select "$1" $(tablelist))
+	local S
+	if [[ -n $1 ]]; then
+		istable $1 && { echo $1; return }
+		S=(-S $1)
+	fi
+	chooser $S $(tablelist)
 }
 
 function tableshow()
 {
 	local tblname args t result
-	if [[ "$1" == "-d" ]]; then
-		usedb $2
+	if [[ $1 == '-d' ]]; then
+		usedb $2 || return
 		shift 2
 	else
-		usedb
+		usedb || return
 	fi
-	[[ "$1" == '-t' ]] && { shift; t=1 }
-	tblname=$(gettable $1)
-	if [[ -n "$t" ]]; then
+	[[ $1 == '-t' ]] && { shift; t=1 }
+	tblname=$(gettable $1) || return
+	if ((t)); then
 		sql "describe $tblname"
 	else
 		echo $(tail -n +2 <(sql "show create table $tblname") | cut -f2-)
@@ -112,7 +192,7 @@ function tableshow()
 # usage: dbsize mydatabase
 function dbsize()
 {
-	usedb "$@"
+	usedb "$@" || return
 	sql -n 'SELECT table_name AS "Table Name", ROUND(((data_length + index_length) / 1024 / 1024), 2) AS "Size in (MB)" FROM information_schema.TABLES WHERE table_schema = "'$db'" ORDER BY (data_length + index_length)'
 }
 
@@ -120,7 +200,7 @@ function dbsize()
 function sqldbdump()
 {
 	usedb "$@"
-	if [[ -f "$db.sql.bkup" ]]; then
+	if [[ -f $db.sql.bkup ]]; then
 		techo -c warn "Saving backup $db.sql.bkup"
 		mv $db.sql $db.sql.bkup
 	fi
