save all

diff --git a/zsh_libs/zsh_android b/zsh_libs/zsh_android
--- a/zsh_libs/zsh_android
+++ b/zsh_libs/zsh_android
@@ -1,6 +1,7 @@
 VERSION=1.0.1
 #lazyload:getpkg,isAndroidSDK,getPkg,vscode,androidenv,checkdbs
 
+phonebrand='2717' # phonebrand
 integer ret
 local dir dirs location
 
@@ -20,15 +21,20 @@ function isAndroidSDK()
 
 if ! isAndroidSDK $ANDROID_SDK_ROOT; then
 	ANDROID_SDK_ROOT=
-	dirs=$(run -v6 find $HOME -type d -iname android\* -and -not -iname androidSDK)
+	dirs=($(run -v6 find $HOME -maxdepth 2 -type d -iname android\* -and -not -iname androidSDK))
 	for dir in $dirs; do
 		if isAndroidSDK $dir; then
 			ANDROID_SDK_ROOT=$dir
+			break
+		elif isAndroidSDK $dir/Sdk; then
+			ANDROID_SDK_ROOT=$dir/Sdk
 			break
 		fi
 	done
 
 	[[ -z $ANDROID_SDK_ROOT && ! -o interactive ]] && abort 127 'Android SDK not found'
+	#TODO check is link or not if == ~/androidSDK
+	#[[ -L $ANDROID_SDK_ROOT
 fi
 
 while ! isAndroidSDK $ANDROID_SDK_ROOT; do
@@ -40,11 +46,7 @@ while ! isAndroidSDK $ANDROID_SDK_ROOT; do
 	fi
 
 	[[ -o interactive ]] || abort 127 'Android SDK not found'
-	chooser -v ANDROID_SDK_ROOT --dir; ret=$?
-	if ((ret)) ; then
-		((ret==130)) && cancel
-		((ret>=127)) && abort
-	fi
+	chooser -v ANDROID_SDK_ROOT --dir || abort $? 'Android SDK not found'
 done
 
 if [[ ! -d $location ]]; then
@@ -60,48 +62,36 @@ path+=($ANDROID_HOME/emulator $ANDROID_HOME/tools $ANDROID_HOME/tools/bin $ANDRO
 techo -c head ANDROID_HOME$C_="$C[warn]'$ANDROID_HOME'$C_"
 
 () {
-return
-	local udevScript="$HOME/bin/udevrun.sh" rulesFile='/etc/udev/rules.d/70-myudev.rules'
-	local rule needsReloading androidRulesFile='/lib/udev/rules.d/51-android.rules'
-	rule="ENV{adb_user}==\"yes\", RUN==\"/bin/su $USER --command='$udevScript'\""
-	#set -x
-	[[ -f  $androidRulesFile ]] || {
+# TODO: get from lsusb
+	local udevScript="$HOME/bin/udevrun.sh"
+	local rulesFile='/etc/udev/rules.d/70-myudev.rules'
+	local androidRulesFile='/lib/udev/rules.d/51-android.rules'
+	local needsReloading hasBrandRule rules=()
+
+	if [[ ! -f  $androidRulesFile ]]; then
 		local pkg='android-sdk-platform-tools-common'
 		run apt install $pkg && needsReloading=1 || {
 			(($CAUGHT==127)) && { # pkg does not exist
 				techo -c warn "Maybe $pkg does not exist anymore. The file looked for was $androidRulesFile"
 			}
 		}
-	}
-	integer opt
-	if [[ ! -f $rulesFile ]]; then
-		opt=1
-	elif [[ "$(cat $rulesFile)" != "$rule" ]]; then
-		local key
-		techo -c warn "File $rulesFile exists but is different from maintainer version."
-		diff -u $rulesFile <(cat <<<$rule)
-		set -x
-		if chooser -v key -b1 --use-keys 'M' 'Maintainer version' 'K' 'Keep current' 'E' 'Edit'; then
-			echo chosen=$key
-			case $key in
-				M) opt=1 ;;
-				E)
-					gvimdiff -f $rulesFile <(echo '# Maintainer file';cat <<<$rule)
-					;;
-				*) ;;
-			esac
-		fi
 	fi
 
-	if ((opt==1)); then
-		echo -E $rule | sudo tee $rulesFile && needsReloading=1 || {
+	grep -q "ATTR{idVendor}==\"$phonebrand\"" $rulesFile(N) $androidRulesFile(N) || {
+		rules+=('SUBSYSTEM=="usb", ATTR{idVendor}=="'$phonebrand'", MODE="0666", GROUP="plugdev"')
+	}
+
+	if [[ ! -f $rulesFile ]] || (($#rules)); then
+		rules+=("ENV{adb_user}==\"yes\", RUN==\"/bin/su $USER --command='$udevScript'\"")
+		print -rl $rules | sudo tee $rulesFile && needsReloading=1 || {
 			techo "Error writing udev rules to $rulesFile"
 		}
 	fi
 
+	set +x
 	((needsReloading)) && {
 		techo "New android udev rules was just installed. Reloading udev..."
-		sudo udevadm control --reload
+		sudo udevadm control --reload-rules
 		#@TODO: check
 	}
 	set +x
@@ -122,11 +112,6 @@ function getPkg()
 {
     #chkCmdInst aapt
     aapt dump badging $1 | grep 'package: name' | cut -f2 -d"'"
-}
-
-function vscode()
-{
-	code &
 }
 
 function androidenv()
diff --git a/zsh_libs/zsh_device b/zsh_libs/zsh_device
--- a/zsh_libs/zsh_device
+++ b/zsh_libs/zsh_device
@@ -516,17 +516,22 @@ function imageof()
 #comp+=(image='')
 function imageMount()
 {
-	local img dir var dev
-	if [[ $# -ne 2 ]]; then
-		echo Usage: $0 imageFile mountDir
+	local img dir var dev _opt
+	(($#)) && { img=$1 ; dir=$2 }
+	(($#img)) && [[ -f $img ]] || {
+		#while [[ ! -f $img ]]; do
+			#chooser -v _opt --file --head 'Choose an image' $(f \*.iso)
+		#done
+		techo -c warn "Usage: $0 imageFile mountDir"
 		return 1
-	fi
-	img=$1 ; dir=$2
-	if [[ ! -f $1 ]]; then
-		techo -c lred "$1: file not found"
-		return 1
-	fi
-	isDir -m $dir || return 1
+	}
+	[[ -f $img ]] || { abort 2 "$img: file not found" }
+	[[ -n $dir ]] && isEmptyDir $dir || {
+		[[ -n $dir ]] && techo -c warn "$dir is not empty"
+		label="$(dd if=$img bs=1 skip=32808 count=32)"
+		isDir -m /m/$label
+		input -p "Mounting point directory" -v dir "/m/$label"
+	}
 	if dev=$(isDirMounted $dir); then
 		if var=$(isLoop $dev); then
 			var=$(imageof $var)
diff --git a/zsh_libs/zsh_sql b/zsh_libs/zsh_sql
--- a/zsh_libs/zsh_sql
+++ b/zsh_libs/zsh_sql
@@ -1,4 +1,4 @@
-VERSION=1.0.5
+VERSION=1.0.6
 #lazyload=sql,gettable,tableshow,tablelist,sqlError,usedb,dblist,dbtstamp,dbsize,sqldbdump,sqlEscape
 alias sql="noglob sql"
 alias sqlmaq="noglob sql --ssh idiomus"
@@ -122,6 +122,7 @@ function sql()
 		ret=$?
 
 	else #### Local ####
+		(($+_opts[--nocolumns] && $+_opts[-o])) && abort 2 "--nocolumns and -o options can't be used together"
 		mysqlopts=()
 		(($+_opts[-n])) || usedb $name[2]
 
@@ -189,7 +190,13 @@ function sql()
 			#@TODO: no error handling: redirect stderr to null
 			if (($#file)); then
 				if [[ -f $file ]]; then
-					(($#verbose)) && techo -r -c head mysql ${(qq)mysqlopts} $db '<' $file
+					if ((!$#presql)); then
+						confirm 'Turn off foreign key verification' && {
+							presql='SET GLOBAL FOREIGN_KEY_CHECKS=0;'
+							postsql='SET GLOBAL FOREIGN_KEY_CHECKS=0;'
+						}
+					fi
+					(($#verbose)) && techo -r -c head "mysql ${(qq)mysqlopts} $db < $file"
 					if ((p)); then mysql $mysqlopts $db < $file 2>&p
 					else mysql $mysqlopts $db < $file; fi
 					techo ret=$?
@@ -260,9 +267,11 @@ function sql()
 	}
 }
 
+# $1 is var name, which is array with row values
 function sqlFetch()
 {
 	integer N
+	# starts at 0
 	(($+rowIndex[$1])) || return 1
 
 	((N=++rowIndex[$1]))
@@ -465,7 +474,15 @@ function istable()
 
 function tablelist()
 {
-	sql 'show tables' | tail -n +2
+	#(($#)) && isdb $1 && { shift }
+	usedb $1 || return
+	sql --nocolumns 'show tables'
+}
+
+function viewlist()
+{
+	usedb $1 || return
+	sql "SHOW FULL TABLES IN $db WHERE TABLE_TYPE LIKE 'VIEW'"
 }
 
 function gettable()
@@ -550,4 +567,33 @@ function sqldbstat()
 	pass=$sqlPass[$user]
 	opts+=(-u$user -p"$pass" --count)
 	mysqlshow $opts $db
+}
+
+alias groupby='sqlgroupby'
+# Added 2020-11-10 20:41
+function sqlgroupby()
+{
+	local _opts groups
+	#zparseopts -D -M -A _opts -
+	tbl=$(gettable $1)
+	tbl=$1; shift
+	_opts=("$@")
+	explode -v cols "$(sql -t show columns from $tbl)" $'\n'
+	array_dump cols
+	dbg chooser --ifs '¬' --multi -s '|' -f 2 -v groups --head "         $cols[2]" ${(j.¬.)cols:4:-1}
+	e groups=$groups
+	sql $_opts "SELECT count(*), ${(j.,.)groups} FROM $tbl"   # ORDER BY ${(j.,.)groups}"
+}
+
+# Added 2020-12-06 12:55
+function sqlgrant()
+{
+	local _gdb _guser _gpass
+	zparseopts -D -M -A _opts - p: u: d:
+
+	(($+_opts[-d])) && $_gdb=$_opts[-d]
+	(($+_opts[-p])) && $_gpass=$_opts[-p]
+	(($+_opts[-u])) && $_guser=$_opts[-u]
+
+	sql -n "GRANT ALL ON $_gdb.* TO '$_guser'@'localhost' IDENTIFIED BY '$_gpass' WITH GRANT OPTION; FLUSH PRIVILEGES;"
 }
