Lots of old and new changes

diff --git a/zsh_libs/zsh_aliases b/zsh_libs/zsh_aliases
--- a/zsh_libs/zsh_aliases
+++ b/zsh_libs/zsh_aliases
@@ -1,5 +1,5 @@
 VERSION=1.0.5
-typeset -g -a comp
+[[ -v comp ]] || typeset -g -a comp
 alias e=echo
 alias op="xdg-open"
 alias open="xdg-open"
@@ -14,6 +14,9 @@ alias mk="make"
 alias apt="sudo apt"
 alias diff_ignore_space="diff --ignore-space-change --ignore-tab-expansion --ignore-trailing-space --ignore-blank-lines"
 alias sys="sudo systemctl"
+#alias jtags="ctags -R . && sed -i -E '/^(if|switch|function|module\.exports|it|describe).+language:js$/d' tags"
+alias jtags='find . -type f -iregex ".*\.js$" -not -path "./node_modules/*" -exec jsctags {} -f \; | sed '"'"'/^$/d'"'"' | LANG=C sort > tags2'
+
 
 function hg()
 {
@@ -25,123 +28,72 @@ function hg()
 	fc -li ${=fopt} | grep ${=gopt}
 }
 
-comp+=("inst=apt")
-function inst()
-{
-	local machine pkgs
-	zparseopts -D -E -M - m:=machine
-	if [[ -z "$machine" ]]; then
-		if [[ ${#@} -ge 1 ]]; then
-			pkgs=("${@}")
-		else
-			pkgs=${$(fc -ln -1)[1]}
-		fi
-		sudo apt-get install ${pkgs[@]}
-	else
-		echo "$@" >> "$CFG/${machine[2]}.pkgs.txt"
-	fi
-}
-comp+=("aptinst=apt")
-function aptinst()
-{
-	sudo apt-get install -y $@
-}
-
 # Added 2019-04-12 11:45
 function aptlist()
 {
 	zgrep 'install ' /var/log/dpkg.log* | sort | cut -f1,2,4,6 -d' ' | less
 }
 
-function typeOf()
-{
-	local name ret fpath
-	name="$1"
-	if [[ ! -f "$name" ]]; then
-		ret=($(which -w $name))
-		type="${ret[2]}"
-		if [[ "$type" != "none" ]]; then
-			if [[ "$type" == "command" ]]; then
-				fpath=$(which $name)
-				if isScript $fpath; then
-					type="script"
-				fi
-			fi
-			echo $type $fpath
-			return 0
-		fi
-		echo "none"
-		return 1
-	fi
-	
-	fpath=$name
-	
-	if isScript $fpath; then
-		type="script"
-	elif [[ -x "$fpath" ]]; then
-		type="command"
-	else
-		echo "none"
-		return 1
-	fi
-	
-	echo $type $fpath
-	return 0
-}
-
-function zindent()
-{
-	echo -n "$@" | sed -E 's/^([^{}])/\t\1/g'
-}
-
 function mkscript()
 {
-	local shell func name data edit err_exists file isLib
+	local shell func name data data2 edit err_exists file isLib help
 	err_exists="exists but isn't a shell script."
-	zparseopts -D -K s:=shell f:=func n:=name e=edit
-
-    if [ $# -lt 1 ]; then
-        echo s:=shell f:=func n:=name e=edit
-        return
-    fi
-	if [[ -n "$func" ]]; then
+	zparseopts -D -K s:=shell f:=func n:=name e=edit || abort
+	
+	data2="$@"
+	if [[ -n "$func[2]" ]]; then
 		func=$func[2]
-		#@TODO function already exists? (c)ancel, (a)ppend, overwrite
+		if [[ "$(typeOf $func)" == 'func' ]]; then
+			techo -c warn "$func() already exists"
+			vw $func
+			return
+		fi
+		#@TODO function already exists? (c)ancel, (e)dit, (o)verwrite
 	fi
+	input -p "Function name" -v func
 	isLib=false
 	if [[ -n "$name" ]]; then
 		name=$name[2]
 		file=$(getpath $name)
         if [[ "$file" != "." ]]; then # full path given
-			if [[ -f "$file" ]] && ! isScript $file; then
-				echo "$file $err_exists"
+			if [[ -d "$name" ]]; then
+				echo "$name is a directory"
+				return 1
+			elif [[ -f "$name" ]] && ! isScript $name; then
+				echo "$name $err_exists"
 				return 1
 			fi
+			file=$name
 		else
 			cmdtype=($(typeOf $name))
 			type=${cmdtype[1]}
 			file=${cmdtype[2]}
-			if [[ "$type" != "none" ]]; then
-				if [[ "$type" != "script" ]]; then
-					if [[ -f "$ZSH_LIBS/zsh_$name" ]]; then # is it a lib?
-						file="$ZSH_LIBS/zsh_$name"
-						isLib=true
-					else
-						echo "$file $err_exists"
-						return 1
-					fi
-				fi
-				#@TODO zconfirm "append to $xpath ?"
-			else
+			if [[ "$type" != "script" ]]; then
 				if [[ -f "$ZSH_LIBS/zsh_$name" ]]; then # is it a lib?
 					file="$ZSH_LIBS/zsh_$name"
 					isLib=true
+				elif [[ "$type" != 'none' ]]; then
+					echo "$file $err_exists"
+					return 1
 				fi
 			fi
 		fi
 	else
-		file="$ZSH_LIBS/zsh_aliases"
 		isLib=true
+		#file="$(chooser $ZSH_LIBS/zsh_* "New zsh library" "Browse full path")"
+		file="New zsh library"
+		if [[ "$file" == "New zsh library" ]]; then
+			file=$(input -p "Enter new library name") || cancel
+			if [[ $file == */* ]]; then
+				file=$(getpath $file)
+				name=$(getfilename $file)
+				name=zsh_${name#zsh_*}
+			else
+				file=$ZSH_LIBS/zsh_${file#zsh_*}
+			fi
+		elif [[ "$file" == "Browse full path" ]]; then
+			file=$(chooser -p "Choose path of zsh library" --dir) || cancel
+		fi
 	fi
 
 	if [[ ! -f "$file" ]]; then
@@ -153,9 +105,9 @@ function mkscript()
 	# TODO: append to function in case of existing function
 	data+="\n# Added "$(date "+%F %R")"\n"
     if [[ -n "$func" ]]; then
-		data+=$(zindent "function ${func}()\n{\n$@\n}")
+		data+=$(zindent "function ${func}()\n{\n$data2\n}")
 	else
-		data+=$(zindent "$@")
+		data+=$(zindent "$data2")
 	fi
 
 	echo ${data}$'\n' >> $file
@@ -165,8 +117,8 @@ function mkscript()
 	[[ -x "$file" || $isLib ]] || chmod +x $file
 
 	# edit
-	if [[ -n "$edit" ]]; then
-		[[ -n "$func" ]] && edfunc $func || gvim -f $file
+	if [[ -n "$edit" || -z "$data2" ]] || confirm "Edit file"; then
+		[[ -n "$func" ]] && $isLib && edfunc $func || gvim -f $file
 	fi
 }
 #function _stack()
@@ -200,50 +152,98 @@ function add_key()
 }
 function edalias()
 {
-	local lin n aliasf=${3:-~/.zsh_aliases}
-    set -x
-	if [[ -n "$1" ]]; then
-		n=${2:-0}
-		lin=$(( `egrep -n "^$1" $aliasf | cut -d: -f1` + $n ))
-		[ $? -ne 0 ] && lin=1
+	local line pat file var is
+	zparseopts -D -M l:=line
+	[[ -n "$1" ]] || return 1
+	if [[ "$1" == '-f' ]]; then
+		shift
+		pat="(function )?$1\(\)"
+		line=${line[2]:-2}
+	else
+		pat="alias $1="
+		line=0
 	fi
-    set +x
-	gvim -f $aliasf +$lin
-	echo "Sourcing $aliasf"
-	source $aliasf
+	file=${2:-~/.zsh_aliases}
+	var="$(egrep -n "^[[:space:]]*$pat" "$file")" || var="2:$file"
+	if [[ $? -eq 0 ]]; then
+		((line+=$(explode "$var" ':' 1)))
+		gvim -f $file +$line
+		echo "PPID=$PPID"
+		include $file
+	else
+		techo -c err "Could not find \"$1\""
+	fi
 }
 
 function edfunc()
 {
-	local arg
-	arg=($(type $1))
-	[[ $? -ne 0 ]] && { echo $arg; return 1; }
-	[[ "${arg[5]}" != "function" ]] && { echo "$1 is not a function:\n\t$arg"; return 2; }
-	edalias "function $1\(\)" 2 ${arg[-1]}
+	local arg file
+	arg=($(type "$1"))
+	[[ $? -ne 0 ]] && return 1
+	if [[ "${arg[4]}" == 'autoload' ]]; then
+		techo "autoload function todo: find not loaded autoload functions in fpath"
+		file="${arg[-1]}"
+		[[ -f "$file" ]] || {
+			typeset -a files=($(f -b "${j.,.)fpath}" "$1"))
+			file=$(chooser -p "Choose file" $files) || cancel
+		}
+	elif [[ "${arg[5]}" != 'function' ]]; then
+		abort 2 "$1 is not a function:\n\t$arg"
+	else
+		file="${arg[-1]}"
+	fi
+	edalias ${2:+-l $2} -f "$1" "$file" 
 }
 comp+=("vw=exec")
 function vw()
 {
-	local ret buffer mime fpath
-	fpath="$*"
-	ret=`which $fpath`
-	if [ -f "$ret" ]; then
-		mime=$(getmime $fpath)
-		[[ "$mime" == "application/x-sharedlib" ]] && { echo "$fpath is binary executable" ; return 1; }
-		gvim $ret
-	else
-		ret=`which -w $@`
-		buffer=(${=ret})
-		case "${buffer[2]}" in
-			function)
-				edfunc $1
-				;;
-			alias)
-				edalias "alias $1=" 0
-				;;
-		esac
-	fi
+	local array mime cpath name line
+	array=($(explode "$1" ':')) ; name=$array[1]; line=$array[2]
+	array=($(type -w "$name"))
+	case "${array[2]}" in
+		function) edfunc $name $line
+			;;
+		alias) edalias $name $line
+			;;
+		command)
+			cpath=$(which "$name")
+			if [[ -f "$cpath" ]]; then
+				mime=$(getmime $cpath)
+				if [[ "$mime" == "application/x-sharedlib" ]]; then
+					echo "$tpath is binary executable"
+					return 1
+				fi
+				gvim $cpath ${line:++$line}
+			else
+				echo Invalid path \"$cpath\"
+			fi
+			;;
+	esac
 }
+# call vim to each file:line argument
+# file1:l4 file2:l66 
+function v()
+{
+	local opt sudo
+	if [ "${1:0:1}" = "-" ]; then
+		if [[ $1 = -s ]]; then
+			sudo='sudo'
+		else
+			opt=$1
+		fi
+		shift
+	fi
+	for arg; do
+		if [[ "$arg" =~ ":" ]]; then
+			line=+$(echo $arg | cut -d: -f2)
+			file=$(echo $arg | cut -d: -f1)
+			$sudo gvim $opt $line $file
+		else
+			$sudo gvim $opt $arg
+		fi
+	done
+}
+
 function finderror()
 {
 	errline=`tail /var/log/apache2/error.log |  grep -e "PHP \(Parse\|Fatal\|Notice\)" | tail -n1`
@@ -281,40 +281,41 @@ function vimcmd()
 }
 function forvim()
 {
+	local _v _cmd
 	if [ "$1" = "cmd" ]; then
-		cmd="--remote-send"
+		_cmd="--remote-send"
 		shift
 	else
-		cmd="--remote-expr"
+		_cmd="--remote-expr"
 	fi
-	for v in `vim --serverlist`; do
-		vim --servername $v $cmd $@
+	for _v in `vim --serverlist`; do
+		vim --servername $_v $_cmd $@
 	done
 }
 function f()
 {
-	local d i s p g dir
-	zparseopts -D - d:=d i=i s=s p=p g:=g
-	#if [ "${1:0:2}" = "-d" ]; then
-	#	d=${1:2}
-	#echo "d[]=>$d[1] $d[2] $d[3]"
+	local d i s p g base args name n=1
+	zparseopts -D - d:=d i=i s=s p=p g:=g b:=base
 	[[ -n $s ]] && s="sudo"
 	[[ -n $d ]] && d[1]='-maxdepth'
-	[[ -n $i ]] && name="-iname" || name="-name"
-	dir=()
-	while [[ -d $1 ]]; do
-		dir+=($1)
-		shift
-	done
-	if [[ -z $dir ]]; then
-		dir+=(.)
-	fi
+	[[ -n "$base" ]] && explode -v base "$base[2]" ',' || base=(.)
 	#[[ $1 = - ]] && shift
 	#$s find ${=d} \( -path ./bckup_extensions -or -path ./extensions \) -prune -or $name $@ -print
-	
+	local found arg
+	until (( found )) || [[ -z ${arg::=${@:$n:1}} ]]; do
+		[[ $arg[1] == '-' ]] && ((found=n))
+		((n++))
+	done
+
+	if ((found==0 || found>1)); then
+		((found==0)) && args=("$@") || args=(${@:1:$found-1})
+		[[ -n $i ]] && name="-iname" || name="-name"
+		name=($name' '${^args})
+		shift $#args
+	fi
 	[[ -n $g ]] && {
-		$s find $dir ${=d} $name $@ $p | group $g
-	} || $s find $dir ${=d} $name $@ $p
+		$s find -L $base ${=d} ${=name} $@ $p | group $g
+	} || $s find -L $base ${=d} ${=name} $@ $p
 }
 function aldd() {
 	local R=$USER_HOME/clp
@@ -349,8 +350,8 @@ function sge()
 }
 function ge()
 {
-	local sudo icase args in_exts ex_exts
-	zparseopts -D -E - i=icase s=sudo --exclude:=ex_exts
+	local sudo icase args in_exts ex_exts width
+	zparseopts -D -E - i=icase s=sudo --exclude:=ex_exts w::=width
 	[[ -n $icase ]] && args+=('-i')
 	[[ -n $sudo ]] && sudo=sudo
 	IFS=',;:' read -rA in_exts <<<"$1"
@@ -358,37 +359,23 @@ function ge()
 	#	exc=("--exclude-dir=extensions" "--exclude-dir=bckup_extensions")
 	[ "$#ex_exts" -gt 0 ] && args+=('--exclude=*.'${^ex_exts[@]})
 	args+=('--include=*.'${^in_exts[@]})
-	$sudo grep --color -rn $args $@
+	if (( $#width )); then
+		[[ $width = -w[0-9]## ]] && width=${width[1]:2} || width=0
+		if [[ $width -eq 0 ]]; then
+			$sudo grep --color -rn $args $@
+			return
+		fi
+	else
+		#width=$(( $(tput cols) - 50 ))
+		width=300
+	fi
+	$sudo grep --color -rn $args $@ | cut -c1-$width
 }
 function duh()
 {
 	local sudo
 	[[ "$1" == '-s' ]] && { shift; sudo='sudo'; }
 	$sudo du -csh "$@" | sort -h
-}
-
-# call vim to each file:line argument
-# file1:l4 file2:l66 
-function v()
-{
-	local opt sudo
-	if [ "${1:0:1}" = "-" ]; then
-		if [[ $1 = -s ]]; then
-			sudo='sudo'
-		else
-			opt=$1
-		fi
-		shift
-	fi
-	for arg; do
-		if [[ "$arg" =~ ":" ]]; then
-			line=+$(echo $arg | cut -d: -f2)
-			file=$(echo $arg | cut -d: -f1)
-			$sudo gvim $opt $line $file
-		else
-			$sudo gvim $opt $arg
-		fi
-	done
 }
 
 # Added 2019-01-10 11:26:22
@@ -486,7 +473,7 @@ function compress_cpio_image()
 	imgName=u${(C)$(getfilenoext $targetImg)}
 	compalg=${3:-mzip}
 	if [[ -n $ignore ]]; then
-		ignore=($(explode $ignore[2]))
+		explode -v ignore $ignore[2] ':'
 		ignore=('-path ./'${^ignore})
 		ignore="( ${(j. -o .)ignore} ) -prune -o -print"
 	fi
@@ -514,27 +501,10 @@ function shpydf()
 # create progress bar
 function pbar()
 {
-	type setup_scroll_area >/dev/null || source $HOME/bin/progress_bar.sh || return 1
-	if [[ "$1" == "start" ]]; then  # setup
-		setup_scroll_area $2
-		enable_trapping		# optional to clean up properly if user presses ctrl-c
-	elif [[ "$1" == "set" ]]; then # advance progress bar
-		draw_progress_bar $2
-	elif [[ "$1" == "block" ]]; then # turns the progress bar yellow to
-		block_progress_bar $2        # indicate some action is requested from the user
-	elif [[ "$1" == "end" ]]; then # finish
-		destroy_scroll_area 
-	else
-		return 1
-	fi
+	include -r progress_bar || return 1
+	pbar "$@"
 }
 
-# Added 2019-02-20 09:23:39 @TODO
-function boxStart()
-{
-    include boxes
-    box start
-}
 # Added 2019-02-20 15:38:03
 function hidrivemount()
 {
@@ -587,35 +557,8 @@ function ipfind()
 	done
 }
 
-# Added 2019-04-04 15:20
-function procmon()
-{
-	local prog=$1 timeout=5
-	while true; do
-		pid=$(pidof $prog)
-		[[ -z "$pid" ]] && continue || e $pid
-		sleep $timeout
-		pid2=$(pidof $prog)
-		[[ -z "$pid2" ]] && continue || e $pid2
-		[[ $pid -eq $pid2 ]] && kill $pid
-		sleep 1
-	done
-}
-
 # Added 2019-04-11 01:43
 function logs()
 {
 	tail {.,$(git root)}/logs/{api,debug}.txt -f &
 }
-
-# Added 2019-06-07 17:27
-function fordo()
-{
-	e FIXME
-	local v
-	cmd=$1 ; shift
-	for v; do
-		run $cmd $v
-	done
-}
-
diff --git a/zsh_libs/zsh_device b/zsh_libs/zsh_device
--- a/zsh_libs/zsh_device
+++ b/zsh_libs/zsh_device
@@ -3,14 +3,11 @@ setopt extendedglob
 
 function findDev()
 {
-    local devin="$1"
-    if [[ ! -b "$devin" ]]; then
-        if [[ ! -f "$devin" ]]; then
-            devin="/dev/$devin"
-            [[ -b "$devin" ]] ||  { abort $? "Device not found: '$1'" ; return 1 }
-        fi
-    fi
-    echo "$devin"
+	local devin="$1"
+	if [[ ! -b "$devin" ]]; then
+		devin=$(isDevice $devin) && [[ -b "$devin" ]] || return 1
+	fi
+	echo "$devin"
 }
 
 #@bug: shows partition as not mounted while it was really mounted
@@ -61,8 +58,9 @@ function deviceMount()
 		elif isDir $dev; then
 			dev=$(awk -v needle="$var" '$2==needle {print $1}' /etc/fstab 2>/dev/null)
 			if [[ -n $dev ]]; then
-				[[ -b $dev ]] || dev=$(blkid --uuid $dev) || return 1
-				sudo udisksctl mount -b $dev
+				[[ -b $dev ]] || dev=$(blkid --uuid $(explode $dev '=' 2)) || return 1
+				tmp=$(run udisksctl mount -b $dev 2>&1)
+				[[ $? -ne 0 && "$tmp" != *already\ mounted* ]] && ((err++))
 			else
 				mnt=$var
 			fi
@@ -90,7 +88,8 @@ function deviceMount()
 			deviceUnmount $var || abortDevError MNTBUSY "$mnt ($var)"
 		}
 		run -s -p "mount $dev" mount $dev $mnt
-	else
+
+	elif [[ $#devs -ge 1 ]]; then
 		local parts line TYPE NAME SIZE FSTYPE LABEL MOUNTPOINT pids
 		parts=("${(f)$(deviceInfo -t part --short $devs)}")
 		for line in $parts; do
@@ -106,10 +105,9 @@ function deviceMount()
 				((err++))
 				continue
 			fi
-			deviceMount $NAME "$baseMnt/$LABEL"
+			deviceMount $NAME "$baseMnt/$LABEL" || ((err++))
 		done
-		((err+=$?))
-		[[ $err -eq 0 ]] && techo $OK || techo -c warn $err errors
+		((err==0)) && techo $OK || techo -c warn $err errors
 		return $err
 	fi
 }
@@ -255,7 +253,7 @@ function deviceInfo()
 		s=short -short=s t:=type -type:=t o:=columns u=mounted
 
 	if [[ -n $columns ]]; then
-		columns=(TYPE $(explode $columns[2] ','))
+		explode -u -v columns "TYPE,$columns[2]" ','
 	else
 		columns=(TYPE NAME SIZE FSTYPE LABEL MOUNTPOINT)
 		if [[ -z "$short" ]]; then
@@ -431,7 +429,7 @@ function mntof()
 {
 	local dev loop
 	dev=$(isDevice $1) || dev=$(loopof $dev) || return
-    awk -v needle="$dev" '$1==needle {print $2}' /proc/mounts 2>/dev/null
+	awk -v needle="$dev" '$1==needle {print $2}' /proc/mounts 2>/dev/null
 }
 function isDeviceMounted()
 {
@@ -535,7 +533,7 @@ function loop()
 # Added 2019-03-01 15:48
 function unloop()
 {
-    local loopNum devLoop devList img
+	local loopNum devLoop devList img
 	zparseopts -D -E -M -- i:=img -img:=i
 	if devLoop=$(isLoop $1) && [[ -z $img ]]; then
 		loopNum=${devLoop#/dev/loop}
@@ -547,8 +545,8 @@ function unloop()
 		[[ "$devLoop" =~ "loop([0-9]*)" ]] || return 1
 		loopNum=$match[1]
 	fi
-    devList=(${devLoop} /dev/mapper/loop${loopNum}p*(N) ${devLoop}p*(N))
-    run deviceUnmount $devList || return
+	devList=(${devLoop} /dev/mapper/loop${loopNum}p*(N) ${devLoop}p*(N))
+	run deviceUnmount $devList || return
 	sudo kpartx -d $devLoop
 	[[ -b $devLoop ]] && sudo losetup -d $devLoop
 	return 0
@@ -557,58 +555,67 @@ function unloop()
 # Added 2019-02-26 14:17
 function ptablecp()
 {
-    local tblbkp src dest
-    src=$1
-    dest=$2
-    shift 2
-    [[ -n $src && -n $dest ]] || { echo "need at least 2 arguments" ; return 1 }
-    #tblbkp="$(getfilename $dest).bkup"
-   # sudo sfdisk -d $dest | tee $dest.ptbl
-    sudo sfdisk -d $src | sudo sfdisk $dest
+	local tblbkp src dest
+	src=$1
+	dest=$2
+	shift 2
+	[[ -n $src && -n $dest ]] || { echo "need at least 2 arguments" ; return 1 }
+	#tblbkp="$(getfilename $dest).bkup"
+	# sudo sfdisk -d $dest | tee $dest.ptbl
+	sudo sfdisk -d $src | sudo sfdisk $dest
 }
 
 # Added 2019-02-14 09:24
 # Updated 2019-02-25 14:47
 function sdd()
 {
-    local devin devout bs quiet status ioffset ooffset offset args dryrun
-    zparseopts -M -D - -dry=dryrun q=quiet -quiet=q -bs:=bs \
-        -ioffset:=ioffset -ooffset:=ooffset -offset:=offset
-    [[ $# -ge 2 ]] || return 1
-	include file
-    devin=$1
-    devout=$2
-    if [[ ${devin:0:2} == 'f:' ]]; then
-        devin=${devin:2}
-    else
-        devin=$(findDev $devin)
-    fi
-    if [[ ${devout:0:2} == 'f:' ]]; then
-        devout=${devout:2}
-    else
-        devout=$(findDev $devout)
-    fi
+	local devin devout bs quiet status ioffset ooffset offset args dryrun
+	zparseopts -M -D - -dry=dryrun q=quiet -quiet=q -bs:=bs \
+		-ioffset:=ioffset -ooffset:=ooffset -offset:=offset
+
+	[[ $# -ge 2 ]] || return 1
+
+	include -r file || abort 1 
+	devin=$1
+	devout=$2
+	if [[ ${devin:0:2} == 'f:' ]]; then
+		devin=${devin:2}
+		[[ -f $devin ]] || abort 127 "$devin: file not found"
+	elif [[ ! -f $devin ]]; then
+		devin=$(findDev $devin) || abort 127 "$devin: device not found"
+	fi
+
+	if [[ ${devout:0:2} == 'f:' ]]; then
+		devout=${devout:2}
+	elif devout=$(isDevice $devout); then
+		[[ -b $devout ]] || abort 127 "$devout: device not found"
+	fi
+
+	if [[ -f $devout ]]; then
+		confirm "Output file $C[warn]\"$devout\"$_C exists.\n$C[warn]Overwrite" || cancel
+	fi
+	
 	shift 2
 
-    args=("$@")
-    if [[ -n $offset ]]; then
-        args+=("skip=$offset[2]")
-        args+=("seek=$offset[2]")
-    else
-        [[ -n $ioffset ]] && args+=("skip=$ioffset[2]")
-        [[ -n $ooffset ]] && args+=("seek=$ooffset[2]")
-    fi
+	args=("$@")
+	if [[ -n $offset ]]; then
+		args+=("skip=$offset[2]")
+		args+=("seek=$offset[2]")
+	else
+		[[ -n $ioffset ]] && args+=("skip=$ioffset[2]")
+		[[ -n $ooffset ]] && args+=("seek=$ooffset[2]")
+	fi
 
-    echo "${C[b]}in=$devin => out=$devout$C_"
+	techo "${C[b]}in=$devin => out=$devout$C_"
 	#@TODO techo watch -n5 'killall -USR1 dd'
-    ##oflag=dsync 
-    if [[ -z $quiet ]]; then
-        args+=('status=progress')
-    fi
-    args+=('conv=notrunc,fdatasync')
+	##oflag=dsync 
+	if [[ -z $quiet ]]; then
+		args+=('status=progress')
+	fi
+	args+=('conv=notrunc,fdatasync')
 	bs=${bs[2]:-64M}
-	sudo dd "if=$devin" "of=$devout" "bs=$bs" "${args[@]}"
-    _sync
+	run $quiet -s dd "if=$devin" "of=$devout" "bs=$bs" "${args[@]}"
+	_sync
 }
 
 # Added 2019-06-03 09:00
diff --git a/zsh_libs/zsh_functions b/zsh_libs/zsh_functions
--- a/zsh_libs/zsh_functions
+++ b/zsh_libs/zsh_functions
@@ -40,26 +40,32 @@ OK=" [${C[ok]}OK$C_]"
 
 function input()
 {
-	local var ret p gui z colors args tit
-	zparseopts -M -D - p:=p s:=set g=gui z=z t:=tit
-	colors=(-fg $C[head] -bg black)
-	p=${p[2]:-Edit text}
-	tit=${tit[2]:-Edit text}
-	var=${(P)set[2]:-"$@"}
-	techo -c head $p
+	local var str p gui z colors args title
+	zparseopts -M -D - p:=p v:=var g=gui z=z t:=title
+	colors=(-fg white -bg black)
+	p=${p[2]:-Input text}
+	title=${title[2]:-Input text}
+	if [[ -n "${var[2]}" ]]; then
+		var="${var[2]}"
+		[[ -v $var ]] || typeset -g $var
+	fi
+	str=${@:-${(P)var}}
+	techo -n -c head "$p: "
 	if [[ -n $z ]] && type zenity>/dev/null; then
-		var=$(zenity -title "$title" --entry --text="$p" --entry-text="$var") || return
+		str=$(zenity -title "$title" --entry --text="$p" --entry-text="$str") || cancel
+		techo -c warn $str
 	elif type gxmessage >/dev/null; then
 		args=($colors -center -ontop -wrap -buttons Cancel:1,Ok:0)
-		var=$(gxmessage $args -title "$title" -entrytext "$var" "$p") || return
+		str=$(gxmessage $args -title "$title" -entrytext "$str" "$p") || cancel
+		techo -c warn $str
 	else
-		vared var || read -r var || return
+		vared str || read -r str || cancel
 	fi
 
-	if [[ -n $set[2] ]]; then
-		${(P)set[2]::=$var}
+	if [[ -n $var ]]; then
+		${(P)var::=$str}
 	else
-		echo $var
+		echo $str
 	fi
 	return 0
 }
@@ -85,29 +91,50 @@ function confirm()
 	return $ret
 }
 
+# Receive a list and the default selected item.
+# Put the default item on the first position.
+# @param string selected
+# @param string[] list
+function mklist()
+{
+	local list first i
+	first=$1
+	list=($1)
+	shift
+	for i; do [[ "$i" != "$first" ]] && list+=($i) ; done
+	echo "${list[@]}"
+}
+
 function chooser()
 {
-	local noSelect chosen ret sep
-	zparseopts -M -D - c=color p:=print n:=noSelect R:=regex s:=sep
+	local noSelect chosen ret sep field search default
+	zparseopts -M -D - c=color p:=print n:=noSelect R:=regex s:=sep f:=field \
+		S:=search D:=default
 
-	#args=("${(@f)@}")
 	if [ $# -gt 1 ]; then
-		#if ! zmodload zsh/curses; then
-		#	return 1
-		#fi
-		chosen="$(ZSHSELECT_NONSELECTABLE="$noSelect[2]" ZSHSELECT_START_IN_SEARCH_MODE=0 zsh-select "$@")"
+		local args
+		chosen=$(
+			NLIST_SET_SEARCH_TO=$search[2]
+			ZSHSELECT_START_IN_SEARCH_MODE=$+search
+			ZSHSELECT_NONSELECTABLE=$noSelect[2]
+			zsh-select $default $@
+		)
+		#(($#search[2])) && args+=(NLIST_SET_SEARCH_TO=$search[2])
+		#(($#noSelect[2])) && args+=(ZSHSELECT_NONSELECTABLE=$noSelect[2])
+		#(($#search[2])) && args+=(NLIST_SET_SEARCH_TO=$search[2])
+		#chosen=$($args ZSHSELECT_START_IN_SEARCH_MODE=$+search zsh-select $@)
+		ret=$?
 	else
 		chosen="$1"
 	fi
-	ret=$?
-	[[ -z "$chosen" ]] && return 1
+	[[ $#chosen -gt 0 ]] || return $ret
 	if [[ -n $regex ]]; then
 		if [[ $chosen =~ $regex[2] ]]; then
 			echo "$match[@]"
 			return 0
 		fi
 	elif [[ -n $sep ]]; then
-		echo $(explode "$chosen" $sep)
+		echo $(explode "$chosen" $sep[2] $field[2])
 		return 0
 	else
 		echo "$chosen"
@@ -169,28 +196,34 @@ function yelp()
 	else  # zsh
 		emulate -L zsh  # because we may be sourced by zsh `emulate bash -c`
 		# $funcfiletrace has format:  file:line
-		local file=${funcfiletrace[1]%:*} line=${funcfiletrace[1]##*:}
-		local func=${funcstack[2]}
-		[[ "$func" =~ '/' ]] && func=source  # $func may be filename. Use bash behaviour
+		#local file=${funcfiletrace[1]%:*} line=${funcfiletrace[1]##*:}
+		#local func=${funcstack[2]}
+		#[[ "$func" =~ '/' ]] && func=source  # $func may be filename. Use bash behaviour
+		# techo "${file##*/}:$func:$line $*"
+		#print -l -- funcfiletrace $funcfiletrace - funcsourcetrace $funcsourcetrace - funcstack $funcstack - functrace $functrace
+		local integer n=$#functrace i=${1:-0}
+		[[ $functrace[$n] = $SHELL:* ]] && ((n--))
+		for ((i++; i<=n; i++)); do
+			techo -c warn $functrace[$i] $_C in $C[lgray]$funcfiletrace[$i]
+		done
 	fi
-	techo "${file##*/}:$func:$line $*"
 }
 [ -z "$BASH" ] || return
 function array_dump()
 {
 	local key val
 	if [[ $(vartype "$1") = association* ]]; then
-		echo "dump of \"$1\":"
-		for key val in ${(Pkv)1}; do
-			echo "${(q)key} -> ${(q)val}"
+		techo -c head "dump of \"$1\" (size: ${(P)#1}):"
+		for key in ${(Pk)1}; do
+			techo "${(qq)key} -> ${(qqq)${(P)1}[$key]}"
 		done
 	elif [[ $(vartype "$1") = array* ]]; then
-		echo "dump of \"$1\":"
-		for key in ${(k)1}; do
-			echo "${(qqqP)1[$key]}"
+		techo -c head "dump of \"$1\" (size: ${(P)#1}):"
+		for val in "${(P@)1}"; do
+			techo "${(qqq)val}"
 		done
 	else
-		echo "Not an array."
+		techo -c err "\"$1\": not an array."
 	fi
 }
 function _push()
@@ -244,12 +277,12 @@ function run()
 {
 	local ret cmd fullcmd logfile watch
 	local sudo trysudo dryrun verbose color alert print
-	local cmdinst workdir skipErrors
+	local cmdinst workdir skipErrors okcodes
 
 	if [[ "${1:0:1}" == - ]]; then
 		zparseopts -M -D - v:=verbose c:=color a=alert p:=print \
 			s=sudo S=trysudo n=dryrun I:=cmdinst -cd:=workdir E=skipErrors \
-			l:=logfile w:=watch
+			l:=logfile w:=watch N:=okcodes -ok-exit-codes:=N
 
 		[[ "$1" == - ]] && shift
 		[[ ${1:0:1} == - ]] && { abort 1 "Invalid command: $1"; return }
@@ -291,6 +324,12 @@ function run()
 			fi
 			cd "$workdir" || throw $?
 		fi
+		if [[ -z $okcodes ]]; then
+			okcodes=(0)
+		else
+			explode -v okcodes "$okcodes[2]" ','
+			in_array okcodes 0 || okcodes+=(0)  # add 0 to successful exit codes
+		fi
 
 		# # # # # # # # # #
 		# Execute command #
@@ -311,7 +350,9 @@ function run()
 		fi
 		ret=$?
 
-		[[ -n $DEBUG ]] && set -x
+		if [[ -n $DEBUG ]]; then
+			typeset -tf $cmd || set -x
+		fi
 		[[ $ret -eq 130 ]] && throw $ret
 		if [[ $ret -eq 127 ]]; then
 			chkCmdInstall $cmd $cmdinst[2]
@@ -325,15 +366,18 @@ function run()
 				ret=$?
 			fi
 		fi
-		[[ -n $DEBUG ]] && { set +x ; return $ret }
+		if [[ -n $DEBUG ]]; then
+			typeset +tf $cmd || set +x
+			return $ret
+		fi
 
-		if [[ $ret -ne 0 ]]; then
+		if ! in_array okcodes $ret; then #TODO
 			if [[ -n "$trysudo" ]]; then
 				techo "Trying with sudo"
 				color sudo $fullcmd
 				ret=$?
 			fi
-			[[ $ret -ne 0 ]] && throw $ret
+			in_array okcodes $ret || throw $ret
 		fi
 	} always {
 		if catch '*'; then
@@ -424,6 +468,8 @@ function color()
 
 function colorify()
 {
+	local line data debug
+	zparseopts -D -M - d:=debug
 	#@broken: [ ! -p /dev/stdin ] && exit 0
 	if [ "$1" = '-all' ] || [ "$1" = '-c' ]; then
 		if [ "$1" = '-all' ]; then
@@ -433,23 +479,58 @@ function colorify()
 			shift
 		fi
 		shift
-		while read line; do
-			echo "${C[$c]}$line$C_"
-		done
+		if [[ -n $1 ]]; then
+			data=("${(@f)@}")
+			for line in $data; do
+				echo "${C[$c]}$line$C_"
+			done
+		else
+			while read line; do
+				echo "${C[$c]}$line$C_"
+			done
+		fi
 	else
-		awk '
-		BEGIN{IGNORECASE=1}
-		function color(c,s) {
-			printf("\033[%dm%s\033[0m\n",90+c,s)
-		}
-		/\.php/ {color(2,$0);next}
-		/error/ {color(1,$0);next}
-		/success/ {color(2,$0);next}
-		/warning/ {color(3,$0);next}
-		/INFO/ {color(4,$0);next}
-		/DBG/ {color(5,$0);next}
-		{print}
-		' $1
+		local a cmd
+		if [[ -n $debug ]]; then
+			cmd=$debug[2]
+			while read line; do
+				if [[ $line =~ ^\\+$cmd:([0-9]+)\>\ (.*) ]]; then
+					techo -c lcyan $cmd:$match[1] ${_C}$match[2]
+				elif [[ $line =~ ^\\+([[:alnum:]]+):([0-9]+)\>\ (.*) ]]; then
+					techo -c blue $match[1]:$match[2] ${_C}$match[3]
+				else
+					techo $line
+				fi
+			done
+		else
+			while read line; do
+				techo $line
+			done
+		fi
+#			debug=$(cat)<<-END
+#				function dbg(c,name,line,str) {
+#					printf("\033[%dm%s\033[1m%s\033[0m> %s\n",90+c,name,line,str)
+#				}
+#				/^\+${debug[2]}:([0-9]+)> (.*)/ {dbg(5,"${debug[2]}",\$1,\$2);next}
+#				/^\+([[:alnum:]]+):([0-9]+)> (.*)\\n/ {dbg(6,\$1,\$2,\$3);next}
+#			END
+#		fi
+#		a=$(cat)<<-END
+#		BEGIN{IGNORECASE=1}
+#		function color(c,s) {
+#			printf("\033[%dm%s\033[0m\\n",90+c,s)
+#		}
+#		$debug
+#		/\.php/ {color(2,\$0);next}
+#		/error/ {color(1,\$0);next}
+#		/success/ {color(2,\$0);next}
+#		/warning/ {color(3,\$0);next}
+#		/INFO/ {color(4,\$0);next}
+#		/DBG/ {color(5,\$0);next}
+#		{print}
+#		END
+#		echo "a=${(qqq)a}"
+#		awk -D -f <(<<< ${(q)a}) </dev/stdin
 	fi
 }
 
@@ -469,10 +550,10 @@ alias q=queue
 # Added 2019-06-04 17:47
 function queue()
 {
-	local qid qidFilter place cmd queue
+	local qid qidFilter place cmd queue queues
 	zparseopts -D - p:=place
 	if [[ $# -eq 0 ]]; then
-		cmd=show
+		cmd='show'
 		qidFilter='*'
 	else
 		cmd=$1 ; shift
@@ -484,20 +565,32 @@ function queue()
 	place=${place[2]:-all}
 
 	case $cmd in
-	add)
-		for queue in $CFG/queue.$place.$~qidFilter; do
-			echo "$@" >> $queue
-		done
-	;;
-	show|*)
-		include file
-		[[ $cmd != show && -z $qidFilter ]] && qidFilter=$cmd
-		for queue in $CFG/queue.$place.$~qidFilter; do
-			qid=$(getext $queue)
-			run -p "Queue: $qid ($place)" more $queue 
-		done
-	;;
+		add)
+			queues=($CFG/queue.$place.$~qidFilter)
+			queue=$(chooser $queues:t "New queue" "Browse full path") || cancel
+			if [[ "$queue" == "New zsh library" ]]; then
+				queue=$(input -p "Enter queue id") || cancel
+				is_full_path || queue=$CFG/$queue
+			elif [[ "$queue" == "Browse full path" ]]; then
+				queue=$(chooser -p "Choose path of queue" --dir) || cancel
+			fi
+
+			input -p "Add to queue $queue" "$@" >> $queue || cancel
+			;;
+		show)
+			include file
+			[[ $cmd != 'show' && -z $qidFilter ]] && qidFilter=$cmd
+			for queue in $CFG/queue.$place.$~qidFilter; do
+				qid=$(getext $queue)
+				run -p "Queue: $qid ($place)" show $queue 
+			done
+			;;
+		*)
+			techo -c err "$cmd: invalid command"
+			usage
 	esac
 
+	function usage() {
+		techo -c warn "$0 [-p place] command [id_filter]\ncommands: add, show"
+	}
 }
-
diff --git a/zsh_libs/zsh_git b/zsh_libs/zsh_git
--- a/zsh_libs/zsh_git
+++ b/zsh_libs/zsh_git
@@ -77,20 +77,85 @@ function croot()
 }
 
 # Added 2019-01-25 11:17:01
+# https://github.com/search?q=
+alias gh='github'
+[[ ! -v comp ]] && typeset -g -a comp
+comp+=('github=cd' 'gh=cd')
 function github()
 {
-    set -x
-    [[ -n "$1" && ! -d "$1" ]] && open https://github.com/$1 || github $(gitgetrepo ${1:-.})
-    set +x
-
+	local url repo search echo
+	zparseopts -D -M - r=repo s=search e=echo
+	if [[ $# -eq 0 ]]; then
+		open "https://github.com/"
+	elif [[ -n $search ]]; then
+		open "https://github.com/search?q=$(omz_urlencode $*)"
+	elif [[ -n $repo ]]; then
+		url="https://github.com/$*"
+		[[ -n $echo ]] && echo $url || open $url
+	elif url=$(gitgetrepo "$*"); then
+		[[ -n $echo ]] && echo $url || open $url
+	else
+		githubAPI $echo "$@"
+	fi
 }
+
+#
+function githubAPI()
+{
+	local limit=20 endpoint='https://api.github.com/graphql' request response fields
+	local echo
+	zparseopts -D -M - e=echo
+
+	request=$(cat) <<-GQL
+	{ 
+		"query":"query(\$search:String!,\$limit:Int!){
+			search(query:\$search, first: \$limit, type: REPOSITORY){
+				nodes {
+				... on Repository {
+					nameWithOwner, description, stargazers { totalCount }, createdAt, updatedAt
+				}
+				}
+			}
+		}",
+		"variables":{ "search":"$(omz_urlencode "$*")","limit":$limit }
+	}
+	GQL
+	fields='.data.search.nodes[] | .nameWithOwner,.description,.stargazers.totalCount,.createdAt,.updatedAt'
+
+	response=$(curl -sS -H "Authorization: bearer $GITHUB_API_TOKEN" -X POST -d "${request//$'\n'/}" $endpoint)
+	if [[ $? -eq 0 ]]; then
+		local field
+		typeset -a repos tmp
+
+		while read -r field; do
+			tmp+=("$(trim "$field")")
+			if (($#tmp == 5)); then
+				repos+=("$tmp")
+				tmp=
+			fi
+		done < <(jq -cr "$fields" <<<$response)
+		
+		if [[ $#repos -eq 0 ]]; then
+			techo "No repositories found"
+		elif [[ $#repos -eq 1 ]]; then
+			github -r $echo $(explode "$repos" ' ' 1)
+		else
+			name=$(chooser -s' ' -f1 "$repos" "Open this search in github") || cancel
+			[[ "$name" == 'Open' ]] && github -s "$*" || github -r $echo $name
+		fi
+	fi
+}
+
 function gitgetrepo()
 {
-    local repo
-    ( 
-        [[ -n "$1" && "$1" != "." && -d "$1" ]] && cd $1
-        repo=$(git remote show origin | awk -F: '/Fetch URL/{print $3}')
-        echo "${repo%.*}"
+    local repo d q
+	zparseopts -D -M - d:=d
+    (
+        [[ -n "$d" ]] && d=$d[2] || d="$*"
+		[[ -d "$d" ]] && cd $1 || { techo -c err "Directory not found: $1"; return 1 }
+		repo=$(git remote show origin 2>/dev/null) || return 1
+        repo=$(echo $repo | awk '/Fetch URL/{print $3}')
+        [[ -n $repo ]] && echo "$repo"
     )
 }
 
@@ -139,4 +204,23 @@ function gremote()
 	#zparseopts c=current
 	
 	remote=($(git remote))
+}
+
+function url() {
+	local schemes=(http https ftp scp git)
+	[[ "$1" = 'getscheme' ]] && {
+		[[ $2 =~ (${(j.|.)schemes})"://"* ]] && echo $match[1]
+	}
+}
+
+# Added 2019-09-03 19:04
+function gclone()
+{
+	local repo
+	cd $HOME/repos
+	for repo; do
+		if [[ -n "$(url getscheme $repo)" ]] || repo="$(github -e $repo)"; then
+			git clone "$repo" #&& cd TODO
+		fi
+	done
 }
diff --git a/zsh_libs/zsh_main b/zsh_libs/zsh_main
--- a/zsh_libs/zsh_main
+++ b/zsh_libs/zsh_main
@@ -1,16 +1,17 @@
-VERSION=1.0.5
+VERSION=1.0.7
 [[ "$SUDO_USER" != "" ]] && export HOME=~$SUDO_USER
 export PATH=$PATH:$HOME/bin
 export NOSND=1
 [[ -z "$ZSH_LIBS" ]] && export ZSH_LIBS=${$(realpath $0):h}
+[[ -v comp ]] || typeset -g -a comp
 
 function techo() {
 	local c args nonl
-    zparseopts -M -D - c:=c n=nonl
+	zparseopts -M -D - c:=c n=nonl
 	[[ -n "$nonl" ]] && args=('-n')
-	[[ -z $TTY || ! -c $TTY ]] && TTY=/dev/null  # stdout
+	[[ -z $TTY || ! -c $TTY ]] && TTY=/dev/null # stdout
 	if [[ -n "$c" ]]; then
-		c="$c[2]"
+		c="${c[2]}"
 		[ -z "${C[$c]}" ] && type colorSet >/dev/null && colorSet $c
 		while [[ ${1[1]} = '-' ]]; do
 			args+=("$1")
@@ -29,6 +30,7 @@ function abort() {
 	zparseopts -D - E=skipErrors e=noexception v:=verbose
 	verbose=${verbose[2]:-2}
 	[[ $# -ge 1 ]] && shift
+	yelp 1
 	[[ $# -ge 1 && $verbose -gt 0 ]] && techo -c lred "$@"
 	[[ -n $nostop ]] && return $cod
 	[[ "$ABORT" -gt 0 ]] && $ABORT $cod "$@" 
@@ -39,39 +41,69 @@ function abort() {
 
 function _test()
 {
-	local f="$1", test_f
+	local f="$1" test_f l
+	[[ $# -eq 0 ]] && abort 1 "Missing argument"
 	test_f="_test_$f"
+	type $test_f || abort 127 "Function \"$test_f\" not found"
 	$test_f && techo "$f $OK" || {
-		techo "$f $FAIL"
-		yelp
+		techo "$f $FAIL $?"
+		#yelp 3
 	}
 }
 
 function _test_explode()
 {
-	local f='explode', a=()
-	a=($($f 'a;b' ';'))
-	[[ -n $a && $a[1] = 'a' && $a[2] = 'b' ]] || return false
+	local f='explode' a=()
+	$f 'a;b' ';'
+	[[ ${a[1]} = 'a' && ${a[2]} = 'b' ]] || return $LINENO
 	a=($($f 'a  b ;; b' ';'))
-	[[ -n $a && $a[1] = 'a  b ' && -z $a[2] && $a[3] = ' b' ]] || return false
+	[[ ${a[1]} = 'a  b ' && -z ${a[2]} && ${a[3]} = ' b' ]] || return $LINENO
 	a=($($f 'a  b ;; b' ' '))
-	[[ -n $a && $a[1] = 'a' && $a[2] = 'b' && $a[3] = ';;' && $a[4] = 'b' ]] || return false
+	[[ -n $a && ${a[1]} = 'a' && ${a[2]} = 'b' && ${a[3]} = ';;' && ${a[4]} = 'b' ]] || return $LINENO
 	return true
 }
 function explode()
 {
-	local _sep=${2:-${sep:- }} str=${1//[[:space:]]/¬}
-	s=(${(ps/$_sep/)str})
-	[ -n "$3" ] && echo "${s[$3]//¬/ }" || echo "${(@)s//¬/\\\x20}"
+	local _var str _sep uniq
+	zparseopts -D -M - v:=_var u=uniq
+	_sep=${2:- }
+	if [[ "$_sep" != ' ' ]]; then
+		str=${(q)1}
+	else
+		str=$1
+	fi
+	str=(${(@zps/$_sep/)str})
+	if [[ -n $uniq ]]; then
+		str=("${(@uz)str}")
+	fi
+	[[ -n "${_var[2]}" ]] && _var=${_var[2]}
+	if [[ -n "$3" ]]; then
+		[[ "$3" = [0-9]## ]] || abort 1 "\$3=$3: not a number"
+		if [[ -n "$_var" ]]; then
+			[[ -v "$_var" ]] || typeset -g $_var
+			eval $_var="'${(Q)str[$3]}'"
+		else
+			echo "${(Q)str[$3]}"
+		fi
+	else
+		[[ -v "$_var" ]] || echo "${str}"
+		_var=${_var:-reply}
+		typeset -ga $_var
+		set -A $_var ${(Q)str}
+	fi
 }
 
 function debug()
 {
-	local cmd=$1
-	shift
-    set -x
-    $cmd "$@" >$TTY
-    set +x
+	local _cmd _data _type keep
+	zparseopts -D -M - k=keep
+	_cmd="$1" ; shift
+	_type="$(typeOf "$_cmd")"
+	[[ "$_type" == 'function' ]] && typeset -tf $_cmd #|| set -x
+	#_data=$($_cmd "$@" 2>&1 | egrep "^\+$_cmd:|[^+]")
+	_data=$($_cmd "$@" 2>&1)
+	[[ -z $keep && "$_type" == 'function' ]] && typeset +tf $_cmd #|| set +x
+	[[ $#_data -gt 0 ]] && colorify -d $_cmd <<<$_data
 }
 
 function vartype() {
@@ -81,17 +113,9 @@ function vartype() {
 # Set info for a lib
 function lib_set_info()
 {
-    local fname=${(U)1}
-	typeset -g ZSH_${fname}_VER=$2
-	typeset -Ag ZSH_${fname}_INFO
-	shift 2
-	#@TODO clone_assoc_array ZSH_${fname}_INFO _temp_aarray
-	set -A ZSH_${fname}_INFO ${(kv)_temp_aarray}
-	#for key val in ${(kv)_temp_aarray}; do
-	#	echo "$key -> $val"
-	#	ZSH_${fname}_INFO[$key]=$val
-	#done
-	unset _temp_aarray
+	local name=${(U)1} info
+	typeset -Ag ZSH_${name}_INFO
+	set -A ZSH_${name}_INFO ver $2 path "$3" required $4 mtime "$5"
 }
 
 function getmime()
@@ -107,18 +131,65 @@ function isScript()
 	}
 }
 
+function typeOf()
+{
+	local name ret tpath
+	name="$1"
+	if [[ ! -f "$name" ]]; then
+		ret=($(which -w $name))
+		type="${ret[2]}"
+		if [[ "$type" != "none" ]]; then
+			if [[ "$type" == "command" ]]; then
+				tpath=$(which $name)
+				if isScript $tpath; then
+					type="script"
+				fi
+			fi
+			echo $type $tpath
+			return 0
+		fi
+		echo "none"
+		return 1
+	fi
+	
+	tpath=$name
+	
+	if isScript $tpath; then
+		type="script"
+	elif [[ -x "$tpath" ]]; then
+		type="command"
+	else
+		echo "none"
+		return 1
+	fi
+	
+	echo $type $tpath
+	return 0
+}
+
+function zindent()
+{
+	echo -n "$@" | sed -E 's/^([^{}])/\t\1/g'
+}
+
 # Include a zsh lib
 function include()
 {
-	local name ver lpath lazyload prefix required force str
-	zparseopts -D -M - l=lazyload p:=lpath -path:=l r=required -required=r f=force
+	local name lpath lazyload required force str mtime info
+	zparseopts -D -M - l=lazyload p:=lpath -path:=lpath r=required -required=r f=force
 
-	name="$1"
-	if [[ -n "$lpath" ]]; then
-		lpath="${lpath[2]}"
-	else
-		lpath="$ZSH_LIBS/zsh_$name"
-	fi
+	[[ $# -eq 0 ]] && return 1
+	[[ "$1" = */* ]] && {
+		lpath="$(getfullpath $1)"
+		name="${$(getfilename $1)#zsh_*}"
+	} || {
+		name="${1#zsh_*}"
+		if [[ -n "$lpath" ]]; then
+			lpath="${lpath[2]}"
+		else
+			lpath="$ZSH_LIBS/zsh_$name"
+		fi
+	}
 		
 	[[ -n $required ]] && required=1 || required=0
 
@@ -131,9 +202,9 @@ function include()
 		return 127
 	fi
 
-	prefix="ZSH_${(U)name}"
-    ver="${prefix}_VER"
-    if [[ -z ${(P)ver} ]] || [[ -n "$force" ]]; then
+	mtime=$(stat -L --printf='%Y' "$lpath") || abort $? 'stat error'
+	info="ZSH_${(U)name}_INFO"
+	if [[ -z ${(P)info} || -n "$force" || "${${(P)info}[mtime]}" -lt "$mtime" ]]; then
 		if ! isScript $lpath; then 
 			techo "\e[91m$lpath is not a script\e[0m"
 			if [[ $required -eq 1 ]]; then
@@ -146,15 +217,12 @@ function include()
 			return 0
 		else
 			#[[ -o interactive ]] && 
-			techo -n "Including $name ($lpath)"
+			techo -n "Including $name (${lpath/$ZSH_LIBS/\$ZSH_LIBS})"
 			source "$lpath"
 			ret=$?
 			if [ $ret -eq 0 ]; then
 				typeset -Ag _temp_aarray
-				_temp_aarray[ver]="$VERSION"
-				_temp_aarray[path]="$lpath"
-				_temp_aarray[required]=${required:-0}
-				lib_set_info $name $VERSION
+				lib_set_info $name $VERSION "$lpath" ${required:-0} "$mtime"
 				#[[ -o interactive ]] &&
 				techo " [\e[92m$VERSION\e[0m]"
 			else
@@ -168,7 +236,72 @@ function include()
 				return $ret
 			fi
 		fi
-    fi
+	fi
 }
 
-lib_set_info main $VERSION # "include" itself
+comp+=("inst=apt")
+function inst()
+{
+	local machine pkgs
+	zparseopts -D -E -M - m:=machine
+	if [[ -z "$machine" ]]; then
+		if [[ ${#@} -ge 1 ]]; then
+			pkgs=("$@")
+		else
+			pkgs=${$(fc -ln -1)[1]}
+		fi
+		sudo apt-get install $pkgs
+	else
+		echo "$@" >> "$CFG/${machine[2]}.pkgs.txt"
+	fi
+}
+
+# Added 2019-09-05 00:57
+# check if any item of array equals value
+# in_array array_name value
+function in_array()
+{
+	local name=$1 val="$2"
+	[[ ${${(P)name}[(i)$val]} -le ${(P)#name} ]]
+}
+
+function ltrim() {
+	echo "${*##[[:blank:]]##}"
+}
+function rtrim() {
+	echo "${*%%[[:blank:]]##}"
+}
+function trim()
+{
+	echo "$(rtrim "$(ltrim "$*")")"
+}
+#@TODO_in_array() { }
+
+comp+=("aptinst=apt")
+function aptinst()
+{
+	sudo apt-get install -y $@
+}
+
+# Added 2019-09-03 19:29
+function libmonitor()
+{
+	local name evt
+	while read -r evt name; do
+		[[ $evt == 'exit' ]] && break
+		techo -c warn "$evt $name"
+	done < <(inotifywait -m -q -e modify -r --format '%e %f' $ZSH_LIBS || echo "exit $?")
+	return $name
+}
+
+# "include" itself
+lib_set_info main $VERSION "$0" 1 "$(stat -L --printf='%Y' "$0")"
+
+if [[ -o interactive ]] && { [[ -z $LIBMON_PID ]] || ! kill -0 $LIBMON_PID 2>/dev/null }; then
+	while ! type inotifywait 2>&1 >/dev/null; do
+		aptinst inotify-tools || {
+			ret=$?
+			[[ $ret -eq 130 || $ret -eq 1 ]] && break
+		}
+	done && { libmonitor & export LIBMON_PID=$! }
+fi
