lots of stuff

diff --git a/zsh_libs/zsh_aliases b/zsh_libs/zsh_aliases
--- a/zsh_libs/zsh_aliases
+++ b/zsh_libs/zsh_aliases
@@ -1,48 +1,17 @@
 VERSION=1.0.7
 [[ -v comp ]] || typeset -g -a comp
 alias e=echo
-alias up='xdotool key Ctrl+Shift+F type ❯ ; xdotool key F3 key F3' # find last prompt
 alias up='xdotool key Ctrl+Shift+F type ❯ ; xdotool key Shift+F3 key Shift+F3' # find last prompt
 alias op="xdg-open"
 alias open="xdg-open"
 alias vmake="make SHELL='$SHELL -x'"
-alias web="cd gp3320/app/bcm-webconf ; . venv/bin/activate ; ./webconf.py &"
 alias sv="v -s"
 alias cfg="cd $CFG"
 alias s="do_sudo"
 alias cpa="sudo cp -a"
 alias mk="make"
 alias apt="sudo apt"
-alias diff_ignore_space="diff --ignore-space-change --ignore-tab-expansion --ignore-trailing-space --ignore-blank-lines"
 alias sys="sudo systemctl"
-alias jtags='find . -type f -iregex ".*\.js$" -not -path "./node_modules/*" -exec jsctags {} -f \; | sed '"'"'/^$/d'"'"' | LANG=C sort > tags'
-alias pytags="ctags -R --python-kinds=-i ."
-
-function tags()
-{
-	local lang args
-	zparseopts -lang:=lang
-	if (($#)) && [[ ! -f $1 && -z $lang ]]; then
-		lang=$1
-		shift
-	elif [[ -n $lang[2] ]]; then
-		lang=$lang[2]
-	else
-		lang=$(chooser Javascript PHP Python Shell) || cancel
-	fi
-
-	#args=${@:-
-	case ${(L)lang} in
-		javascript|js)
-			type jsctags >/dev/null || npm install -g git+https://github.com/ramitos/jsctags.git
-			jtags
-			;;
-		php) phpctags -R --exclude='vendor/*' $args ;;
-		python|py) pytags ;;
-		shell|sh) ctags --language-force=Sh -R . ;;
-		*) techo -c err "Unsupported language: $lang" ;;
-	esac
-}
 
 function hg()
 {
@@ -63,23 +32,41 @@ function aptlist()
 
 function mkscript()
 {
-	local shell func name edit
+	local shell func name edit append ret=1
 	local file isLib help line data data2 _type
 	zparseopts -D -K s:=shell f:=func n:=name e=edit
 	
+	(($#func)) && func=$func[2]
 	data2="$@"
-	if [[ -n $func[2] ]]; then
-		func=$func[2]
-		_type=($(typeOf $func))
-		(($#_type))
-		if [[ "" == 'function' ]]; then
-			techo -c warn "$func() already exists"
-			vw $func
-			return
+	while ((ret)); do
+		input -p "Function name" -v func || cancel
+		if (($#func)); then
+			_type=($(typeOf $func))
+			if in_array 'function' _type; then
+				techo -c warn "$func() already exists"
+				#@TODO 
+				chooser -v tmp -f1 -p "$func() already exists" \
+					"Rename" \
+					'Append' \
+					"Edit $func()" \
+					'Cancel' || cancel
+
+				if [[ $tmp == 'Edit' ]]; then
+					vw $func && return
+					ret=0
+				elif [[ $tmp == 'Cancel' ]]; then
+					cancel
+				elif [[ $tmp == 'Rename' ]]; then
+				elif [[ $tmp == 'Append' ]]; then
+					ret=0
+					append=1
+				fi
+			else
+				ret=0
+			fi
 		fi
-		#@TODO function already exists? (c)ancel, (e)dit, (o)verwrite
-	fi
-	input -p "Function name" -v func
+	done
+
 	isLib=false
 	if [[ -n "$name" ]]; then
 		local err_exists="exists but isn't a shell script."
@@ -133,11 +120,11 @@ function mkscript()
 	if [[ ! -f "$file" ]]; then
 		# Create library
 		if isLib; then
-			data="VERSION=1.0.0\n[[ -v comp ]] || typeset -g -a comp"
+			data=$(< $ZSH_LIBS/zsh_blank)
 		else
 			# Create script
-			[[ -n "$shell" ]] && shell="/bin/"$shell[2] || shell=$SHELL
-			data="#!${shell}\n"
+			[[ -n $shell ]] && shell="/bin/"$shell[2] || shell=$SHELL
+			data="#!${shell}"
 		fi
 	fi
 
@@ -151,15 +138,15 @@ function mkscript()
 		data+=$(zindent "$data2")
 	fi
 
-	echo ${data}$'\n' >> $file
+	echo -n $data >> $file
 	$isLib && source $file && { type $func ; which $func; }
 
 	# setup file
-	[[ -x "$file" || $isLib ]] || chmod +x $file
+	[[ -x $file || $isLib ]] || chmod +x $file
 
 	# edit
-	if [[ -n "$edit" || -z "$data2" ]] || confirm "Edit file"; then
-		if [[ -n "$func" ]] && $isLib; then
+	if [[ -n $edit || -z $data2 ]] || confirm "Edit file"; then
+		if [[ -n $func ]] && $isLib; then
 			edfunc $func
 		else
 			gvim -f $file
@@ -197,7 +184,7 @@ function add_key()
 }
 
 # finds command(s) in an alias
-function inalias()
+function inAlias()
 {
 	local needsFunc ret=1 arr
 	zparseopts -D -M - f=needsFunc
@@ -249,7 +236,7 @@ function inalias()
 							return 1
 						fi
 					else
-						tmp=($(inalias $needsFunc $m)) || return 1
+						tmp=($(inAlias $needsFunc $m)) || return 1
 						f=($tmp[1])
 						break
 					fi
@@ -282,11 +269,10 @@ function inalias()
 
 function edalias()
 {
-	local linenum pat file var
-	zparseopts -D -M l:=linenum
-	[[ -n "$1" ]] || return 1
-	if [[ "$1" == '-f' ]]; then
-		shift
+	local linenum pat file var isFunc
+	zparseopts -D -M l:=linenum f=isFunc
+	[[ -n $1 ]] || return 1
+	if (($#isFunc)); then
 		pat="(function +)?$1\(\)"
 		linenum=${linenum[2]:-2}
 	else
@@ -295,7 +281,10 @@ function edalias()
 	fi
 	if (($#2)); then
 		file=$2
-		var=("${(@f)$(egrep -rHn "^([^#]* )?$pat" $file)}") || var=($file:0)
+		#var=("${(@f)$(egrep -rHn "^([^#]* )?$pat" $file)}") || var=($file:0)
+		if ! var=("${(@f)$(egrep -rHn "^([^#]* )?$pat" $file)}"); then
+			[[ $(getfilename $file) == $1 ]] && var=($file:0)
+		fi
 	else
 		var=("${(@f)$(egrep -rHn "^([^#]* )?$pat" $ZSH_LIBS $fpath)}")
 	fi
@@ -331,7 +320,11 @@ function edalias()
 			v $file
 		fi
 	else
-		techo -c err "Could not find \"$1\" alias"
+		if (($#isFunc)); then
+			techo -c err "Could not find function $1()" 
+		else
+			techo -c err "Could not find alias $1"
+		fi
 	fi
 }
 
@@ -343,10 +336,11 @@ function edfunc()
 		autoload +X $1 && edfunc $1
 		return
 	elif [[ $arg[5] != 'function' ]]; then
-		if [[ $arg[4] != 'alias' ]] || (( ! $#functions[$1] )); then
+		if [[ $arg[4] == 'alias' ]] && (($#functions[$1])); then
+			file=$functions_source[$1]
+		else
 			abort 2 "$1 is not a function:\n\t$arg"
 		fi
-		file=$functions_source[$1]
 	elif [[ -f $arg[-1] ]]; then
 		file=$arg[-1]
 	else
@@ -364,6 +358,7 @@ function edfunc()
 	fi
 	edalias ${2:+-l $2} -f "$1" "$file" 
 }
+
 comp+=("vw=exec")
 function vw()
 {
@@ -371,6 +366,10 @@ function vw()
 	array=($(explode "$1" ':')) ; name=$array[1]; linenum=$array[2]
 	array=($(type -w "$name"))
 	case "${array[2]}" in
+		none)
+			[[ -f $name ]] || abort 127 'Command not found'
+			v $name:$linenum
+			;;
 		function)
 			edfunc $name $linenum
 			;;
@@ -382,7 +381,7 @@ function vw()
 				func=$name
 			else
 				if [[ $(type -f $name) =~ "^$name is an alias for (.*)$" ]]; then
-					func=$(inalias -f $name)
+					func=$(inAlias -f $name)
 				fi
 			fi
 
@@ -394,9 +393,9 @@ function vw()
 			;;
 		command)
 			cpath=$(which "$name")
-			if [[ -f "$cpath" ]]; then
+			if [[ -f $cpath ]]; then
 				mime=$(getmime $cpath)
-				if [[ "$mime" == "application/x-sharedlib" ]]; then
+				if [[ $mime == 'application/x-sharedlib' ]]; then
 					echo "$tpath is binary executable"
 					return 1
 				fi
@@ -449,16 +448,6 @@ function v()
 	done
 }
 
-function finderror()
-{
-	errline=`tail /var/log/apache2/error.log |  grep -e "PHP \(Parse\|Fatal\|Notice\)" | tail -n1`
-	str=`echo $errline| sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'`
-	linenum=`echo $str | sed 's/.*line \([0-9]*\).*$/\1/'`
-	filename=`echo $str | sed 's/.*\(\/media\/sparc\/xdata\/[^ ]*\).*$/\1/'`
-	echo $filename
-	echo $linenum
-	#v "$filename:$linenum"
-}
 function cptree()
 {
 	local dest=$1
@@ -554,8 +543,9 @@ function send()
 function ge()
 {
 	local sudo icase in_exts ex_exts ex_dirs width prefix
-	local opts args 
+	local opts args defExDirs defExExts
 	zparseopts -D -E -M - i=icase s=sudo --exclude:=ex_exts E:=ex_dirs C::=width -cols::=C
+	
 	IFS=',;: ' read -rA in_exts <<<"$1"
 	shift
 	#	exc=("--exclude-dir=extensions" "--exclude-dir=bckup_extensions")
@@ -563,8 +553,10 @@ function ge()
 		IFS=',;: ' read -rA ex_exts <<<$ex_exts[2]
 		opts+=('--exclude=*.'${^ex_exts[@]})
 	fi
+	(($#ex_dirs)) || ex_dirs=(- node_modules,android,vendor)
 	if (($#ex_dirs)); then
 		IFS=',;: ' read -rA ex_dirs <<<$ex_dirs[2]
+		techo "Excluding dirs: $ex_dirs"
 		opts+=('--exclude-dir='${^ex_dirs[@]})
 	fi
 	opts+=('--include=*.'${^in_exts[@]} --color=always $icase)
@@ -580,7 +572,7 @@ function ge()
 			return
 		fi
 	fi
-	((width=$(tput cols)-50))
+	((width=$(tput cols)+50))
 	$prefix grep -rn $opts "$@" | cut -c1-$width
 }
 
@@ -589,113 +581,6 @@ function duh()
 	local sudo
 	[[ "$1" == '-s' ]] && { shift; sudo='sudo'; }
 	$sudo du -csh "$@" | sort -h
-}
-
-# Added 2019-01-10 11:26:22
-function extract_cpio_image()
-{
-    local ret name mime sourceDir imgfile=$(getfullpath "$1") targetroot targetDir uncompressed tmp
-	[[ -n $imgfile ]] || abort 1 "No image given"
-	[[ -s $imgfile ]] || { abort 127 "$imgfile: not found" ; return; }
-	sourceDir=$(getpath "$imgfile")
-	name=${$(getfilename "${(L)imgfile%.img}")#u}
-    targetDir=${2:-$PWD/$name}
-    (
-		if [[ -f "$targetDir" ]]; then
-			# targetDir=${targetDir}
-			techo -c warn "A file exists in place of target dir: \"$C[warn]$targetDir$C_\""
-			return 1
-			#targetDir=$(input "Choose another path/filename" "$targetDir")
-		fi
-		
-		if [[ -d "$targetDir" ]]; then
-			isEmptyDir "$targetDir" || {
-				confirm "Dir $targetDir not empty. $C[lred]Remove files and continue" \
-					|| { cancel ; return; }
-				run -s rm -rf "$targetDir"/* || { abort $? ; return; }
-			}
-		else
-			confirm Create dir '"$targetDir"' && \
-				run -s mkdir -p "$targetDir" || { abort $? ; return; }
-		fi
-		#uncompressed="$imgfile.cpio"
-		#if [[ "$imgfile" -ot "$uncompressed" ]] && [[ -s "$uncompressed" ]] && \
-		#	! confirm -c warn "$uncompressed is newer than $imgfile\nOverwrite it"
-		#then
-		#	{ cancel ; return; }
-		#fi
-		mime=$(getmime "$imgfile")
-		tmp="$imgfile"
-		if [[ "$mime" == 'application/octet-stream' ]]; then
-			mime=$(file "$imgfile")
-			if [[ $mime =~ 'cpio archive' ]]; then
-				uncompressed="$imgfile" # already a cpio file
-				tmp=
-			elif [[ $mime =~ 'u-boot' ]]; then
-				tmp="$sourceDir/$name.img.gz"
-				[[ -f "$tmp" ]] && rm -f "$tmp"
-				run -S -p 'U-Boot image detected. Extracting ramdisk.' \
-					dd if="$imgfile" of="$tmp" bs=64c skip=1
-				mime=$(getmime "$tmp")
-			fi
-		fi
-		
-		techo cd $targetDir
-		cd $targetDir || return
-		if [[ -n "$tmp" ]]; then
-			if [[ "$mime" == 'application/gzip' ]]; then
-				run -s -p "cpio: inflating $tmp -> $PWD/" \
-					cpio -idmv < <(run zcat "$tmp") || return
-			else
-				abort 2 "$tmp is not a gzip (mime=$mime)"
-				return 1
-			fi
-		else
-			run -s -p "cpio: inflating $uncompressed -> $PWD/" \
-				cpio -idmv --file="$uncompressed" || return
-		fi
-    ) && cd $targetDir
-}
-function compress()
-{
-    local alg sudo
-	[[ $1 == -s ]] && { sudo=sudo ; shift; }
-	alg=$1 ; shift
-    case "$alg" in
-        "gzip")
-            $sudo gzip -c < $1 > $2
-            ;;
-
-        "lzo")
-            $sudo lzop $1 -o $2
-            ;;
-
-        *)
-            $sudo minigzip < $1 > $2
-            ;;
-    esac
-}
-
-function compress_cpio_image()
-{
-    local sourceDir targetImg imgName compalg ignore var
-	zparseopts -D - i:=ignore
-	sourceDir=$1 ; [[ -z $sourceDir || $sourceDir = . ]] && sourceDir=$PWD
-	targetImg=$(getfullpath "${2:-$sourceDir}.img")
-	targetDir=$(getpath $targetImg)
-	imgName=u${(C)$(getfilenoext $targetImg)}
-	compalg=${3:-mzip}
-	if [[ -n $ignore ]]; then
-		explode -v ignore $ignore[2] ':'
-		ignore=('-path ./'${^ignore})
-		ignore="( ${(j. -o .)ignore} ) -prune -o -print"
-	fi
-	
-	(techo cd $sourceDir ; cd $sourceDir && run compress -s $compalg \
-		<(cpio -ov -H newc -R root:root < <(run -s find ${(z)ignore}) ) $targetImg
-	) &&
-		run mkimage -A arm -O linux -T ramdisk \
-			-d $(getfullpath -r=$PWD $targetImg) $(getfullpath -r=$PWD $targetDir/$imgName)
 }
 
 # Added 2019-01-11 16:33:46
@@ -708,14 +593,6 @@ function stripcolors()
 function shpydf()
 {
     output=`pydf`; devs=`echo $output | cut -f1 -d `; labels=`sudo lsblk --noheadings -o LABEL $devs|stripcolors`; for line in $output; do i=1; echo "${labels[$i]} $line"; i++; done
-}
-
-# Added 2019-01-16 19:18:20
-# create progress bar
-function pbar()
-{
-	include -r progress_bar || return 1
-	pbar "$@"
 }
 
 # Added 2019-02-20 15:38:03
@@ -757,20 +634,16 @@ function mkcp()
 	cp "$@"
 }
 
-# Added 2019-04-04 14:54
-function ipfind()
-{
-	local user=${1:-debian} net
-	net=192.168.0
-	for ip in $(seq $(($last+1)) 254); do
-		last=$ip
-		ping -W3 -c1 $net.$ip && ssh $user@$net.$ip
-		echo ret=$?
-	done
-}
-
 # Added 2019-04-11 01:43
 function logs()
 {
-	tail {.,$(git root)}/logs/{api,debug}.txt -f &
+	run tail $(git root)/logs/{api,debug,php}.txt -f &
+}
+
+# Added 2020-01-14 21:06
+function fixtty()
+{
+	# show cursor
+	tput cnorm # or echo -en "\e[?25h"
+	confirm 'Reset terminal' && tput reset
 }
diff --git a/zsh_libs/zsh_file b/zsh_libs/zsh_file
--- a/zsh_libs/zsh_file
+++ b/zsh_libs/zsh_file
@@ -1,4 +1,5 @@
-VERSION=1.0.7
+VERSION=1.0.8
+#lazyload=urlfollow,urlinfo,vnc,imdb,globo,awkWrapper
 
 setopt nomultios
 
@@ -43,7 +44,7 @@ function isDir()
 			return 2
 		fi
 		[[ -z $mk ]] && return 1
-		confirm "dir $dir doesn't exist. Create" && run -S mkdir $dir
+		confirm "dir $dir doesn't exist. Create" && run -S mkdir -p $dir
 	fi
 }
 
@@ -88,6 +89,7 @@ function rename()
 {
 	local orig name dir fullpath
 	(( $# )) || usage $0
+	#@TODO is link? confirm rename link or link target
 	[[ "$1" == '-s' ]] && { shift; sudo='-s' }
 	orig="$(getfilename "$1")"
 	dir="$(getpath $(getfullpath $1))"
@@ -123,16 +125,19 @@ function ddiff()
 				shift
 			fi
 		fi
-		if [[ -z $dir1 ]]; then
-			input -p "Dir 1" -v var || return
+		local buttons=(--okcodes '0 1' -b "Current directory [$PWD]:1")
+		if [[ -z $dir1 || -n $config ]]; then
+			var=$dir1
+			input -p "Dir 1" -v var $buttons || return
 			isDir -m $var && dir1=$var || return
 		fi
-		if [[ -z $dir2 ]]; then
-			input -p "Dir 2" -v var || return
+		if [[ -z $dir2 || -n $config ]]; then
+			var=$dir2
+			input -p "Dir 2" -v var $buttons || return
 			isDir -m $var && dir2=$var || return
 		fi
 		d1=$dir1; d2=$dir2
-		echo "dir1=$dir1\ndir2=$dir2"
+		techo "dir1: $dir1\ndir2: $dir2"
 	fi
 
 	if [[ -d $dir1 && -d $dir2 ]]; then 
@@ -156,12 +161,13 @@ function syncDirs()
 	local integer i n
 	local src targets dir data rsArgs checksum arg
 	local quiet sudo excludeFrom dry extraArgs reverse
-	local files stat name
+	local files stat name noSlash
 	typeset -a src targets rsArgs extraArgs files excludePatterns
-	zparseopts -D -M - q=quiet s=sudo i:=excludeFrom d=dry t:=targets c=checksum r=reverse
+	zparseopts -D -M - q=quiet s=sudo i:=excludeFrom d=dry \
+		c=checksum r=reverse -no-add-slash=noSlash
 
 	[[ -z "$sudo" ]] && sudo='-S'
-	[[ $# -ge 2 ]] || abort 1 "usage: $0 source1 [.. sourceN] target1[,target2]"
+	(($# >= 2)) || abort 1 "usage: $0 source1 [.. sourceN] target1[,target2]"
 	
 	n=$#
 	for arg; do
@@ -178,8 +184,10 @@ function syncDirs()
 	#if [[ $#src -eq 0 ]]; then
 	#	src=($(box get backupconfig))
 	#fi
-	if [[ -z "$targets" ]]; then
-		input "Enter target directory" -v targets || cancel
+	if ((!$#targets)); then
+		#@TODO: show current selected directories and allow addition and removal
+		local buttons=(--okcodes '0 1' -b "Current directory [$PWD]:1")
+		input --multi --dir -p 'Enter target directories' -v targets || cancel
 	fi
 
 	if [[ -n $reverse ]]; then
@@ -187,7 +195,6 @@ function syncDirs()
 		targets=($src)
 		src=($files)
 	fi
-
 
 	# # # # # # # # # #	   -t, --times           preserve modification times
 	# rsync arguments #    -O, --omit-dir-times  omit directories from --times
@@ -203,19 +210,59 @@ function syncDirs()
 	excludePatterns=(.osync_workdir 'backup*' '*.local' '.bsync*' '.git' 'node_modules')
 	rsArgs+=(--exclude=$^excludePatterns)
 	[[ -n $excludeFrom ]] && rsArgs+=(--exclude-from="${excludeFrom[2]}")
+
 	for ((n=1; n<=$#src; n++)); do
-		if [[ -d "${src[$n]}" ]]; then
-			if [[ -f "${src[$n]}/rsync.ignore" ]]; then
-				rsArgs+=(--exclude-from="${src[$n]}/rsync.ignore")
+		local isRemoteDir=0 isEmptyDir=0
+		dir=$src[$n]
+		if [[ $dir =~ (.*):(.*) ]]; then
+			local ret host=$match[1] p=$match[2]
+			ret=($(ssh $host \
+				"if [[ -d $p ]]; then
+					glob=("$p"(N/F))
+					v=\$#glob
+					if ((v)) && [[ -f $p/rsync.ignore ]]; then
+						echo -n 1i
+					else
+						echo -n \$v
+					fi
+				elif [[ -f $p ]]; then
+					echo -n f
+				fi"
+			))
+			case $ret in
+				1*)
+					isRemoteDir=1
+					((!$#noSlash)) && [[ ${dir: -1} != / ]] && src[$n]+='/'
+					if [[ $ret == '1i' ]]; then
+						#@TODO: scp $dir/rsync.ignore /tmp)
+						#rsArgs+=(--exclude-from=$fIgnore)
+					fi
+					;;
+				f) ;;
+				0)
+					confirm -c warn "Empty remote directory$C_: $C[lred]'$host:$p'. \
+						Ignore and continue" || cancel
+					src[$n]=(); ((n--))
+					;;
+				'')
+					confirm -c warn "Source $host:$p not found. Ignore and continue" || cancel
+					src[$n]=(); ((n--))
+					;;
+				*) abort 1 "Invalid response from $host: '$ret'" ;;
+			esac
+		elif [[ -d $dir ]]; then
+			if isEmptyDir $dir; then
+				confirm -c warn "Empty directory$C_: $C[lred]'$dir'. \
+					Ignore and continue" || cancel
+				src[$n]=(); ((n--))
+			else
+				((!$#noSlash)) && [[ ${dir: -1} != / ]] && { dir+='/'; src[$n]+='/' }
+				if [[ -f ${dir}rsync.ignore ]]; then
+					rsArgs+=(--exclude-from=${dir}rsync.ignore)
+				fi
 			fi
-			if isEmptyDir $src[$n]; then
-				techo -c err "Empty directory$C_: $C[lred]$src[$n]"
-				return 1
-			fi
-			[[ ${src[$n]: -1} != / ]] && src[$n]+=/
 		fi
 	done
-	
 	techo -c lcyan "Sources: ${(@qq)src}"
 	techo -c lcyan "Targets: ${(@qq)targets}"
 	# rsync arguments from command line
@@ -225,12 +272,20 @@ function syncDirs()
 	# # # # # #
 	# Targets #
 	# # # # # #
-	local nothing=1 permFlags
+	local nothing=1 permFlags ret
 	for dir in $targets; do
-		if isDir -m "$dir"; then
-			[[ "$(fstypeof $dir)" != "vfat" ]] && permFlags='-pog'
+		local host p #sshArgs
+		if [[ $dir =~ ([^:]+):(.*) ]]; then
+			host=$match[1]; p=$match[2]
+			#if [[ -n $sshCFG[$host] ]]; then
+			#	sshArgs=(ssh $sshCFG[$host])
+			#fi
+		fi
+		if isDir -m $dir; then
+			[[ "$(fstypeof $dir)" != 'vfat' ]] && permFlags='-pog'
+			#data="$(run $sudo rsync -ni ${sshArgs[@]} ${rsArgs[@]} $permFlags "$src[@]" $dir)"
 			data="$(run $sudo rsync -ni ${rsArgs[@]} $permFlags "$src[@]" $dir)"
-			if [[ $#data -gt 0 ]]; then
+			if (($#data)); then
 				nothing=0
 				echo $data
 				confirm "Do it" && # run --confirm "Do it"
@@ -293,7 +348,8 @@ function box()
 		[[ -d $base/$box ]] || abort 127
 	fi
 	cd $base/$box
-	[ -d .git ] && git status
+	[ -d .git ] && git status &
+	[[ -d android ]] && include android
 	todo -d . #@TODO mv to cd hook
 }
 
@@ -328,9 +384,10 @@ function attributeSync()
 	_sync
 }
 
+#@TODO
 function _sync() {
-	run -w "isDirty" -p "Flushing caches to disk. Please wait." sync
-	
+	#run -w "isDirty" -p "Flushing caches to disk. Please wait." sync
+	run -p "Flushing caches to disk..." sync
 	#watch -n 1 -c -t  "grep -e 'Dirty:' -e 'Writeback:' /proc/meminfo; kill -0 $pid || killall watch"
 }
 
@@ -409,4 +466,118 @@ function uniqfile()
 		name="$prefix$base$(date +"%Y%m%d-%H%m%S")$suffix"
 	fi
 	echo -n $name
+}
+
+typeset -gA awkFuncs
+awkFuncs=(
+	printArgs '(i,f) {\
+		if (i<0) i=NF+i+1; 	if (f<0) f=NF+f+1;\
+		print "NF="NF,"i="i,"f="f;
+		for (j=i ; j<f ; j++) {\
+			printf("%s%s", $j, OFS);\
+		}\
+		if (j==f) print $j; }'
+	printArray '(A,i,f){\
+		if (i<0) i=length(A)-i+1; 	if (f<0) f=length(A)-f+1;\
+		for (j=i ; j<f ; j++) {\
+			printf("%s%s", A[j], OFS);\
+		}\
+		if (j==f) print A[j]; }'
+)
+
+function awkWrapper()
+{
+	local opts prog _vars _expr _out _inc reSep
+	local _mapCols _cols _row
+	zparseopts -D -M - v:=_vars F:=reSep E=_expr e:=_expr o:=_out \
+		I:=_inc -inc:=I C:=_mapCols -mapColumns:=C c:=_cols -cols:=c
+
+	if [[ -n $_vars ]]; then
+		_vars=(${(P)_vars[2]})
+		opts=('-v '$^_vars)
+		opts=($=opts)
+	fi
+	(($#reSep)) && opts+=($reSep)
+
+	prog=''
+	if (($#_inc)); then #@TODO
+		local fname=$_inc[2]
+		prog+="function ${fname}${awkFuncs[$fname]}"$'\n'
+	fi
+
+	if (($#_expr)); then
+		if (($#_expr > 1)); then
+			_expr=(${(P)_expr[2]})
+		else
+			_expr=("$@[1,4]")
+		fi
+		local x m pat action
+		for x pat m action in $_expr; do
+			if [[ $x == <-> ]]	; then
+				prog+="x==$x"
+			elif [[ $x =~ 'BEGIN|END' ]]; then
+				prog+="$x { $action }"$'\n'
+				continue
+			elif [[ $x == 'function' ]]; then
+				prog+="function $action"$'\n'
+				continue
+			elif [[ $x != '-' ]]; then
+				prog+=$x
+			fi
+			
+			if [[ $pat != '-' ]]; then
+				if [[ $x != '-' ]]; then
+					prog+=' && '
+				fi
+
+				if [[ $m != '-' ]]; then
+					prog+="match(\$0,$pat,$m)"
+				else
+					prog+=$pat
+				fi
+			fi
+
+			prog+=" { $action }"$'\n'
+		done
+	fi
+
+	if (($#_out)); then
+		_out=$_out[2]
+		if (($#_mapCols)); then
+			local key val
+			_mapCols=$_mapCols[2]
+			typeset -gA $_out $_mapCols
+			_row=()
+			while read key val; do
+				col=${${(P)_mapCols}[$key]}
+				[[ -z $col ]] && abort 1 "Invalid column: $key"
+				_row+=($col $val)
+			done < <(awk $opts $prog $1)
+			set -A $_out $_row
+		#elif (($#assoc)); then
+		elif ((1)); then
+			typeset -ga $_out
+			_cols=$_cols[2]
+			typeset -ga $_out $_cols
+			_row=()
+			{
+				local integer i=0
+				read -A _cols 
+				#while read ... $_out; do
+					#col=${${(P)_cols}[$key]}
+					#[[ -z $col ]] && abort 1 "Invalid column: $key"
+					#_row+=($col $val)
+				#	_row+=($col $val)
+				#	((i++))
+				#done
+				read -A $_out
+			} < <(awk $opts $prog $1)
+		else
+			#save line by line to array
+			set -A $_out "${(@f)$(awk $opts $prog $1)}"
+		fi
+	else
+		# raw awk output to stdout
+		awk $opts $prog $1
+	fi
 }
diff --git a/zsh_libs/zsh_main b/zsh_libs/zsh_main
--- a/zsh_libs/zsh_main
+++ b/zsh_libs/zsh_main
@@ -1,19 +1,23 @@
 VERSION=1.0.8
 [[ -v comp ]] || typeset -g -a comp
 
+alias _dbg_trap='[[ -o xtrace ]] && unalias _dbg_trap && include debug && _dbg_trap $0'
 function techo()
 {
-	local c args nonl print noesc ts
+	local c _topts nonl print noesc ts msg
 	_dbg_trap $0
 	zparseopts -M -D - c:=c n=nonl P=print r=noesc T=ts
-	[[ -n $nonl ]] && args=('-n')
+	[[ -n $nonl ]] && _topts=('-n')
 	[[ -z $TTY || ! -c $TTY ]] && TTY=/dev/null # stdout
 	while [[ ${1[1]} == '-' ]]; do
-		args+=("$1")
+		if [[ $1 == '-' || $1 == '--' ]]; then
+			shift
+			break
+		fi
+		_topts+=("$1")
 		shift
 	done
 	if [[ -n $c ]]; then
-		local msg
 		c=$c[2]
 		if [[ $c == <1-> ]]; then
 			msg="\e[38;5;${c}m$@$C_"
@@ -31,14 +35,15 @@ function techo()
 	[[ -n $ts ]] && { print=1; ts='%D{%s.%.}>' }
 
 	if [[ -n $print ]]; then
-		print -P $noesc $args - $ts$msg >$TTY
+		print -P $noesc $_topts - $ts$msg >$TTY
 	else
-		echo -e ${noesc:+-E} $args - $ts$msg >$TTY
+		echo -e ${noesc:+-E} $_topts - $ts$msg >$TTY
 	fi
 }
 
 function cancel() {
 	local ret=$?
+	_dbg_trap $0
 	((ret != 130)) && throw $ret
 	abort 130 "$C[warn]Cancelled $@"
 }
@@ -48,6 +53,7 @@ function abort()
 {
 	local skipErrors noexception verbose print
 	integer cod=$1
+	_dbg_trap $0
 	zparseopts -D - E=skipErrors e=noexception v:=verbose -P=print
 	verbose=${verbose[2]:-2}
 	(($#)) && shift
@@ -89,23 +95,23 @@ function implode()
 
 function explode()
 {
-	local _var _str _sep uniq _list ifs _Asep stdin _tmp
-	zparseopts -D -M - v:=_var u=uniq A:=_Asep -stdin=stdin
+	local _var _str _sep uniq _list ifs _Asep stdin _tmp awk #@TODO awkWrapper...
+	zparseopts -D -M - v:=_var u=uniq A:=_Asep -stdin=stdin -awk:=awk
 
 	[[ -n $_var[2] ]] && _var=$_var[2]
-	[[ -n $3 && $3 != <1-> ]] && abort 1 "field specifier is not a number: \$3=$3"
 
 	if [[ -n $stdin ]]; then
 		_sep=${1:- }
 		#_str=()
 		while read -r _tmp; do
 			#_str+=($_tmp)
-			explode $_tmp $_sep $3
+			explode $_tmp $_sep $2
 		done
 		return
 	else
 		_str=$1
 		_sep=${2:- }
+		[[ -n $3 && $3 != <1-> ]] && abort 1 "field specifier is not a number: \$3=$3"
 	fi
 
 	_list=(${(@ps/$_sep/)_str})
@@ -151,7 +157,7 @@ function lib_set_info()
 
 function getmime()
 {
-	file -bi $(realpath "$@") | awk -F';' '{print $1}'
+	explode "$(file -bi $(realpath "$@"))" ';' 1
 	((pipestatus[1])) && fstack
 }
 
@@ -202,7 +208,7 @@ function isZshLib()
 function isScript()
 {
 	local mime=$(getmime "$*")
-	[[ $mime = 'text/x-shellscript' || $mime == 'text/plain' && $(read -e "$*") =~ VERSION=[0-9]+(\.[0-9]+)* ]]
+	[[ $mime = 'text/x-shellscript' || $mime == 'text/plain' && $(read -e <"$*") =~ VERSION=[0-9]+(\.[0-9]+)* ]]
 }
 
 function typeOf()
@@ -334,13 +340,13 @@ function include()
 			return 1
 		fi
 
-		if (($#lazyload)); then # @TODO
+		if (($#lazyload)); then
 			local llfuncs func
 			if (($#HEADER[lazyload])); then
 				# register a autoload function for each lazy load function
 				explode -v llfuncs ${HEADER[lazyload]} ','
 				for func in $llfuncs; do
-					functions[$func]="include $name && {
+					functions[$func]="include $quiet $name && {
 						$func \"\$@\"
 					}"
 				done
@@ -362,7 +368,6 @@ function include()
 			echo EOF >&p
 			(
 				#@TODO sort errors by file before opening files
-				set -x
 				while read -p tmp; do
 					split=(${(Q)${(z)tmp}})
 					file=$split[1]; line=$split[2]; error=$split[3]; error2=$split[4]
@@ -371,9 +376,9 @@ function include()
 					#@idea run this part only on current terminal, if there is one focused.
 				done
 				if type v 2>&1 >/dev/null; then
-					#v $file:$line &
+					techo v $file:$line
 				else
-					#${EDITOR:-vim} $file +$line &
+					${EDITOR:-vim} $file +$line
 				fi
 			)
 
@@ -423,30 +428,38 @@ function inst()
 	done
 }
 
+comp+=("aptinst=apt")
+function aptinst()
+{
+	sudo apt-get install -y $@
+}
+
+
 # Added 2019-09-05 00:57
 # check if any item of array equals value
 # in_array value array_name 
 function in_array()
 {
-	local name val _var ret i
+	local name val _var ret _i
 	zparseopts -D -M - v:=_var
 
 	case $(vartype $2) in
 	association*)
-		i=${(k)${(P)2}[(re)$1]}
+		_i=${(k)${(P)2}[(re)$1]}
+		[[ -n $_i ]] || return 1
 		;;
 	array*)
-		i=${${(P)2}[(rei)$1]}
+		_i=${${(P)2}[(rei)$1]}
+		((_i <= ${(P)#2})) || return 1
 		;;
 	*)
 		techo -c err "\"$2\": not an array."
+		print ${(P)2}
 		abort 2 "not an array"
 		return 2
 	esac
-
-	((i <= ${(P)#2})) || return 1
-
-	[[ -v $_var[2] ]] && typeset -g "$_var=$i"
+	
+	(($#_var)) && typeset -g "$_var[2]=$_i"
 	return 0
 }
 
@@ -477,13 +490,6 @@ function rtrim() {
 function trim()
 {
 	echo "$(rtrim "$(ltrim "$*")")"
-}
-#@TODO_in_array() { }
-
-comp+=("aptinst=apt")
-function aptinst()
-{
-	sudo apt-get install -y $@
 }
 
 # Added 2019-09-03 19:29
@@ -532,40 +538,47 @@ comp+=("do_sudo=sudo")
 function do_sudo()
 {
 	integer glob=1
-	local args user
+	local _sopts user cmd
 	
 	include -r functions
 	zparseopts -D -M - u:=user
 
-	args=(-H $user)
+	_sopts=(-H $user)
 	(($# == 0)) && 1=/bin/zsh
 	while (($#)); do
 		case $1 in
-			command|exec|-) shift
+			command|exec|-)
+				cmd=1; shift
 				break
-				;;
-			nocorrect) shift
-				;;
-			noglob) glob=0; shift
-				;;
+			;;
+			nocorrect)
+				shift 
+			;;
+			noglob)
+				glob=0; shift
+			;;
 			*) break
-				;;
+			;;
 		esac
 	done
 
 	if (($#)); then
-		if [[ $(typeOf $1) == 'alias' ]]; then
-			local tmp=$(inalias -f $1) || return 1
-			1=$tmp
+		if [[ $(typeOf -p $1) != (command|script)* ]]; then
+			abort 1 "$1: command not found"
 		fi
+		#if [[ $(typeOf $1) == 'alias' ]]; then
+		#	abort 1 "$1 is an alias"
+			#local tmp=$(inalias -f $1) || return 1
+			#1=$tmp
+		#fi
 	else
 		1=/bin/zsh
 	fi
 
 	if ((glob)); then
-		PATH="/sbin:/usr/sbin:/usr/local/sbin:$PATH" sudo $args $~==*
+		sudo $_sopts env "PATH=$PATH" $~==*
 	else
-		PATH="/sbin:/usr/sbin:/usr/local/sbin:$PATH" sudo $args $==*
+		sudo $_sopts env "PATH=$PATH" $==*
 	fi
 }
 
@@ -574,4 +587,3 @@ function heredoc()
 {
 	IFS='\n' read -r -d '' $1 || true
 }
-
