Stable

diff --git a/zsh_libs/zsh_aliases b/zsh_libs/zsh_aliases
--- a/zsh_libs/zsh_aliases
+++ b/zsh_libs/zsh_aliases
@@ -3,7 +3,7 @@ VERSION=1.0.5
 alias e=echo
 alias op="xdg-open"
 alias open="xdg-open"
-alias vmake="make SHELL='$$SHELL -x'"
+alias vmake="make SHELL='$SHELL -x'"
 alias web="cd gp3320/app/bcm-webconf ; . venv/bin/activate ; ./webconf.py &"
 alias sv="v -s"
 alias pytags="ctags -R --python-kinds=-i ."
@@ -22,9 +22,9 @@ function hg()
 {
 	local match fopt gopt ic range
 	zparseopts -D -E -K i=ic r:=range
-	[[ -n "$ic" ]] && gopt+=" -i"
+	[[ -n $ic ]] && gopt+=' -i'
 	gopt+=" $1"
-	[[ -n "$range" ]] && fopt="${range[2]}" || fopt="0"
+	[[ -n $range ]] && fopt=${range[2]} || fopt="0"
 	fc -li ${=fopt} | grep ${=gopt}
 }
 
@@ -36,14 +36,14 @@ function aptlist()
 
 function mkscript()
 {
-	local shell func name data data2 edit err_exists file isLib help
-	err_exists="exists but isn't a shell script."
-	zparseopts -D -K s:=shell f:=func n:=name e=edit || abort
+	local shell func name edit
+	local file isLib help line data data2 
+	zparseopts -D -K s:=shell f:=func n:=name e=edit
 	
 	data2="$@"
 	if [[ -n "$func[2]" ]]; then
 		func=$func[2]
-		if [[ "$(typeOf $func)" == 'func' ]]; then
+		if [[ "$(typeOf $func)" == 'function' ]]; then
 			techo -c warn "$func() already exists"
 			vw $func
 			return
@@ -53,6 +53,7 @@ function mkscript()
 	input -p "Function name" -v func
 	isLib=false
 	if [[ -n "$name" ]]; then
+		local err_exists="exists but isn't a shell script."
 		name=$name[2]
 		file=$(getpath $name)
         if [[ "$file" != "." ]]; then # full path given
@@ -68,6 +69,7 @@ function mkscript()
 			cmdtype=($(typeOf $name))
 			type=${cmdtype[1]}
 			file=${cmdtype[2]}
+			name=${name#zsh_*}
 			if [[ "$type" != "script" ]]; then
 				if [[ -f "$ZSH_LIBS/zsh_$name" ]]; then # is it a lib?
 					file="$ZSH_LIBS/zsh_$name"
@@ -75,6 +77,9 @@ function mkscript()
 				elif [[ "$type" != 'none' ]]; then
 					echo "$file $err_exists"
 					return 1
+				else
+					file="$ZSH_LIBS/zsh_$name"
+					isLib=true
 				fi
 			fi
 		fi
@@ -113,6 +118,7 @@ function mkscript()
     if [[ -n "$func" ]]; then
 		data+=$(zindent $func "$data2")
 	else
+		line=$(wc -l $file)
 		data+=$(zindent "$data2")
 	fi
 
@@ -124,7 +130,11 @@ function mkscript()
 
 	# edit
 	if [[ -n "$edit" || -z "$data2" ]] || confirm "Edit file"; then
-		[[ -n "$func" ]] && $isLib && edfunc $func || gvim -f $file
+		if [[ -n "$func" ]] && $isLib; then
+			edfunc $func
+		else
+			gvim -f $file
+		fi
 	fi
 }
 #function _stack()
@@ -156,45 +166,68 @@ function add_key()
 	chmod 700 ${base}/.ssh
 	chmod 600 ${base}/.ssh/authorized_keys
 }
+
+# finds command(s) in an alias
+function inalias()
+{
+	if [[ $(type -f $1) =~ "^$1 is an alias for (.*)$" ]]; then
+		local f m prefix=(run)
+		for m in $=match[1]; do
+			if [[ ${m:0:1} = [[:alpha:]] && $+functions[$m] -eq 1 ]] && ! in_array prefix $m; then
+				f=$m
+				break
+			fi
+		done
+		(($#f)) && echo $f
+		return
+	fi
+	return 1
+}
+
 function edalias()
 {
-	local line pat file var is
-	zparseopts -D -M l:=line
+	local linenum pat file var
+	zparseopts -D -M l:=linenum
 	[[ -n "$1" ]] || return 1
 	if [[ "$1" == '-f' ]]; then
 		shift
-		pat="(function )?$1\(\)"
-		line=${line[2]:-2}
+		pat="(function +)?$1\(\)"
+		linenum=${linenum[2]:-2}
 	else
-		pat="alias $1="
-		line=0
+		pat="alias +$1="
+		linenum=0
 	fi
 	file=${2:-~/.zsh_aliases}
-	var="$(egrep -n "^[[:space:]]*$pat" "$file")" || var="2:$file"
-	if [[ $? -eq 0 ]]; then
-		((line+=$(explode "$var" ':' 1)))
-		gvim -f $file +$line
-		echo "PPID=$PPID"
-		include $file
+	var=("${(@f)$(egrep -rHn "^([^#]* )?$pat" $file $fpath)}")
+	if (($#var)); then
+		local result line
+		typeset -a tmp
+		for result in $var; do
+			explode -v tmp "$result" ':'
+			file=$tmp[1]
+			((linenum+=$tmp[2]))
+			# @TODO
+		done
+		# echo "PPID=$PPID"
+		gvim -f $file +$linenum
+		isZshLib $file && include $file
 	else
-		techo -c err "Could not find \"$1\""
+		techo -c err "Could not find \"$1\" alias"
 	fi
 }
 
 function edfunc()
 {
 	local arg file
-	arg=($(type "$1"))
-	[[ $? -ne 0 ]] && return 1
+	arg=($(type $1)) || return 1
 	if [[ "${arg[4]}" == 'autoload' ]]; then
-		techo "autoload function todo: find not loaded autoload functions in fpath"
-		file="${arg[-1]}"
-		[[ -f "$file" ]] || {
-			typeset -a files=($(f -b "${j.,.)fpath}" "$1"))
-			file=$(chooser -p "Choose file" $files) || cancel
-		}
-	elif [[ "${arg[5]}" != 'function' ]]; then
-		abort 2 "$1 is not a function:\n\t$arg"
+		autoload +X $1 && edfunc $1
+		return
+	elif [[ $arg[5] != 'function' ]]; then
+		if [[ $arg[4] != 'alias' ]] || (( ! $#functions[$name] )); then
+			abort 2 "$1 is not a function:\n\t$arg"
+		fi
+		file=$functions_source[$name]
 	else
 		file="${arg[-1]}"
 	fi
@@ -203,13 +236,30 @@ function edfunc()
 comp+=("vw=exec")
 function vw()
 {
-	local array mime cpath name line
-	array=($(explode "$1" ':')) ; name=$array[1]; line=$array[2]
+	local array mime cpath name linenum
+	array=($(explode "$1" ':')) ; name=$array[1]; linenum=$array[2]
 	array=($(type -w "$name"))
 	case "${array[2]}" in
-		function) edfunc $name $line
+		function)
+			edfunc $name $linenum
 			;;
-		alias) edalias $name $line
+		alias)
+			local func
+			if (( $#functions[$name] )); then # also a function exists
+				local opt
+				(( $#linenum )) && { edfunc $name $linenum ; return }
+				func=$name
+			else
+				if [[ $(type -f $name) =~ "^$name is an alias for (.*)$" ]]; then
+					func=$(inalias $match[1])
+				fi
+			fi
+
+			if (($#func)); then
+				opt=$(chooser -f1 "alias $name" "function $func()") || cancel
+				[[ $opt == 'function' ]] && { edfunc $func $linenum ; return }
+			fi
+			edalias $name $linenum
 			;;
 		command)
 			cpath=$(which "$name")
@@ -219,14 +269,15 @@ function vw()
 					echo "$tpath is binary executable"
 					return 1
 				fi
-				gvim $cpath ${line:++$line}
+				gvim $cpath ${linenum:++$linenum}
 			else
 				echo Invalid path \"$cpath\"
 			fi
 			;;
 	esac
 }
-# call vim to each file:line argument
+
+# call vim to each file:linenum argument
 # file1:l4 file2:l66 
 function v()
 {
@@ -241,9 +292,9 @@ function v()
 	fi
 	for arg; do
 		if [[ "$arg" =~ ":" ]]; then
-			line=+$(echo $arg | cut -d: -f2)
+			linenum=+$(echo $arg | cut -d: -f2)
 			file=$(echo $arg | cut -d: -f1)
-			$sudo gvim $opt $line $file
+			$sudo gvim $opt $linenum $file
 		else
 			$sudo gvim $opt $arg
 		fi
@@ -254,11 +305,11 @@ function finderror()
 {
 	errline=`tail /var/log/apache2/error.log |  grep -e "PHP \(Parse\|Fatal\|Notice\)" | tail -n1`
 	str=`echo $errline| sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'`
-	line=`echo $str | sed 's/.*line \([0-9]*\).*$/\1/'`
+	linenum=`echo $str | sed 's/.*line \([0-9]*\).*$/\1/'`
 	filename=`echo $str | sed 's/.*\(\/media\/sparc\/xdata\/[^ ]*\).*$/\1/'`
 	echo $filename
-	echo $line
-	v --remote-tab-silent "$filename:$line"
+	echo $linenum
+	v --remote-tab-silent "$filename:$linenum"
 }
 function cptree()
 {
@@ -527,7 +578,6 @@ function find_dupes()
 #	dupes=(find . ! -empty -type f -exec md5sum {} + | sort -k1 | uniq -w32 -D --all-repeated=separate)
 	#getpath $(printf "%s\n" "$string1" "$string2" | sed -e 'N;s/^\(.*\).*\n\1.*$/\1/'
 }
-
 
 # Added 2019-03-30 20:31
 function lastarg()
diff --git a/zsh_libs/zsh_functions b/zsh_libs/zsh_functions
--- a/zsh_libs/zsh_functions
+++ b/zsh_libs/zsh_functions
@@ -1,4 +1,5 @@
-VERSION=1.0.5
+VERSION=1.0.7
+#lazyload=run,input,chooser,confirm,todo 
 
 #@TODO check i it's the top shell, and i it is, don't exit, just return: [[ $- =~ m ]] || EXIT=1
 #		echo $ZSH_EVAL_CONTEXT
@@ -40,30 +41,56 @@ OK=" [${C[ok]}OK$C_]"
 
 function input()
 {
-	local var str p gui z colors args title
-	zparseopts -M -D - p:=p v:=var g=gui z=z t:=title
+	local _var str p gui z c colors args title raw _buttons
+	zparseopts -M -D - c:=c p:=p v:=_var g=gui z=z t:=title r=raw \
+		b:=_buttons -buttons:=b
+
+	typeset -A buttons=(Cancel 1 Ok 0)
+	if (($#_buttons)); then
+		explode -A':' -v _buttons $_buttons[2] ','
+		buttons+=(${(kv)_buttons})
+	fi
+
 	colors=(-fg white -bg black)
 	p=${p[2]:-Input text}
 	title=${title[2]:-Input text}
-	if [[ -n "${var[2]}" ]]; then
-		var="${var[2]}"
-		[[ -v $var ]] || typeset -g $var
-	fi
-	str=${@:-${(P)var}}
-	techo -n -c head "$p: "
-	if [[ -n $z ]] && type zenity>/dev/null; then
-		str=$(zenity -title "$title" --entry --text="$p" --entry-text="$str") || cancel
-		techo -c warn $str
-	elif type gxmessage >/dev/null; then
-		args=($colors -center -ontop -wrap -buttons Cancel:1,Ok:0)
-		str=$(gxmessage $args -title "$title" -entrytext "$str" "$p") || cancel
-		techo -c warn $str
+	if [[ -n $_var[2] ]]; then
+		_var=$_var[2]
+		typeset -g $_var
+		str=${@:-${(P)_var}}
 	else
-		vared str || read -r str || cancel
+		str="$@"
 	fi
 
-	if [[ -n $var ]]; then
-		${(P)var::=$str}
+	[[ ${p: -1} != ' ' ]] && techo -n -c ${c[2]:-head} "$p$C_: " || techo -n $c $p 
+
+	if [[ -n $z ]] && type zenity>/dev/null; then
+		str=$(zenity -title "$title" --entry --text="$p" --entry-text="$str") || cancel
+		(($#str)) && techo -c warn $str
+	elif type gxmessage >/dev/null && [[ -z $raw ]]; then
+		args=($colors -center -ontop -wrap -buttons "$(implode -A':' buttons ',')")
+		str=$(gxmessage $args -title "$title" -entrytext "$str" "$p")
+		ret=$?
+		in_array $ret buttons || cancel
+		str=$buttons[(ie)$ret] #@TODO
+		(($#str)) && techo -c warn $str
+	else
+		if [[ -o zle ]]; then
+			techo # newline, because vared clears the line
+			vared -e str
+		else
+			read -r str
+		fi
+		ret=$?
+		if ((ret)); then
+			((ret == 130)) && cancel || return 1
+		fi
+	fi
+	
+	(($#str)) || return 10
+	
+	if [[ -n $_var ]]; then
+		typeset -g "$_var=$str"
 	else
 		echo $str
 	fi
@@ -91,69 +118,98 @@ function confirm()
 	return $ret
 }
 
-# Receive a list and the default selected item.
-# Put the default item on the first position.
-# @param string selected
-# @param string[] list
-function mklist()
-{
-	local list first i
-	first=$1
-	list=($1)
-	shift
-	for i; do [[ "$i" != "$first" ]] && list+=($i) ; done
-	echo "${list[@]}"
-}
-
 function chooser()
 {
-	local noSelect chosen ret sep field search default
-	zparseopts -M -D - c=color p:=print n:=noSelect R:=regex s:=sep f:=field \
-		S:=search D:=default
+	local noSelect sep field bytes search default
+	local list ifs var chosen chosenList selectors events
 
-	if [ $# -gt 1 ]; then
-		local args
-		chosen=$(
-			NLIST_SET_SEARCH_TO=$search[2] \
-			ZSHSELECT_START_IN_SEARCH_MODE=$+search \
-			ZSHSELECT_NONSELECTABLE=$noSelect[2] \
-			zsh-select $default $@
-		)
-		#(($#search[2])) && args+=(NLIST_SET_SEARCH_TO=$search[2])
-		#(($#noSelect[2])) && args+=(ZSHSELECT_NONSELECTABLE=$noSelect[2])
-		#(($#search[2])) && args+=(NLIST_SET_SEARCH_TO=$search[2])
-		#chosen=$($args ZSHSELECT_START_IN_SEARCH_MODE=$+search zsh-select $@)
-		ret=$?
-	else
-		chosen="$1"
+	selectors=(${${(@uM)@#-[bfsR]}#-}) # keep options order
+
+	zparseopts -D -M - c=color p:=print n:=noSelect R:=regex S:=search \
+		 v:=var d:=default s:=sep f:=field -ifs:=ifs b:=bytes E:=events
+
+	if (($#sep || $#field)); then
+		(($#sep && $#field)) && unset 'selectors[(I)[sf]]'
+		field=${field[2]:-1}
+		sep=${sep[2]:- }
 	fi
-	[[ $#chosen -gt 0 ]] || return $ret
-	if [[ -n $regex ]]; then
-		if [[ $chosen =~ $regex[2] ]]; then
-			echo "$match[@]"
-			return 0
-		fi
-	elif [[ -n $sep ]]; then
-		echo $(explode "$chosen" $sep[2] $field[2])
-		return 0
+
+	if [[ -n $ifs ]]; then
+		explode -v list "$*" $ifs[2]
 	else
-		echo "$chosen"
-		return 0
+		list=("$@")
 	fi
-	return 1
+
+	if (($#list > 1)); then
+		{
+			[[ -n $default[2] ]] && default=($default[2])
+			explode -v chosenList "$(
+				NLIST_SET_SEARCH_TO=$search[2] \
+				ZSHSELECT_START_IN_SEARCH_MODE=$+search[2] \
+				ZSHSELECT_NONSELECTABLE=$noSelect[2] \
+				ZSHSELECT_ENABLE_EVENTS=$events[2] \
+				zsh-select $default "${(@)list:|default}" || throw $?
+			)" $'\n'
+		} always {
+			if catch '*'; then
+				return $CAUGHT
+			fi
+		}
+	else
+		chosenList=($list)
+	fi
+
+	(($#chosenList)) || return 10
+
+	list=()
+	for chosen in $chosenList; do
+		local opt
+
+		for opt in $selectors; do
+			case $opt in
+			R)
+				if [[ $chosen =~ $regex[2] ]]; then
+					chosen=$match
+				else
+					continue
+				fi
+			;;
+			b)
+				#chosen=$(echo - $chosen | cut $bytes)
+				typeset -l "chosen=${chosen:bytes[1,]}"
+			;;
+			s|f)
+				explode -v chosen $chosen $sep $field
+			;;
+			esac
+		done
+		list+=($chosen)
+	done
+
+	if (($#var)); then
+		set -A "$var[2]" $list
+	else
+		print -r $list
+	fi
+
+	#[[ ! -t 1 || -z $var ]] && print -r $list
+	return 0
 }
 
 function chkCmdInstall()
 {
-	local deb ret
-		# techo -c err "$cmd command not found"
 	if ! command -v $1 >/dev/null; then
-		[ -n "$2" ] && deb=$2 || deb=$1
-		techo "Installing $deb (provides $cmd)"
-		sudo apt install $deb
-		ret=$?
-		[ $ret -ne 0 ] && techo -c err "Error installing $deb"
-		return $ret
+		local deb ret tmp
+		techo -c lred "$1$C_: command not found. $C[warn]Searching for package to install."
+		[[ -n $2 ]] && deb=$2 || {
+			chooser -v deb -s':' -f1 --ifs=$'\n' "$(dpkg -S '*/'$1)" || return 127
+		}
+		techo "Installing $C[lcyan]$deb (provides $C[lcyan]$1)"
+		sudo apt install $deb || {
+			ret=$?
+			techo -c err "Error installing $deb"
+			return $ret
+		}
 	fi
 }
 
@@ -164,12 +220,13 @@ function alert()
 		icon="error"
 		title="Error"
 		shift
-		[ -z "$NOSND" ] && sndplay error || vflash
+		((!NOSND)) && sndplay error
 	else
 		icon="trophy-gold"
 		title="Success"
-		[ -z "$NOSND" ] && sndplay success || vflash
+		((!NOSND)) && sndplay success
 	fi
+	vflash
 	notify-send --icon=$icon "$title" "$*"
 }
 
@@ -185,29 +242,6 @@ function sndplay()
 	run -I libsox-fmt-mp3 - shuf -ezn 1 $dir/* | xargs -0 -n1 play
 }
 
-# Say the file, line number and optional message for debugging
-# Inspired by bash's `caller` builtin
-# Thanks to https://unix.stackexchange.com/a/453153/143394
-function yelp()
-{
-	# shellcheck disable=SC2154  # undeclared zsh variables in bash
-	if [ -n "$BASH_VERSION" ]; then
-		local file=${BASH_SOURCE[1]} func=${FUNCNAME[1]} line=${BASH_LINENO[0]}
-	else  # zsh
-		emulate -L zsh  # because we may be sourced by zsh `emulate bash -c`
-		# $funcfiletrace has format:  file:line
-		#local file=${funcfiletrace[1]%:*} line=${funcfiletrace[1]##*:}
-		#local func=${funcstack[2]}
-		#[[ "$func" =~ '/' ]] && func=source  # $func may be filename. Use bash behaviour
-		# techo "${file##*/}:$func:$line $*"
-		#print -l -- funcfiletrace $funcfiletrace - funcsourcetrace $funcsourcetrace - funcstack $funcstack - functrace $functrace
-		local integer n=$#functrace i=${1:-0}
-		[[ $functrace[$n] = $SHELL:* ]] && ((n--))
-		for ((i++; i<=n; i++)); do
-			techo -c warn $functrace[$i] $_C in $C[lgray]$funcfiletrace[$i]
-		done
-	fi
-}
 [ -z "$BASH" ] || return
 function array_dump()
 {
@@ -219,7 +253,7 @@ function array_dump()
 		done
 	elif [[ $(vartype "$1") = array* ]]; then
 		techo -c head "dump of \"$1\" (size: ${(P)#1}):"
-		for val in "${(P@)1}"; do
+		for val in "${(qP@)1}"; do
 			techo "${(qqq)val}"
 		done
 	else
@@ -273,139 +307,130 @@ function run_end()
 # 4: Above, plus finishing message
 # 5: Above, plus associated command
 # 6: Above, plus full command with arguments
+comp+=('run=which')
 function run()
 {
-	local ret cmd fullcmd logfile watch
+	local ret cmd fullcmd logfile watch cmdPrefix
 	local sudo trysudo dryrun verbose color alert print
-	local cmdinst workdir skipErrors okcodes
+	local cmdinst workdir skipErrors okcodes debug
 
-	if [[ "${1:0:1}" == - ]]; then
+	if [[ ${1:0:1} == - ]]; then
 		zparseopts -M -D - v:=verbose c:=color a=alert p:=print \
 			s=sudo S=trysudo n=dryrun I:=cmdinst -cd:=workdir E=skipErrors \
-			l:=logfile w:=watch N:=okcodes -ok-exit-codes:=N
+			l:=logfile w:=watch N:=okcodes -ok-exit-codes:=N D:=debug
 
-		[[ "$1" == - ]] && shift
-		[[ ${1:0:1} == - ]] && { abort 1 "Invalid command: $1"; return }
+		[[ $1 == - ]] && shift
+		[[ ${1:0:1} == - ]] && { abort 2 "Invalid command: $1"; return }
 	fi
 	verbose=${verbose[2]:-6}
 
 	cmd=$1
-	if [[ -n "$sudo" ]]; then
+	if [[ -n $sudo ]]; then
 		fullcmd=(sudo "$@")
 		trysudo=
 	else
 		fullcmd=("$@")
 	fi
 
-	if [[ -z "$color" ]]; then
+	if [[ -z $color ]]; then
 		color=(-c head)
-	elif [[ "$color" = 'none' ]]; then
+	elif [[ $color == 'none' ]]; then
 		color=''
 	fi
 	[[ -n $print ]] && print=$print[2]
-	if [[ $verbose -ge 3 ]] || [[ $verbose -ge 2 && -n $print ]] ; then
-		if [[ $verbose -ge 6 ]]; then
+	if ((verbose>=3)) || [[ $verbose -ge 2 && -n $print ]] ; then
+		if ((verbose>=6)); then
 			[[ -n $print ]] && techo $color $print
 			techo $color $fullcmd
 		elif [[ -n $print ]]; then
-			[[ $verbose -ge 5 ]] && techo $color "$print ($cmd)" || techo $color $print
+			((verbose>=5)) && techo $color "$print ($cmd)" || techo $color $print
 		else
 			techo $color $cmd
 		fi
 	fi
-	[[ -n "$print" ]] && print="$print : $cmd" || print=$cmd
+
+	[[ -n $print ]] && print="$print : $cmd" || print=$cmd
+
 	{
 		[[ -n $dryrun ]] && return 0
 
 		if [[ -n $workdir ]]; then
 			workdir=$workdir[2]
 			if [[ ! -d $workdir ]]; then
-				confirm "$workdir does not exist. Create" && mkdir "$workdir" || throw $?
+				confirm "$workdir does not exist. Create" && mkdir $workdir || throw $?
 			fi
-			cd "$workdir" || throw $?
+			cd $workdir || throw $?
 		fi
+
 		if [[ -z $okcodes ]]; then
 			okcodes=(0)
 		else
-			explode -v okcodes "$okcodes[2]" ','
+			explode -v okcodes $okcodes[2] ','
 			in_array okcodes 0 || okcodes+=(0)  # add 0 to successful exit codes
 		fi
 
+		(($#debug)) && DEBUG=$debug[2]
+		if ((DEBUG)); then
+			(($#watch)) && _dbg_funcOnOff $watch[2]
+			cmdPrefix='debug'
+		elif (($#color)); then
+			cmdPrefix='color'
+		fi
 		# # # # # # # # # #
 		# Execute command #
 		# # # # # # # # # #
-		if [[ -n "$color" ]]; then
+		#waitPid -c "dirtyMem -P" color $fullcmd
+		while ((1)); do
 			if [[ -n $watch ]]; then
-				waitPid -c "dirtyMem -P" color $fullcmd
-				color $fullcmd
+				$cmdPrefix $fullcmd & waitPid -c $watch[2] $!
 			else
-				color $fullcmd
+				$cmdPrefix $fullcmd
 			fi
-		else
-			if [[ -n $watch ]]; then
-				waitPid -c "dirtyMem -P" $fullcmd
-			else
-				$fullcmd
-			fi
-		fi
-		ret=$?
-
-		if [[ -n $DEBUG ]]; then
-			typeset -tf $cmd || set -x
-		fi
-		[[ $ret -eq 130 ]] && throw $ret
-		if [[ $ret -eq 127 ]]; then
-			chkCmdInstall $cmd $cmdinst[2]
 			ret=$?
-			if [[ $ret -eq 0 ]]; then
-				if [[ -n "$color" ]]; then
-					color $fullcmd
-				else
-					$fullcmd
-				fi
-				ret=$?
-			fi
-		fi
-		if [[ -n $DEBUG ]]; then
-			typeset +tf $cmd || set +x
-			return $ret
-		fi
 
-		if ! in_array okcodes $ret; then #TODO
-			if [[ -n "$trysudo" ]]; then
+			((ret==130)) && throw $ret
+			if ((ret==127)); then
+				chkCmdInstall $cmd $cmdinst[2] && continue || throw 127
+			fi
+
+			break
+		done
+
+		if ! in_array okcodes $ret; then
+			if [[ -n $trysudo ]]; then
 				techo "Trying with sudo"
-				color sudo $fullcmd
+				sudo $fullcmd
 				ret=$?
 			fi
 			in_array okcodes $ret || throw $ret
 		fi
 	} always {
+		if ((DEBUG)); then
+			(($#watch)) && _dbg_funcOnOff $watch[2] 0
+			#{ typeset +Ttf $cmd || set +x }
+		fi
 		if catch '*'; then
 			local data=(${=CAUGHT})
 			ret=$data[1]
-			if [[ $ret -eq 130 ]]; then
+			if ((ret==130)); then
 				cancel $verbose "$print $CANCEL"
 				return
 			fi
-			[[ $verbose -ge 1 ]] && techo "$print $FAIL ($data)"
-			[[ -n "$alert" ]] && error "$print error: $data"
+			((verbose)) && techo "$print $FAIL ($data)"
+			[[ -n $alert ]] && error "$print error: $data"
 			abort $skipErrors $ret
 			return
 		fi
 	}
 
-	case $ret in
-	0)
-		[[ $verbose -ge 4 ]] && techo "$cmd $OK"
-		[[ -n "$alert" ]] && success "$cmd finished successfully."
-	;;
-	*)
-		[[ $verbose -ge 1  ]] && techo "$print $FAIL"
-		[[ -n "$alert" ]] && error "$print error: ret=$ret"
+	if in_array okcodes $ret; then
+		((verbose>=4)) && techo "$cmd $OK"
+		[[ -n $alert ]] && success "$cmd finished successfully."
+	else
+		((verbose)) && techo "$print $FAIL"
+		[[ -n $alert ]] && error "$print error: ret=$ret"
 		abort $skipErrors $ret
-	;;
-	esac
-
+	fi
 	return $ret
 }
 
@@ -469,7 +494,7 @@ function color()
 function colorify()
 {
 	local line data debug
-	zparseopts -D -M - d:=debug
+	zparseopts -D -M - D:=debug
 	#@broken: [ ! -p /dev/stdin ] && exit 0
 	if [ "$1" = '-all' ] || [ "$1" = '-c' ]; then
 		if [ "$1" = '-all' ]; then
@@ -493,13 +518,14 @@ function colorify()
 		local a cmd
 		if [[ -n $debug ]]; then
 			cmd=$debug[2]
+			# @TODO dbg_ps
 			while read line; do
-				if [[ $line =~ ^\\+$cmd:([0-9]+)\>\ (.*) ]]; then
-					techo -c lcyan $cmd:$match[1] ${_C}$match[2]
-				elif [[ $line =~ ^\\+([[:alnum:]]+):([0-9]+)\>\ (.*) ]]; then
-					techo -c blue $match[1]:$match[2] ${_C}$match[3]
+				if [[ $line =~ ^\\+([0-9]?)\<?$cmd:([0-9]+)\>\ (.*) ]]; then
+					techo -c lcyan $cmd:$match[2] ${_C}$match[3]
+				elif [[ $line =~ ^\\+([0-9]?)\<?([[:alnum:]]+):([0-9]+)\>\ (.*) ]]; then
+					((DEBUG)) && techo -c blue $match[1]:$match[2] ${_C}$match[3]
 				else
-					techo $line
+					techo -c lred $line
 				fi
 			done
 		else
@@ -546,20 +572,18 @@ function refactor()
 	find $dir -type f -name '*.php' -print0 | xargs -0 sed -ised "s/$search/$replace/g"
 }
 
-alias q=queue
+alias q=todo
 # Added 2019-06-04 17:47
-function queue()
+function todo()
 {
-	local qid qFilter cmd queue queues dir baseDir=$CFG e="q"
-	zparseopts -D -M - d:=dir -dir:=d
-	if [[ $# -eq 0 ]]; then
+	local id filter cmd todo todos
+	local box dir glob data baseDir=$CFG e='todo'
+	zparseopts -D -M - d:=dir -dir:=d f:=filter
+	if (( ! $# )); then
 		cmd='show'
 	else
 		cmd=$1; shift
-		if [[ -n $1 ]]; then
-			qFilter=$1
-			shift
-		fi
+		data=$*
 	fi
 	if [[ $#dir[2] -ne 0 ]]; then
 		dir=$dir[2]
@@ -567,42 +591,60 @@ function queue()
 		dir=$baseDir
 	fi
 	[[ -d $dir ]] || abort 127 "\"$dir\": directory not found"
-	[[ -z $qFilter ]] && qFilter="*.$e"
+	[[ -z $filter ]] && filter='*'
 
 	include file
+	#glob=$dir/$filter.$e
+	glob="$dir/*.$e"
+	todos=($~glob(-N))
 	case $cmd in
-		add)
-			#queues=($dir/$~qFilter(-N))
-			queues=($dir/*(-N))
-			queue=$(chooser -S $qFilter $queues:t "New queue" "Browse full path") || cancel
-			if [[ "$queue" == "New queue" ]]; then
-				queue=$(input -p "Enter queue id") || cancel
-				[[ ${queue:0:1} != / ]] && queue=$dir/$queue
-				[[ ${queue: -2} != ".$e" ]] && queue=$queue.$e
-			elif [[ "$queue" == "Browse full path" ]]; then
-				queue=$(chooser --file -p "Choose path of queue") || cancel
-				[[ ${queue:0:1} != / ]] && queue=$dir/$queue
-				#dir=$(getfilename $queue)
-			fi
-			qid=$(noext $(getfilename $queue) $e)
-			input -p "Adding to $qid" "$@" >> $queue || cancel
-			;;
-		show)
-			for queue in $dir/$~qFilter(-N); do
-				qid=$(noext $(getfilename $queue) $e)
-				run -p "Queue: $qid" show $queue
-			done
-			;;
-		*)
-			techo -c err "$cmd: invalid command"
-			usage
+	add)
+		todo=$(chooser -S $filter $todos:t "New todo" "Browse full path") || cancel
+		if [[ "$todo" == "New todo" ]]; then
+			todo=$(input -p "Enter todo id") || cancel
+			[[ ${todo:0:1} != / ]] && todo=$dir/$todo
+			[[ $(getext $todo) == $e ]] || todo=$todo.$e
+		elif [[ "$todo" == "Browse full path" ]]; then
+			todo=$(chooser --file -p "Choose path of todo") || cancel
+			[[ ${todo:0:1} != / ]] && todo=$dir/$todo
+			# @todo
+			#dir=$(getfilename $todo)
+		fi
+		id=$(noext $(getfilename $todo) $e)
+		input -p "Adding to todo $id" "$data" || cancel
+		;;
+	show)
+		(($#todos)) || return 0
+		todo=$(chooser -S $filter $todos:t) || cancel
+		id=$(noext $(getfilename $todo) $e)
+		run -p "Todo: $id" show $todo
+		#for todo in $~glob(-N); do
+		#	id=$(noext $(getfilename $todo) $e)
+		#	run -p "Todo: $id" show $todo
+		#done
+		sqlite3 -batch test.db
+		;;
+	*)
+		techo -c err "$cmd: invalid command"
+		usage
 	esac
 
 	function usage() {
-		techo -c warn "$0 [--dir/-d path] <add|show> [searchFilter]\n\
-			default filter: *.q\n\
-			default dir: $baseDir"
+		local opts=(
+			dir	 d "path(default: $baseDir)" 'base directory'
+			help h ''						 'help'
+		)
+		techo "$0 [options] [add|show] [filter]"
+		opts $opts
 	}
+}
+
+function opts()
+{
+	local long opt desc arg 
+	for long opt arg desc; do
+		print -ca -C 4 -- --$long -$opt $arg $desc
+	done
 }
 
 # Added 2019-09-20 15:55
@@ -619,3 +661,8 @@ function pizza()
 	done ; alert "pizza time" } &
 }
 
+# Added 2019-10-23 21:53
+function kcmd()
+{
+	qdbus $KONSOLE_DBUS_SERVICE $KONSOLE_DBUS_SESSION "$@"
+}
diff --git a/zsh_libs/zsh_main b/zsh_libs/zsh_main
--- a/zsh_libs/zsh_main
+++ b/zsh_libs/zsh_main
@@ -1,112 +1,116 @@
-VERSION=1.0.7
-[[ "$SUDO_USER" != "" ]] && export HOME=~$SUDO_USER
-export PATH=$PATH:$HOME/bin
-export NOSND=1
-[[ -z "$ZSH_LIBS" ]] && export ZSH_LIBS=${$(realpath $0):h}
+VERSION=1.0.8
 [[ -v comp ]] || typeset -g -a comp
 
-function techo() {
-	local c args nonl
-	zparseopts -M -D - c:=c n=nonl
+function techo()
+{
+	local c args nonl print
+	zparseopts -M -D - c:=c n=nonl P=print
 	[[ -n "$nonl" ]] && args=('-n')
 	[[ -z $TTY || ! -c $TTY ]] && TTY=/dev/null # stdout
-	if [[ -n "$c" ]]; then
-		c="${c[2]}"
-		[ -z "${C[$c]}" ] && type colorSet >/dev/null && colorSet $c
-		while [[ ${1[1]} = '-' ]]; do
-			args+=("$1")
-			shift
-		done
-		echo -e $args "${C[$c]}${@}$C_" >$TTY
+	while [[ ${1[1]} = '-' ]]; do
+		args+=("$1")
+		shift
+	done
+	if [[ -n $c ]]; then
+		local msg
+		c=$c[2]
+		if [[ $c = [0-9]## ]]; then
+			msg="\e[38;5;${c}m$@$C_"
+		else
+			[[ -v C[$c] ]] && type colorSet >/dev/null && colorSet $c
+			msg="${C[$c]}${@}$C_"
+		fi
+		if [[ -n $print ]]; then
+			print -P $args $msg >$TTY
+		else
+			echo -e $args $msg >$TTY
+		fi
+	elif [[ -n "$print" ]]; then
+		print -P $args "$@" >$TTY
 	else
 		echo -e $args "$@" >$TTY
 	fi
 }
 
-function cancel() { abort 130 "Cancelled $@" }
+function cancel() {
+	local ret=$?
+	((ret != 130)) && throw $ret
+	abort 130 "$C[warn]Cancelled $@"
+}
 
-function abort() {
-	local cod=$1 skipErrors noexception verbose
-	zparseopts -D - E=skipErrors e=noexception v:=verbose
+# @TODO skipErrors 
+function abort()
+{
+	local skipErrors noexception verbose print
+	integer cod=$1
+	zparseopts -D - E=skipErrors e=noexception v:=verbose -P=print
 	verbose=${verbose[2]:-2}
-	[[ $# -ge 1 ]] && shift
-	yelp 1
-	[[ $# -ge 1 && $verbose -gt 0 ]] && techo -c lred "$@"
-	[[ -n $nostop ]] && return $cod
-	[[ "$ABORT" -gt 0 ]] && $ABORT $cod "$@" 
-	{ [ -z "$EXIT" ] || [ $EXIT -gt 0 ] } && [[ ! -o interactive ]] && exit $cod
+	(($#)) && shift
+	((verbose>2 || DEBUG)) && fstack 1
+	(($# && verbose)) && techo -c lred "$@"
+	[[ -n $ABORT ]] && $ABORT $cod "$@" 
+
+	#@TODO $ZSH_EVAL_CONTEXT =~ toplevel* , does not seem to work
+	((EXIT)) && [[ ! -o interactive ]] && exit $cod
+
 	[[ -z $noexception ]] && throw $cod
 	return $cod
 }
 
-function _test()
+function implode()
 {
-	local f="$1" test_f l
-	[[ $# -eq 0 ]] && abort 1 "Missing argument"
-	test_f="_test_$f"
-	type $test_f || abort 127 "Function \"$test_f\" not found"
-	$test_f && techo "$f $OK" || {
-		techo "$f $FAIL $?"
-		#yelp 3
-	}
+	local _var _str _sep uniq _list ifs _Asep
+	zparseopts -D -M - v:=_var u=uniq -ifs:=ifs A:=_Asep
+
+	[[ -n $2 ]] && _sep=$2 || _sep=' '
+	if [[ -n $_Asep ]]; then
+		_Asep=$_Asep[2]
+	else
+		[[ $_sep != ':' ]] && _Asep=':' || _Asep=';'
+	fi
+	_list=()
+	for key in ${(Pk)1}; do
+		_list+=($key$_Asep${${(P)1}[$key]})
+	done
+	echo -n ${(@pj/$_sep/)_list}
 }
 
-function _test_explode()
-{
-	local f='explode' a=()
-	$f 'a;b' ';'
-	[[ ${a[1]} = 'a' && ${a[2]} = 'b' ]] || return $LINENO
-	a=($($f 'a  b ;; b' ';'))
-	[[ ${a[1]} = 'a  b ' && -z ${a[2]} && ${a[3]} = ' b' ]] || return $LINENO
-	a=($($f 'a  b ;; b' ' '))
-	[[ -n $a && ${a[1]} = 'a' && ${a[2]} = 'b' && ${a[3]} = ';;' && ${a[4]} = 'b' ]] || return $LINENO
-	return true
-}
 function explode()
 {
-	local _var str _sep uniq
-	zparseopts -D -M - v:=_var u=uniq
+	local _var _str _sep uniq _list ifs _Asep
+	zparseopts -D -M - v:=_var u=uniq -ifs:=ifs A:=_Asep
 	_sep=${2:- }
-	if [[ "$_sep" != ' ' ]]; then
-		str=${(q)1}
-	else
-		str=$1
-	fi
-	str=(${(@zps/$_sep/)str})
-	if [[ -n $uniq ]]; then
-		str=("${(@uz)str}")
-	fi
-	[[ -n "${_var[2]}" ]] && _var=${_var[2]}
-	if [[ -n "$3" ]]; then
-		[[ "$3" = [0-9]## ]] || abort 1 "\$3=$3: not a number"
+	[ -t 0 ] && _str=$1 || read _str
+	#[[ $_sep != ' ' ]] && _str=${_str// /$'\\ '}          #_str=${_str// /$'\\ '}
+	_list=(${(@ps/$_sep/)_str})
+	[[ -n $uniq ]] && _list=(${(@u)_list})
+	[[ -n $_var[2] ]] && _var=$_var[2]
+	if [[ -n $3 ]]; then
+		[[ $3 == [0-9]## ]] || abort 1 "\$3=$3: not a number"
 		if [[ -n $_var ]]; then
-			[[ -v $_var ]] || typeset -g $_var
-			eval $_var="'${(Q)str[$3]}'"
+			typeset -g $_var
+			#eval $_var="'${(Q)_str[$3]}'"
+			eval $_var="'${_list[$3]}'"
+			#echo ${(Q)_str[$3]}
 		else
-			echo "${(Q)str[$3]}"
+			print -r $_list[$3]
 		fi
+		#[ ! -t 1 ] && echo $_str[$3]
 	else
 		if [[ -n $_var ]]; then
-			_var=${_var:-reply}
-			[[ -v $_var ]] || typeset -ga $_var
-			set -A $_var ${(Q)str}
+			if [[ -n $_Asep ]]; then
+				typeset -gA $_var
+				_Asep=$_Asep[2]
+				set -A $_var ${(@ps/$Asep/)_list}
+			else 
+				typeset -ga $_var
+				set -A $_var $_list
+			fi
 		else
-			echo $str
+			print -r $_list
 		fi
+		#[ ! -t 1 ] && echo $_list
 	fi
-}
-
-function debug()
-{
-	local _cmd _data _type keep
-	zparseopts -D -M - k=keep
-	_cmd="$1" ; shift
-	_type="$(typeOf "$_cmd")"
-	[[ "$_type" == 'function' ]] && typeset -tf $_cmd #|| set -x
-	#_data=$($_cmd "$@" 2>&1 | egrep "^\+$_cmd:|[^+]")
-	_data=$($_cmd "$@" 2>&1)
-	[[ -z $keep && "$_type" == 'function' ]] && typeset +tf $_cmd #|| set +x
-	[[ $#_data -gt 0 ]] && colorify -d $_cmd <<<$_data
 }
 
 function vartype() {
@@ -116,51 +120,93 @@ function vartype() {
 # Set info for a lib
 function lib_set_info()
 {
-	local name=${(U)1} info
+	local name info
+	integer ll=$6 err
+	if [[ $1 == '-E' ]]; then
+		err=1
+		shift
+	fi
+	name=${(U)1}
 	typeset -Ag ZSH_${name}_INFO
-	set -A ZSH_${name}_INFO ver $2 path "$3" required $4 mtime "$5"
+	set -A ZSH_${name}_INFO ver $2 path "$3" required $4 mtime "$5" lazyload $ll err $err
 }
 
 function getmime()
 {
 	file -bi $(realpath "$@") | awk -F';' '{print $1}'
+	((pipestatus[1])) && fstack
+}
+
+function zshLibReadHeader()
+{
+	local mime=$(getmime "$*") version header
+	typeset -gA HEADER=()
+	{ read version ; read header } < "$*" || return
+	if [[ $mime = 'text/plain' && $version =~ VERSION=([0-9\.]+) ]]; then
+		VERSION=$match[1]
+		if [[ $header =~ ^\#(([[:alnum:]]+)(=([^[:blank:]]+))?)([[:blank:]]+([[:alnum:]]+)(=([^[:blank:]]+))?)*$ ]]
+		then
+			local opt val nop
+			for nop opt nop val in $match; do
+				case $opt in
+					lazyload)
+						;;
+					*) techo -r opt $opt=$val; continue
+						;;
+				esac
+				HEADER[$opt]=$val 
+			done
+		fi
+	fi
+}
+
+function isZshLib()
+{
+	local mime=$(getmime "$*")
+	[[ $mime = 'text/plain' && $(read -e "$*") = VERSION=[0-9\.]## ]]
 }
 
 function isScript()
 {
-	local mime=$(getmime "$@")
-	[[ "$mime" = "text/x-shellscript" ]] || {
-		[[ "$mime" = "text/plain" ]] && head -n1 "$*" | grep -q '^VERSION'
-	}
+	local mime=$(getmime "$*")
+	[[ $mime = 'text/x-shellscript' || $mime = 'text/plain' && $(read -e "$*") = VERSION=[0-9\.]## ]]
 }
 
 function typeOf()
 {
-	local name ret tpath
-	name="$1"
-	if [[ ! -f "$name" ]]; then
-		ret=($(which -w $name))
-		type="${ret[2]}"
-		if [[ "$type" != "none" ]]; then
-			if [[ "$type" == "command" ]]; then
-				tpath=$(which $name)
-				if isScript $tpath; then
-					type="script"
-				fi
+	#[[ -o xtrace ]] && _dbg_fcfg $0
+	local name ret tpath all result
+	local integer i=2
+	zparseopts -D -M - a=all p=p
+	name=$1
+	if [[ ! -f '$name' ]]; then
+		ret=($(which -w $all $p $name))
+
+		for ((i=2 ; $+ret[i] ; i+=2)); do
+			type=$ret[i]
+
+			if [[ $type == 'none' ]]; then
+				echo 'none'
+				return 1
 			fi
-			echo $type $tpath
-			return 0
-		fi
-		echo "none"
-		return 1
+
+			if [[ $type == 'command' ]]; then
+				tpath=$(which $name)
+				isScript $tpath && type='script'
+			fi
+
+			result+=($type:$tpath)
+		done
+		echo ${(z)${(@u)result//:/ }}
+		return 0
 	fi
 	
 	tpath=$name
 	
 	if isScript $tpath; then
-		type="script"
+		type='script'
 	elif [[ -x "$tpath" ]]; then
-		type="command"
+		type='command'
 	else
 		echo "none"
 		return 1
@@ -182,87 +228,159 @@ function zindent()
 	[[ -n $f ]] && echo "}"
 }
 
+function parseErrors()
+{
+	local line
+	while read line; do
+		#echo line=${(q)line}
+		[[ $line == 'EOF' ]] && return
+		if [[ $line =~ $'^(.+):([0-9]+): (parse error near) `(.*)\'' ]]; then
+		elif [[ $line =~ $'^(.+):([0-9]+): (condition expected): "(.*)"' ]]; then
+		elif [[ $line =~ $'^(.+):([0-9]+): (not an identifier):(.*)' ]]; then
+
+		else
+			techo -Pr "%F{9}${line}%f"
+			continue
+		fi
+		
+		print -Pr ${(@q)match}
+	done
+}
+
 # Include a zsh lib
 function include()
 {
-	local name lpath lazyload required force str mtime info
-	zparseopts -D -M - l=lazyload p:=lpath -path:=lpath r=required -required=r f=force
+	local quiet verbose lpath lazyload required force
+	local mtime info name
+	zparseopts -D -M - l=lazyload p:=lpath -path:=lpath r=required -required=r \
+		f=force q=quiet v:=verbose
 
-	[[ $# -eq 0 ]] && return 1
-	[[ "$1" = */* ]] && {
+	(( !$# )) && return 1
+	verbose=${verbose[2]:-2}
+	[[ -n $quiet ]] && verbose=0
+	if [[ $1 = */* ]]; then
 		lpath="$(getfullpath $1)"
 		name="${$(getfilename $1)#zsh_*}"
-	} || {
+	else
 		name="${1#zsh_*}"
-		if [[ -n "$lpath" ]]; then
-			lpath="${lpath[2]}"
+		if [[ -n $lpath ]]; then
+			lpath=$lpath[2]
 		else
 			lpath="$ZSH_LIBS/zsh_$name"
 		fi
-	}
+	fi
 		
-	[[ -n $required ]] && required=1 || required=0
+	required=$#required
 
-	if [[ ! -f "$lpath" ]]; then
-		techo "[\e[1;101mFAIL\e[0m] \e[91m$lpath not found\e[0m"
-		if [[ $required -eq 1 ]]; then
-			techo "\e[1;91mRequired $name not loaded\e[0m"
+	if [[ ! -f $lpath ]]; then
+		techo -P "[%1K%F{15}FAIL%f%k] %F{11}$lpath %F{9}not found%f"
+		if ((required)); then
+			techo -P "%F{9}Required %F{11}$name %F{9}not loaded%f"
 			[[ ! -o interactive ]] && abort 127
 		fi
 		return 127
 	fi
 
-	mtime=$(stat -L --printf='%Y' "$lpath") || abort $? 'stat error'
+	mtime=$(stat -L --printf='%Y' $lpath) || techo -P "%F{9}stat error on %F{11}$lpath%f"
 	info="ZSH_${(U)name}_INFO"
-	if [[ -z ${(P)info} || -n "$force" || "${${(P)info}[mtime]}" -lt "$mtime" ]]; then
-		if ! isScript $lpath; then 
-			techo "\e[91m$lpath is not a script\e[0m"
-			if [[ $required -eq 1 ]]; then
-				[[ ! -o interactive ]] && abort 2
+
+	if [[ -z ${(P)info} ||  # not loaded
+		-n $force ||  # force load 
+		${${(P)info}[mtime]} -lt $mtime ]] || # file was modified
+		((${${(P)info}[lazyload]} && ! $#lazyload)) # was lazy loaded 
+	then 
+		if ! zshLibReadHeader $lpath; then
+			techo -P "%F{11}$lpath %F{9}is not a zsh library%f"
+			if ((required)); then
+				[[ -o interactive ]] || abort 2
 				return 2
 			fi
 			return 1
 		fi
-		if [ -n "$lazyload" ]; then # @TODO
-			return 0
-		else
-			#[[ -o interactive ]] && 
-			techo -n "Including $name (${lpath/$ZSH_LIBS/\$ZSH_LIBS})"
-			source "$lpath"
-			ret=$?
-			if [ $ret -eq 0 ]; then
-				typeset -Ag _temp_aarray
-				lib_set_info $name $VERSION "$lpath" ${required:-0} "$mtime"
-				#[[ -o interactive ]] &&
-				techo " [\e[92m$VERSION\e[0m]"
-			else
-				local line
-				techo " [\e[1;101mFAIL\e[0m]"
-				if [[ $required -eq 1 ]]; then
-					techo "\n\e[1;92mRequired $name not loaded\e[0m"
-					[[ ! -o interactive ]] && abort 2
-					return 2
-				fi
-				return $ret
+
+		if (($#lazyload)); then # @TODO
+			local llfuncs func
+			if [[ -n $HEADER[lazyload] ]]; then
+				explode -v llfuncs ${HEADER[lazyload]} ','
+				for func in $llfuncs; do
+					functions[$func]="include $name && $func \$@"
+				done
 			fi
+			lib_set_info $name $VERSION "$lpath" ${required:-0} "$mtime" 1
+			return 0
+		fi
+
+		#[[ -o interactive ]] && 
+		techo -P -r "Including %F{11}$name%f ("${lpath/$ZSH_LIBS/"\\$"ZSH_LIBS}") [%F{2}$VERSION%f]"
+		if source $lpath; then
+			lib_set_info $name $VERSION "$lpath" ${required:-0} "$mtime"
+			#[[ -o interactive ]] &&
+		else
+			local error error2 file line tmp split
+			lib_set_info -E $name $VERSION "$lpath" ${required:-0} "$mtime"
+			techo -P "%F{11}$name%f [%K{1}%F{15}FAIL%f%k]"
+			(
+				coproc parseErrors 
+				#@TODO sort errors by file before opening files
+				while read -pr tmp; do
+					split=(${(z)tmp})
+					file=$split[1]; line=$split[2]; error=$split[3]; error2=$split[4]
+					techo -Pr "%F{3}$file:$line %F{9}${error} %K{1}%F{15}${error2}%f%k"
+					if type v 2>&1 >/dev/null; then
+						v $file:$line &
+					else
+						${EDITOR:-vim} $file +$line &
+					fi
+				done
+				echo EOF >&p
+			)
+
+			if ((required)); then
+				techo -P "\n%F{9}Required %F{11}\"zsh_$name\"%F{9} not loaded%f"
+				[[ -o interactive ]] || abort 2
+				return 2
+			fi
+			return $ret
 		fi
 	fi
 }
 
+function reload()
+{
+	local lib ll info libs=($(typeset -m 'ZSH_*_INFO' | cut -d'=' -f1))
+	for lib in $libs; do
+		if [[ $lib =~ 'ZSH_(.*)_INFO' ]]; then
+			info=ZSH_${match[1]}_INFO
+			((${${(P)info}[lazyload]})) && ll=-l || ll=''
+			include -q $ll ${(L)match[1]}
+		fi
+	done
+}
+
+function TRAPHUP() { reload }
+#function TRAPINT() {
+#	kill -$1 $$
+#	return $((128+$1))
+#}
+
 comp+=("inst=apt")
 function inst()
 {
-	local machine pkgs
-	zparseopts -D -E -M - m:=machine
-	if [[ -z "$machine" ]]; then
-		if [[ ${#@} -ge 1 ]]; then
-			pkgs=("$@")
+	local machine cmd pkgs pkg
+	zparseopts -D -M - m:=machine
+	if [[ -z $machine ]]; then
+		if (($#)); then
+			cmd=("$@")
 		else
-			pkgs=${$(fc -ln -1)[1]}
+			#@TODO findcmd(use inalias)
+			cmd=(${$(fc -ln -1)[1]})
 		fi
-		sudo apt-get install $pkgs
+		for cmd in $cmd; do
+			pkg=$(chooser -s':' -f1 --ifs $'\n' "$(dpkg -S '*/'$cmd)}") || return
+			(($#pkg)) && sudo apt-get install $pkg
+		done
 	else
-		echo "$@" >> "$CFG/${machine[2]}.pkgs.txt"
+		echo "$@" >> $CFG/$machine[2].pkgs.txt
 	fi
 }
 
@@ -271,15 +389,39 @@ function inst()
 # in_array array_name value
 function in_array()
 {
-	local name=$1 val="$2"
-	[[ ${${(P)name}[(i)$val]} -le ${(P)#name} ]]
+	local name val _var
+	zparseopts -D -M - v:=_var
+	[[ -v $_var[2] ]] && _var=$_var[2]
+	name=$1
+	val=$2
+	integer i=${${(P)name}[(i)$val]}
+	
+	((i <= ${(P)#name}))
 }
 
+#TODO call this within chooser
+function match_array()
+{
+	local _var field choose sep
+	zparseopts -D -M - v:=_var f:=field c=choose s:=sep
+	[[ -v $_var[2] ]] || return 1
+	_var=${_var[2]:-REPLY}
+	typeset -ga $_var
+	typeset "$_var=(${(M)${(P)2}:#${1}*})"
+	[ -t 1 ] || echo $_var
+	if (($#choose)); then
+		chooser -v $_var $field $sep ${(P)_var} || cancel
+	else
+		(($#_var))
+	fi
+}
+
+#@untested check escaping
 function ltrim() {
-	echo "${*##[[:blank:]]##}"
+	echo "${(q)*##[[:blank:]]##}"
 }
 function rtrim() {
-	echo "${*%%[[:blank:]]##}"
+	echo "${(q)*%%[[:blank:]]##}"
 }
 function trim()
 {
@@ -296,10 +438,26 @@ function aptinst()
 # Added 2019-09-03 19:29
 function libmonitor()
 {
-	local name evt
+	# last   t       last+1.5   
+	# | DIFF | SLEEP |
+	local name evt pids
+	float t lastt=0 diff
 	while read -r evt name; do
 		[[ $evt == 'exit' ]] && break
-		techo -c warn "$evt $name"
+		pids=($(pidof inotifywait 2>/dev/null))
+		if (($#pids > 1)); then
+			command kill ${pids:0:-1}
+		fi
+		techo -c warn "$evt $name $$"
+		t=$(date '+%s.%3N')
+		((diff = t - lastt))
+		if ((diff < 1.5)); then
+			((diff = 1.5 - diff))
+			sleep $diff
+			((t += diff))
+		fi
+		((lastt = t))
+		killall -HUP zsh
 	done < <(inotifywait -m -q -e modify -r --format '%e %f' $ZSH_LIBS || echo "exit $?")
 	return $name
 }
@@ -307,11 +465,47 @@ function libmonitor()
 # "include" itself
 lib_set_info main $VERSION "$0" 1 "$(stat -L --printf='%Y' "$0")"
 
-if [[ -o interactive ]] && { [[ -z $LIBMON_PID ]] || ! kill -0 $LIBMON_PID 2>/dev/null }; then
+#if [[ -o interactive ]] && { [[ -z $LIBMON_PID ]] || ! kill -0 $LIBMON_PID 2>/dev/null }; then
+if [[ -o interactive ]] && ! pidof inotifywait 2>&1 >/dev/null; then
 	while ! type inotifywait 2>&1 >/dev/null; do
 		aptinst inotify-tools || {
 			ret=$?
-			[[ $ret -eq 130 || $ret -eq 1 ]] && break
+			(( ret==130 || ret==1 )) && break
 		}
-	done && { libmonitor & export LIBMON_PID=$! }
+	done && { libmonitor &! }
+#	done && { libmonitor & export LIBMON_PID=$! }
 fi
+
+alias sudo='noglob do_sudo '
+comp+=("do_sudo=sudo")
+function do_sudo()
+{
+	integer glob=1
+	local -a run
+	include -r functions
+	if [[ $# -gt 1 && $1 == -u ]]; then
+		run=(command sudo -u $2)
+		shift ; shift
+	else
+		run=(run -s)
+	fi
+	(($# == 0)) && 1=/bin/zsh
+	while (($#)); do
+		case $1 in
+			command|exec|-) shift
+				break
+				;;
+			nocorrect) shift
+				;;
+			noglob) glob=0; shift
+				;;
+			*) break
+				;;
+		esac
+	done
+	if ((glob)); then
+		PATH="/sbin:/usr/sbin:/usr/local/sbin:$PATH" $run $~==*
+	else
+		PATH="/sbin:/usr/sbin:/usr/local/sbin:$PATH" $run $==*
+	fi
+}
