Update all

diff --git a/zsh_libs/zsh_network b/zsh_libs/zsh_network
--- a/zsh_libs/zsh_network
+++ b/zsh_libs/zsh_network
@@ -1,10 +1,247 @@
 VERSION=1.0.2
-#lazyload=urlfollow,urlinfo,vnc,imdb,globo
+#lazyload=urlfollow,urlinfo,url,vnc,imdb,globo,netGet,netGetJson,urlencode,urldecode
 
 [[ ! -v comp ]] && typeset -g -a comp
 
+zmodload zsh/langinfo # Required for $langinfo
+
+# URL-encode a string
+#
+# Encodes a string using RFC 2396 URL-encoding (%-escaped).
+# See: https://www.ietf.org/rfc/rfc2396.txt
+#
+# By default, reserved characters and unreserved "mark" characters are
+# not escaped by this function. This allows the common usage of passing
+# an entire URL in, and encoding just special characters in it, with
+# the expectation that reserved and mark characters are used appropriately.
+# The -r and -m options turn on escaping of the reserved and mark characters,
+# respectively, which allows arbitrary strings to be fully escaped for
+# embedding inside URLs, where reserved characters might be misinterpreted.
+#
+# Prints the encoded string on stdout.
+# Returns nonzero if encoding failed.
+#
+# Usage:
+#  omz_urlencode [-r] [-m] [-P] <string>
+#
+#    -r causes reserved characters (;/?:@&=+$,) to be escaped
+#
+#    -m causes "mark" characters (_.!~*''()-) to be escaped
+#
+#    -P causes spaces to be encoded as '%20' instead of '+'
+function urlencode()
+{
+	emulate -L zsh
+	zparseopts -D -E -a opts r m P
+
+	local in_str=$1
+	local url_str=""
+	local spaces_as_plus
+	if [[ -z $opts[(r)-P] ]]; then spaces_as_plus=1; fi
+	local str="$in_str"
+
+	# URLs must use UTF-8 encoding; convert str to UTF-8 if required
+	local encoding=$langinfo[CODESET]
+	local safe_encodings
+	safe_encodings=(UTF-8 utf8 US-ASCII)
+	if [[ -z ${safe_encodings[(r)$encoding]} ]]; then
+		str=$(echo -E "$str" | iconv -f $encoding -t UTF-8)
+		if [[ $? != 0 ]]; then
+			echo "Error converting string from $encoding to UTF-8" >&2
+			return 1
+		fi
+	fi
+
+	# Use LC_CTYPE=C to process text byte-by-byte
+	local i byte ord LC_ALL=C
+	export LC_ALL
+	local reserved=';/?:@&=+$,'
+	local mark='_.!~*''()-'
+	local dont_escape="[A-Za-z0-9"
+	if [[ -z $opts[(r)-r] ]]; then
+		dont_escape+=$reserved
+	fi
+	# $mark must be last because of the "-"
+	if [[ -z $opts[(r)-m] ]]; then
+		dont_escape+=$mark
+	fi
+	dont_escape+="]"
+
+	# Implemented to use a single printf call and avoid subshells in the loop,
+	# for performance (primarily on Windows).
+	local url_str=""
+	for (( i = 1; i <= ${#str}; ++i )); do
+		byte="$str[i]"
+		if [[ "$byte" =~ "$dont_escape" ]]; then
+			url_str+="$byte"
+		else
+			if [[ "$byte" == " " && -n $spaces_as_plus ]]; then
+				url_str+="+"
+			else
+				ord=$(( [##16] #byte ))
+				url_str+="%$ord"
+			fi
+		fi
+	done
+	echo -E "$url_str"
+}
+
+# URL-decode a string
+#
+# Decodes a RFC 2396 URL-encoded (%-escaped) string.
+# This decodes the '+' and '%' escapes in the input string, and leaves
+# other characters unchanged. Does not enforce that the input is a
+# valid URL-encoded string. This is a convenience to allow callers to
+# pass in a full URL or similar strings and decode them for human
+# presentation.
+#
+# Outputs the encoded string on stdout.
+# Returns nonzero if encoding failed.
+#
+# Usage:
+#   omz_urldecode <urlstring>  - prints decoded string followed by a newline
+function urldecode()
+{
+	emulate -L zsh
+	local encoded_url=$1
+
+	# Work bytewise, since URLs escape UTF-8 octets
+	local caller_encoding=$langinfo[CODESET]
+	local LC_ALL=C
+	export LC_ALL
+
+	# Change + back to ' '
+	local tmp=${encoded_url:gs/+/ /}
+	# Protect other escapes to pass through the printf unchanged
+	tmp=${tmp:gs/\\/\\\\/}
+	# Handle %-escapes by turning them into `\xXX` printf escapes
+	tmp=${tmp:gs/%/\\x/}
+	local decoded
+	eval "decoded=\$'$tmp'"
+
+	# Now we have a UTF-8 encoded string in the variable. We need to re-encode
+	# it if caller is in a non-UTF-8 locale.
+	local safe_encodings
+	safe_encodings=(UTF-8 utf8 US-ASCII)
+	if [[ -z ${safe_encodings[(r)$caller_encoding]} ]]; then
+		decoded=$(echo -E "$decoded" | iconv -f UTF-8 -t $caller_encoding)
+		if [[ $? != 0 ]]; then
+			echo "Error converting string from UTF-8 to $caller_encoding" >&2
+			return 1
+		fi
+	fi
+
+	echo -E "$decoded"
+}
+
+function netGetJson()
+{
+	local var jqFilter opts json tmp
+	integer ret
+	zparseopts -D -M -A opts - v: -var:=v -jq: -raw
+
+	netGet --var json --header 'Accept: application/json' "$@" || return
+
+	if (($+opts[--raw])); then
+		if (($+opts[--jq])); then
+			jqFilter=${opts[--jq]:-.}
+		fi
+	else
+		e jq $opts[--jq]
+		jqFilter=${opts[--jq]:-.}' | @sh'
+		e jqf $jqFilter
+	fi
+
+	if (($#jqFilter)); then
+		tmp=$(jq -erc $jqFilter <<< $json) || return
+	else
+		tmp=$json
+	fi
+	if (($+opts[-v])); then
+		typeset -g "$opts[-v]=$tmp"
+	else
+		print -r -- $tmp
+	fi
+}
+
+function netGet()
+{
+	local checkEval ftemp fname url out opt
+	typeset -a opts cOpts
+	integer stdout verbose=1 ret minKbps=20
+	zparseopts -D -M -A opts - v: 'q' -var:=v -stdout -temp: -check-eval: -url: -user: -header: -post
+
+	type -p curl git >/dev/null || sudo apt install curl git
+
+	#minKbps=${opts[--min-speed]:-}
+	cOpts=(-L --speed-time 8 --speed-limit $((1000*minKbps)) --create-dirs)
+	(($+opts[-q])) && verbose=0 || { (($+opts[-v])) && verbose=${opts[-v]} }
+	((verbose)) || cOpts+=(-sS)
+	if (($+opts[--url])); then
+		url=$opts[--url]
+	elif (($#1)); then
+		url=$1; shift
+	else
+		return 10
+	fi
+
+	# pass through these options to curl
+	for opt in user header request data; do
+		opt="--$opt"
+		if (($+opts[$opt])); then
+			cOpts+=($opt $opts[$opt])
+		fi
+	done
+
+	if (($#1)); then
+		fname=$1
+		(($+opts[--temp])) && ftemp=${opts[--temp]}
+		if (($#ftemp)); then
+			cOpts+=(-o "$ftemp")
+		else
+			cOpts+=(-o "$fname")
+		fi
+	elif (($+opts[-v] || $+opts[--stdout])); then
+		stdout=1
+	else
+		cOpts+=(-JO -w '%{filename_effective}')
+		((verbose)) && techo -c warn 'Saving to '$PWD'. Using filename given by remote.'
+	fi
+
+	out=$(curl $cOpts $url); ret=$?
+	if ((ret)); then
+		(($#ftemp)) && rm -f $ftemp
+		return $ret
+	fi
+
+	if ((stdout)); then
+		if (($+opts[-v])); then
+			typeset -g "$opts[-v]=$out"
+		else
+			echo -n - $out
+		fi
+		return 0
+	fi
+
+	[[ -z $fname ]] && fname=$out # from -w {filename_effective}
+
+	if (($+opts[--check-eval])); then
+		local name=${ftemp:-$fname}
+		[[ -n $name ]] || { techo -c warn 'Filename not given but --check-eval used'; return 2 }
+		checkEval=${opts[--check-eval]//'$file'/$name}
+		eval $checkEval; ret=$?
+	fi
+
+	if ((ret)); then
+		(($#ftemp)) && rm -f $ftemp || rm -f $fname
+	else
+		mv $ftemp $fname; ret=$?
+	fi
+	return $ret
+}
+
 function urlfollow() {
-	curl -Ls -I -o /dev/null -w %{url_effective} $1
+	curl -LsS -I -o /dev/null -w '%{url_effective}' $1
 }
 
 # Choose which parts of given url to return, or save in array (-v varname)
@@ -43,6 +280,7 @@ function urlinfo()
 		(($+opts[-p])) && { _path=($match[5]); out+=$_path }
 		(($+opts[-q])) && { query=(${match[6]#\?}); out+=$query }
 	elif [[ $1 =~ (${~userpat}'@')?(${~hostpat}):($~pathpat)? ]]; then
+		# git scheme is actually ssh: git@host:path
 		if (($+opts[-s])); then
 			[[ $match[1] == 'git' ]] && scheme=(git) || scheme=(ssh)
 			out=($scheme)
@@ -57,33 +295,26 @@ function urlinfo()
 	return 0
 }
 
-function imdb()
-{
-	local e
-	[[ $1 == '-e' ]] && { shift; e='-e' }
-
-	url $e 'https://www.imdb.com/find?q=' "$*"
-}
-
 function url()
 {
-	local echo encode url arg c
-	zparseopts -D -M -E - e=echo -no-color=c c:=c # E=encode -encode=E
-
+	local encode url args c opts key val
+	zparseopts -D -M -E -A opts - 'e' c: -color=c
+	typeset -a args
 	[[ -n $1 ]] || return 10
-	url=$1
-	arg=$2
-	arg=$(omz_urlencode $arg)
+	url=("$(urlencode -mrp $1)"); shift
+	for key val; do
+		args+=("$(urlencode -mrp $key)")
+	done
 	if [[ -n $c[2] ]]; then
 		c=$C[$c[2]]
 	elif [[ -z $c ]]; then
-		c=$C[lgreen]
+		c=$C[${opts[-c]:-lgreen}]
 	else
 		c=
 	fi
 
 	url=$url$arg
-	if [[ -n $echo ]]; then
+	if (($+opts[-e])); then
 		echo $c$url
 	else
 		techo -c head 'Opening' $c$url
@@ -124,7 +355,13 @@ function htmlget()
 		- '/^¬/' -
 			'print $2'
 	)
-	tmp=($(curl -Ss -w "\n¬ %{http_code}" -L $url | awkWrapper -e expr))
+
+	tmp=$TMP/'globo_raw.html'
+	if curl -Ss -w "\n¬ %{http_code}" -L $url -o $tmp && [[ -s $tmp ]]; then
+		abort $? curl
+	fi
+
+	tmp=($(cat $tmp | awkWrapper -e expr))
 	code=$tmp[-1]
 	if ((code!=200)); then
 		techo -c err "curl: http code $code"
@@ -133,6 +370,13 @@ function htmlget()
 
 	tidy $opts <<< $tmp[1,-2]
 	return 0
+}
+
+function imdb()
+{
+	local e
+	[[ $1 == '-e' ]] && { shift; e='-e' }
+	url $e 'https://www.imdb.com/find?q=' "$*"
 }
 
 # print: sed -n '/^<tr>/p' file
@@ -144,7 +388,7 @@ function globo()
 
 	htmlget $update -b '<section class="schedule-item' \
 		-e '<div class="grade-de-programacao-container-bottom"' \
-		-o $file https://redeglobo.globo.com/sao-paulo/programacao || return
+		-o $file https://redeglobo.globo.com/sao-paulo/programacao || abort $? htmlget
 
 	vars=(today=$(date '+%Y%m%d') yesterday=$(date -d yesterday '+%Y%m%d') now=$(date '+%s'))
 	expr=(
@@ -225,6 +469,11 @@ function ipfind()
 	done
 }
 
+function ipget()
+{
+	ip addr | egrep -o '192.*/' | explode --stdin '/'
+}
+
 # Added 2020-01-15 19:12
 function google()
 {
@@ -247,4 +496,9 @@ function vnc()
 	done
 	#DISPLAY=:0
 	x0vncserver -display :0 -rfbport 5555 -rfbauth $passfile
+}
+
+function ssh_()
+{
+	#-o PubkeyAuthentication=no
 }
diff --git a/zsh_libs/zsh_sql b/zsh_libs/zsh_sql
--- a/zsh_libs/zsh_sql
+++ b/zsh_libs/zsh_sql
@@ -7,17 +7,7 @@ alias sqlmaq="noglob sql --ssh maquina"
 DB_DATA_DIR=/var/lib/mysql
 DBNAME='idiomus'
 
-typeset -gA sqlPass=(
-	# user  pass
-	'sparc' 'my!7866'
-	'idiomus' '#58dhAms$3xx'
-)
-typeset -gA sqlUser=(
-	# root user
-	'root' 'sparc'
-	# Dbname    User
-	'idiomus' 'idiomus'
-)
+source $CFG/sql.cfg.zsh
 
 typeset -gA rowIndex
 
@@ -28,12 +18,12 @@ function dbtstamp()
 	usedb "$@"
 	sudo ls -lrt --time-style=+"%Y-%m-%d %H:%M:%S" $DB_DATA_DIR/$db/ | \
 		awk '{print $6,$7,$8}' | sort --numeric-sort
-}
+	}
 
 function todosql__()
 {
-	sql --ssh maquina 'SELECT review_version_id, sequence, length, texts, timestamps, status FROM review_track WHERE review_version_id=184 ORDER BY updated_at' | {          
-		read cols ; while IFS=$'\t\t' read -r version_id sequence length texts timestamps _status ; do 
+	sql --ssh maquina 'SELECT review_version_id, sequence, length, texts, timestamps, status FROM review_track WHERE review_version_id=184 ORDER BY updated_at' | {
+		read cols ; while IFS=$'\t\t' read -r version_id sequence length texts timestamps _status ; do
 			sqlQuote -v _texts $texts; sqlQuote -v _timestamps $timestamps
 			sql "insert into review_track (review_version_id,sequence, length, texts, timestamps,status) values ($version_id, $sequence, $length, '$_texts', '$_timestamps', '$_status')"
 		done
@@ -74,21 +64,22 @@ function sql()
 
 	if [[ -n $host ]]; then # remote
 		OPT_CHK file -f for remote
-		#(($+file)) && 
-		opts=() # TODO
+		#(($+file)) &&
+		opts=(-d idiomus) # TODO
+		#(($+_opts[-n])) || choose remote database
 		if (($+_opts[-o])); then
 			#@TODO
-			#ssh $host[2] "noglob sql $opts ${(qqq)sql}" 2>&p | \
+			#ssh $host[2] "noglob sql $opts ${(qq)sql}" 2>&p | \
 			#	awkWrapper -F '\\t' --inc printFields -E - - - - 'printFields(1,-1)'
 		else
-			ssh $host[2] "noglob sql $opts ${(qqq)sql}" 2>&p
+			ssh $host[2] "include sql; noglob sql $opts ${(qq)sql}" 2>&p
 		fi
 		ret=$?
 	else
 		opts=()
-
 		(($+_opts[-n])) || usedb $name[2]
 
+		# credentials
 		if [[ -n $db ]]; then
 			user=${_opts[-u]:-${sqlUser[$db]:-$sqlUser[root]}}
 			pass=${pass[2]:-$sqlPass[$user]}
@@ -124,42 +115,42 @@ function sql()
 					((i--))
 				fi
 			} < <(mysql $opts -e $sql $db) 2>&p
-			#mysql $opts -e $sql $db 2>&p | IFS=$'\t\t' read -A $_out[2]
-				#awkWrapper $_out -F '\\t' --inc printFields -E - - - - 'printArgs(1,-1)'
-			ret=$?
-			if ((i)); then
-				if (($#_colsOut)); then
-					_colsOut=$_colsOut[2]
-					typeset -gA $_colsOut
-					integer colN=1
-					for col in $_cols; do
-						typeset -g "${_colsOut}[$col]=$colN"
-						((colN++))
-					done
-				fi
+		#mysql $opts -e $sql $db 2>&p | IFS=$'\t\t' read -A $_out[2]
+		#awkWrapper $_out -F '\\t' --inc printFields -E - - - - 'printArgs(1,-1)'
+		ret=$?
+		if ((i)); then
+			if (($#_colsOut)); then
+				_colsOut=$_colsOut[2]
+				typeset -gA $_colsOut
+				integer colN=1
+				for col in $_cols; do
+					typeset -g "${_colsOut}[$col]=$colN"
+					((colN++))
+				done
+			fi
+		fi
+	else
+		#@TODO: no error handling: redirect stderr to null
+		if (($#file)); then
+			if [[ -f $file ]]; then
+				(($#verbose)) && techo -r -c head mysql ${(qq)opts} ${(qq)sql} $db '<' $file
+				mysql $opts $sql $db 2>&p < $file
+			else
+				techo -c err "File not found$C_: $file"
+				false
 			fi
 		else
-			#@TODO: no error handling: redirect stderr to null
-			if (($#file)); then
-				if [[ -f $file ]]; then
-					(($#verbose)) && techo -r -c head mysql ${(qq)opts} ${(qq)sql} $db '<' $file
-					mysql $opts $sql $db 2>&p < $file
-				else
-					techo -c err "File not found$C_: $file"
-					false
-				fi
+			if (($#_idVar)); then
+				# sql+="; SELECT ROW_COUNT(), LAST_INSERT_ID()"
+				sql+="; SELECT LAST_INSERT_ID()"
+				(($#verbose)) && techo -r -c head mysql $opts -s -e ${(qq)sql} $db
+				_id=$(mysql $opts -s -e $sql $db) 2>&p
 			else
-				if (($#_idVar)); then
-					# sql+="; SELECT ROW_COUNT(), LAST_INSERT_ID()"
-					sql+="; SELECT LAST_INSERT_ID()"
-					(($#verbose)) && techo -r -c head mysql $opts -s -e ${(qq)sql} $db
-					_id=$(mysql $opts -s -e $sql $db) 2>&p
-				else
-					(($#verbose)) && techo -r -c head mysql $opts -e ${(qq)sql} $db
-					mysql $opts -e "$sql" $db 2>&p
-				fi
+				(($#verbose)) && techo -r -c head mysql $opts -e ${(qq)sql} $db
+				mysql $opts -e "$sql" $db 2>&p
 			fi
-			ret=$?
+		fi
+		ret=$?
 		fi
 	fi
 	echo EOF >&p ; wait $p
@@ -230,20 +221,20 @@ function sqlError()
 	((_v)) && msg="SQL Error $cod ($state)$C_ at line $line: "
 	case $cod in
 		1049) msg+="Can't connect to database $C[warn]'$1'$C_"
-		;;
+			;;
 		1062) #uses the format string for 1586 (ER_DUP_ENTRY_WITH_KEY_NAME)
 			msg+="Duplicate entry $C[warn]'$1'$C_ for key $C[warn]'$2'"
-		;;
+			;;
 		1064) msg+="Syntax error near $C[warn]'$@'"
-		;;
+			;;
 		145[12]) msg+="Constraint violation $C[warn]$3$C_: $C[warn]$2.$4$C_ REFERENCES $C[warn]$5.$6"
-		;;
+			;;
 		*) local _args=("$@")
 			# printf -v _args $msg"$(perror -s $cod)" $C[warn]$^_args$C_
 			printf -v _args $msg"$(perror -s $cod)" $_args
 			techo -c lred $_args
 			return
-		;;
+			;;
 	esac
 	techo -c lred $msg
 }
@@ -270,35 +261,35 @@ function parseSqlErrors()
 			#  https://mariadb.com/kb/en/mariadb-error-codes/
 			#  sql/share/errmsg-utf8.txt
 			case $errCode in
-			1062)
-				#uses the format string for 1586 (ER_DUP_ENTRY_WITH_KEY_NAME)
-				msgFormat="Duplicate entry '(.*)' for key '(.*)'"
-				;;
-			1064)
-				msgFormat="near '(.*)'"
-				;;
-			145[12])
-				msgFormat='^[^(]+\(`([^`]+)`.`([^`]+)`, CONSTRAINT `([^`]+)` FOREIGN KEY \(([^)]+)\) REFERENCES `([^`]+)` \(([^)]+)\)'
-				#msgFormat="^[^(]+\\(\`([^\`]+)\`.\`([^\`]+)\`, CONSTRAINT \`([^\`]+)\` FOREIGN KEY \\(\`([^\`]+)\`\\) REFERENCES \`([^\`]+)\` \\(\`([^\`]+)\`"
-			#	msgFormat="Cannot add or update a child row: a foreign key constraint fails (`¬tbl¬`.`#¬sql¬`, CONSTRAINT `#¬fk¬` FOREIGN KEY (`¬col¬`) REFERENCES `¬tbl¬` (`¬col¬`))"
-	#ERROR 1452 (23000) at line 1: Cannot add or update a child row: a foreign key constraint fails (`idiomus`.`#sql-426_49`, CONSTRAINT `#sql-426_49_ibfk_1` FOREIGN KEY (`review_id`) REFERENCES `review` (`review_id`))
-				;;
-			*)
-				if msgFormat=${"$(perror $errCode)"#*: }; then
-					msgFormat=${msgFormat//(#m)[()]/'\'$MATCH}
-					rx=(
-						'%l#[du]'       '(-?[0-9]+)'
-						'%-#.#[0-9]#[sM]' '(.*)'
-						'\).' ')\.'
-					)
-					msgFormat=${msgFormat//${~rx[1]}/$rx[2]}
-					msgFormat=${msgFormat//${~rx[3]}/$rx[4]}
-					msgFormat='^'${msgFormat//${~rx[5]}/$rx[6]}
-				else
-					techo -c lred "Unknown error: $C[warn]$errCode$C_ ($sqlState)"
-					continue
-				fi
-				;;
+				1062)
+					#uses the format string for 1586 (ER_DUP_ENTRY_WITH_KEY_NAME)
+					msgFormat="Duplicate entry '(.*)' for key '(.*)'"
+					;;
+				1064)
+					msgFormat="near '(.*)'"
+					;;
+				145[12])
+					msgFormat='^[^(]+\(`([^`]+)`.`([^`]+)`, CONSTRAINT `([^`]+)` FOREIGN KEY \(([^)]+)\) REFERENCES `([^`]+)` \(([^)]+)\)'
+					#msgFormat="^[^(]+\\(\`([^\`]+)\`.\`([^\`]+)\`, CONSTRAINT \`([^\`]+)\` FOREIGN KEY \\(\`([^\`]+)\`\\) REFERENCES \`([^\`]+)\` \\(\`([^\`]+)\`"
+					#	msgFormat="Cannot add or update a child row: a foreign key constraint fails (`¬tbl¬`.`#¬sql¬`, CONSTRAINT `#¬fk¬` FOREIGN KEY (`¬col¬`) REFERENCES `¬tbl¬` (`¬col¬`))"
+					#ERROR 1452 (23000) at line 1: Cannot add or update a child row: a foreign key constraint fails (`idiomus`.`#sql-426_49`, CONSTRAINT `#sql-426_49_ibfk_1` FOREIGN KEY (`review_id`) REFERENCES `review` (`review_id`))
+					;;
+				*)
+					if msgFormat=${"$(perror $errCode)"#*: }; then
+						msgFormat=${msgFormat//(#m)[()]/'\'$MATCH}
+						rx=(
+							'%l#[du]'       '(-?[0-9]+)'
+							'%-#.#[0-9]#[sM]' '(.*)'
+							'\).' ')\.'
+						)
+						msgFormat=${msgFormat//${~rx[1]}/$rx[2]}
+						msgFormat=${msgFormat//${~rx[3]}/$rx[4]}
+						msgFormat='^'${msgFormat//${~rx[5]}/$rx[6]}
+					else
+						techo -c lred "Unknown error: $C[warn]$errCode$C_ ($sqlState)"
+						continue
+					fi
+					;;
 			esac
 
 			if [[ $msg =~ $msgFormat ]]; then
@@ -404,12 +395,27 @@ function dbsize()
 # Added 2019-03-23 23:36
 function sqldbdump()
 {
+	local opts
+
 	usedb "$@"
 	if [[ -f $db.sql.bkup ]]; then
 		techo -c warn "Saving backup $db.sql.bkup"
 		mv $db.sql $db.sql.bkup
 	fi
-	mysqldump $db --no-data --single-transaction --skip-add-drop-table | \
+
+	# credentials
+	if [[ -n $db ]]; then
+		user=${_opts[-u]:-${sqlUser[$db]:-$sqlUser[root]}}
+		pass=${pass[2]:-$sqlPass[$user]}
+	else
+		user=${_opts[-u]:-$sqlUser[root]}
+		pass=${pass[2]:-$sqlPass[$user]}
+	fi
+	(($+_opts[-p])) && pass=$_opts[-p]
+	opts+=(${user:+-u$user} ${pass:+-p"$pass"})
+#--no-data 
+	mysqldump $db $opts --single-transaction --skip-add-drop-table | \
 		sed -e 's/ AUTO_INCREMENT=[0-9]*\b//g' | \
 		grep -v '^\/\*![0-9]\{5\}.*character_set_client.*\/;$' > $db.sql
+	#t=calculo; mysqldump --no-create-info --extended-insert --password='Churr!4as678' -u $
 }
