Flushing android and other small changes

diff --git a/zsh_libs/zsh_android b/zsh_libs/zsh_android
--- a/zsh_libs/zsh_android
+++ b/zsh_libs/zsh_android
@@ -1,10 +1,21 @@
 VERSION=1.0.0
 
-type getfullpath 2>&1 >/dev/null || include file
-export ANDROID_SDK_ROOT=$(getfullpath $HOME/Android/Sdk)
+export ANDROID_SDK_ROOT=$(getfullpath $HOME/androidSDK)
+if ! [[ -d $ANDROID_SDK_ROOT && -d $ANDROID_SDK_ROOT/tools ]]; then
+	echo "Android SDK not found"
+	return 1
+fi
 export ANDROID_HOME=$ANDROID_SDK_ROOT
 export ANDROID_PLATFORM_TOOLS=$ANDROID_SDK_ROOT/platform-tools
 path+=($ANDROID_HOME/emulator $ANDROID_HOME/tools $ANDROID_HOME/tools/bin $ANDROID_PLATFORM_TOOLS)
+
+tmp=($ANDROID_HOME/build-tools/*(/On[1]))
+export ANDROID_BUILD_TOOLS=$tmp
+if [[ -d $ANDROID_BUILD_TOOLS ]]; then
+	alias aapt=$ANDROID_BUILD_TOOLS/aapt
+else
+	echo 'Build tools dir not found'
+fi
 
 # Get package name from apk file
 function getPkg()
@@ -17,10 +28,6 @@ return
 #APPS="${ANDROID_APPS:-$HOME/PeD/android}"
 #[ -d "$APPS" ] || APPS="$HOME/apps"
 #ANDROID_APPS="$APPS"
-SEAGATE_INBRAMED=/seagate
-SEAGATE_APPS=$SEAGATE_INBRAMED/android
-CLOUD_INBRAMED=$CLOUD/data/Inbramed
-CLOUD_APPS=$CLOUD_INBRAMED/android
 export ANDROID_APPS APPS CLOUD_APPS CLOUD_INBRAMED
 
 #export TREADMILL=$APPS/Treadmill
@@ -28,13 +35,6 @@ export ANDROID_APPS APPS CLOUD_APPS CLOUD_INBRAMED
 #export TREADMILL_IMG=$TREADMILL_RES/drawable
 #export TREADMILL_LAYOUT=$TREADMILL_RES/layout
 #export TREADMILL_JAVA="$(echo $TREADMILL/app/src/main/java/**/treadmill)"
-#
-#export CICLOERGOMETER=$APPS/Cicloergometer
-#export CICLOERGOMETER_RES=$CICLOERGOMETER/app/src/main/res
-#export CICLOERGOMETER_IMG=$CICLOERGOMETER_RES/drawable
-#export CICLOERGOMETER_LAYOUT=$CICLOERGOMETER_RES/layout
-#export CICLOERGOMETER_JAVA="$(echo $CICLOERGOMETER/app/src/main/java/**/cicloergometer)"
-#export CHIPSEE_JB=$HOME/images/Chipsee-BBB-JB-42-Source-20140413/device/ti/beagleboneblack
 
 # Added 2019-06-10 17:59
 function checkdbs()
diff --git a/zsh_libs/zsh_file b/zsh_libs/zsh_file
--- a/zsh_libs/zsh_file
+++ b/zsh_libs/zsh_file
@@ -1,5 +1,7 @@
 VERSION=1.0.8
-#lazyload=urlfollow,urlinfo,vnc,imdb,globo,awkWrapper
+#lazyload=syncDirs,urlfollow,urlinfo,vnc,imdb,globo,awkWrapper,getfullpath,getpath,getext,getfilename,isDir,isEmptyDir,box,ddiff
+
+[[ -v comp ]] || typeset -ga comp
 
 setopt nomultios
 
@@ -156,15 +158,16 @@ function ddiff()
 }
 
 # Added 2019-05-03 16:50
+comp+=("syncDirs=rsync")
 function syncDirs()
 {
 	integer i n
-	local src targets dir data rsArgs checksum arg
+	local src targets dir data rsArgs checksum arg noDelete
 	local quiet sudo excludeFrom dry extraArgs reverse
 	local files stat name noSlash sshCFG
 	typeset -a src targets rsArgs extraArgs files excludePatterns
 	zparseopts -D -M - q=quiet s=sudo i:=excludeFrom d=dry \
-		c=checksum r=reverse -no-add-slash=noSlash
+		c=checksum r=reverse -no-add-slash=noSlash -no-delete=noDelete
 
 	[[ -z "$sudo" ]] && sudo='-S'
 	(($# >= 2)) || abort 1 "usage: $0 source1 [.. sourceN] target1[,target2]"
@@ -211,11 +214,12 @@ function syncDirs()
 	rsArgs+=(--exclude=$^excludePatterns)
 	[[ -n $excludeFrom ]] && rsArgs+=(--exclude-from="${excludeFrom[2]}")
 
+	# analyse sources
 	for ((n=1; n<=$#src; n++)); do
 		local isEmptyDir=0
 
 		dir=$src[$n]
-		if [[ $dir =~ ([^:]+):(.*) ]]; then
+		if [[ $dir =~ ([^:]+):(.*) ]]; then		 # remote
 			local ret host=$match[1] p=$match[2]
 
 			#include -q network
@@ -237,14 +241,14 @@ function syncDirs()
 				fi"
 			))
 			case $ret in
-				1*)
+				1*) # dir
 					((!$#noSlash)) && [[ ${dir: -1} != / ]] && src[$n]+='/'
 					if [[ $ret == '1i' ]]; then
 						#@TODO: scp $dir/rsync.ignore /tmp)
 						#rsArgs+=(--exclude-from=$fIgnore)
 					fi
 					;;
-				f) ;;
+				f) ;; # file
 				0)
 					confirm -c warn "@TODO Empty remote directory$C_: $C[lred]'$host:$p'. \
 						Create dir" || cancel
@@ -278,44 +282,59 @@ function syncDirs()
 	# # # # # #
 	# Targets #
 	# # # # # #
-	local nothing=1 permFlags ret
+	local nothing=1 permFlags ret host p
 	for dir in $targets; do
-		local host p #sshArgs
+		host=''; p=''  #sshArgs
 		if [[ $dir =~ ([^:]+):(.*) ]]; then
 			host=$match[1]; p=$match[2]
-			# ????
-		elif isDir -m $dir; then
-			[[ "$(fstypeof $dir)" != 'vfat' ]] && permFlags='-pog'
+		elif ! isDir -m $dir; then
+			techo -c warn "Skipping $dir"
+			continue
+		fi
+
+		if ((1)); then
+			permFlags=''
+			if (($#host)); then # remote
+				permFlags='-p' # og'
+			else
+				[[ "$(fstypeof $dir)" != 'vfat' ]] && permFlags='-p' #og'
+			fi
 			#data="$(run $sudo rsync -ni ${sshArgs[@]} ${rsArgs[@]} $permFlags "$src[@]" $dir)"
 			data="$(run $sudo rsync -ni ${rsArgs[@]} $permFlags "$src[@]" $dir)"
 			if (($#data)); then
 				nothing=0
 				echo $data
-				confirm "Do it" && # run --confirm "Do it"
+				if confirm "Do it"; then
 					run $sudo rsync --info=PROGRESS2 $rsArgs $permFlags $src $dir || abort
-				_sync
+				else
+					cancel
+				fi
+
+				# @TODO((!isRemote && !noSync)) && _sync
 			fi
 
-			# # # # # # #
-			# Deletions #
-			# # # # # # #
-			data="$(run $sudo rsync -ni --delete --existing --ignore-existing \
-				-JO ${rsArgs[@]} $src[@] $dir)" || abort
+			if ((!$#noDelete)); then
+				# # # # # # #
+				# Deletions #
+				# # # # # # #  @TODO: -J (omit-link-times) does not work on old rsync
+				data="$(run $sudo rsync -ni --delete --existing --ignore-existing \
+					-O ${rsArgs[@]} $src[@] $dir)" || abort
 
-			if [[ -n "$data" ]]; then
-				nothing=0
-				techo -c warn "Deletions:"
-				n=0
-				echo $data | while read stat name; do
-					echo "$dir/$name ${C[red]}❌$C_"
-					files+=($dir/$name)
-					((n++))
-				done
-				confirm -c warn "Delete these $n files" || continue
-				#@TODO rm $(chooser "$files[@]")
-				run $sudo rsync --delete --existing --ignore-existing \
-					--info=PROGRESS2 $rsArgs $src $dir || abort
-				_sync
+				if [[ -n "$data" ]]; then
+					nothing=0
+					techo -c warn "Deletions:"
+					n=0
+					echo $data | while read stat name; do
+						echo "$dir/$name ${C[red]}❌$C_"
+						files+=($dir/$name)
+						((n++))
+					done
+					confirm -c warn "Delete these $n files" || continue
+					#@TODO rm $(chooser "$files[@]")
+					run $sudo rsync --delete --existing --ignore-existing \
+						--info=PROGRESS2 $rsArgs $src $dir || abort
+					_sync
+				fi
 			fi
 		fi
 	done
@@ -323,37 +342,81 @@ function syncDirs()
 	return 0
 }
 
-# Added 2019-01-22 18:07:09 @TODO
-function syncIhm()
-{
-	( cd $HOME/PeD/android && {
-		syncDirs -c -i $CFG/android.ignore $TREADMILL \
-			$CLOUD_APPS/Treadmill,/m/home/inbramed/android/Treadmill
-		syncDirs -c -i $CFG/android.ignore $CICLOERGOMETER \
-			$CLOUD_APPS/Cicloergometer,/m/home/inbramed/android/Cicloergometer
-	  }
-	)
-}
-
 # Added 2019-02-20 09:23:39 @TODO
 function box()
 {
-	local box base=$HOME/repos search=$1
-	#zparseopts -D -M - S:=search
+	local box base=$HOME/repos cmd search list
+	#zparseopts -D -M - 
 	include functions
+	include -l network
 	#include boxes
-	#box start
-	if [[ -n $search && -d $base/$search ]]; then
-		box=$search
+
+	if (($#)); then
+		cmd=$1 ; shift ; box="$*"
 	else
-		local list=($base/*(-/om))
-		box=$(chooser ${=1:+-S $search} $list:t) || cancel
-		[[ -d $base/$box ]] || abort 127 "Invalid box: $base/$box"
+		cmd='search'
+		box="$@"
 	fi
-	cd $base/$box
-	[[ -d .git ]] && git status &
-	[[ -d android ]] && include android
-	todo -d . #@TODO mv to cd hook
+
+	while ((1)); do
+		case $cmd in
+			new)
+				if [[ -z $box ]]; then
+					input -v box -p 'Enter git url or name to search' || cancel
+				fi
+				gclone $box #&& BOX=$box
+				return
+				#mkdir $base/$box
+			;;
+			open)
+				if [[ $box == '.' ]]; then
+					 box=$BOX
+				fi
+				cd $base/$box || return
+				BOX=$box
+				[[ -d .git ]] && git status &
+				[[ -d android ]] && include android
+				todo -d . #@TODO mv to cd hook
+				return 0
+			;;
+			start|run)
+				#@TODO
+				if [[ -z $box ]]; then
+					[[ -n $BOX ]] || abort 10
+					box=$BOX
+				else
+					#@TODO: glob search name, if count==1 box=result
+					result=($base/(#i)*${box}*)
+					(($#result)) || abort 10
+					chooser -v box $result:t || cancel
+				fi
+				if [[ -d $base/$box/node_modules ]]; then
+					(cd $base/$box/node_modules ; npm start &)
+				fi
+				return
+			;;
+			list|search)
+				search=$box
+				if [[ -n $search && -d $base/$search ]]; then
+					cmd='open'; box=$search
+					continue
+				fi
+
+				list=($base/*(-/om))
+				box=$(chooser -f1 ${=box:+-S $search} $list:t 'New box') || cancel
+				if [[ $box == 'New' ]]; then
+					cmd='new' ; box=''
+				elif [[ -d $base/$box ]]; then
+					cmd='open'
+				fi
+			;;
+			*)
+				box=$cmd
+				cmd='search'
+				#abort -v5 1 "Invalid command: $C[warn]$cmd$C_. Commands: open, list/search, new, start"
+			;;
+		esac
+	done
 }
 
 
@@ -475,7 +538,6 @@ typeset -gA awkFuncs
 awkFuncs=(
 	printArgs '(i,f) {\
 		if (i<0) i=NF+i+1; 	if (f<0) f=NF+f+1;\
-		print "NF="NF,"i="i,"f="f;
 		for (j=i ; j<f ; j++) {\
 			printf("%s%s", $j, OFS);\
 		}\
@@ -505,13 +567,14 @@ function awkWrapper()
 	prog=''
 	if (($#_inc)); then #@TODO
 		local fname=$_inc[2]
+		((${+awkFuncs[$fname]})) || abort 127 "Undefined function $C[warn]$fname"
 		prog+="function ${fname}${awkFuncs[$fname]}"$'\n'
 	fi
 
 	if (($#_expr)); then
-		if (($#_expr > 1)); then
+		if (($#_expr > 1)); then	# -e varname
 			_expr=(${(P)_expr[2]})
-		else
+		else						# -E
 			_expr=("$@[1,4]")
 		fi
 		local x m pat action
diff --git a/zsh_libs/zsh_main b/zsh_libs/zsh_main
--- a/zsh_libs/zsh_main
+++ b/zsh_libs/zsh_main
@@ -37,19 +37,20 @@ function techo()
 	if [[ -n $print ]]; then
 		print -P $noesc $_topts - $ts$msg >$TTY
 	else
-		echo -e ${noesc:+-E} $_topts - $ts$msg >$TTY
+		echo ${noesc:+-E} $_topts - $ts$msg >$TTY
 	fi
 }
 
 function cancel() {
-	local ret=$?
+	local _ret=$?
 	_dbg_trap $0
-	((ret != 130)) && throw $ret
 	abort 130 "$C[warn]Cancelled $@"
+	# $((ret != 130)) && throw $ret
+	abort 130 "$C[warn]Cancelled (ret=$_ret) $@"
 }
 
 () {
-	typeset -gA ExTree Ex
+	typeset -gA ExTree # Ex
 	ExTree=(Ex -
 	  IoEx Ex
 		FileIoEx IoEx
@@ -57,7 +58,10 @@ function cancel() {
 		  ConstraintSqlEx SqlEx
 	)
 	local e #p
-	for e in ${(k)ExTree}; do Ex[$e]="(#m)*$e(_*)#"; done
+	for e in ${(k)ExTree}; do
+		#Ex[$e]="(#m)*$e(_(#b)(*))#"
+		typeset -g "$e=(#m)*$e(_(#b)(*))#"
+	done
 	# integer i len
 	# for e p in ${(kv)spec}; do
 	#  	if [[ $p != '-' ]]; then
@@ -69,6 +73,21 @@ function cancel() {
 	# for e in ${(k)spec}; do exMask[$e]='(#m)'$exMask[$e]; done
 }
 
+function throw()
+{
+	typeset -g EXCEPTION=$1
+	typeset -ga ExArgs=("$@[2,-1]")
+	readonly THROW
+	if (( TRY_BLOCK_ERROR == 0 )); then
+	  # We are throwing an exception from the middle of an always-block.
+	  # We can do this by restoring the error status from the try-block.
+	  (( TRY_BLOCK_ERROR = 1 ))
+	fi
+
+	# Raise an error, but don't show an error message.
+	THROW= 2>/dev/null
+}
+
 function abort()
 {
 	integer last=$?
@@ -76,22 +95,32 @@ function abort()
 	integer cod
 	zparseopts -D - -ex:=_EX_TYPE e=noexception v:=verbose D:=dbglvl
 
-	(($#_EX_TYPE)) && _EX=$_EX_TYPE[2]
-	(($#)) && { cod=$1; shift } || { techo -c lred 'abort(): missing argument'; cod=$last }
+	if (($#_EX_TYPE)); then
+		_EX=$_EX_TYPE[2]
+		if ((!$+ExTree[${_EX%%_*}])); then
+			techo -c lred "Invalid Exception: ${_EX%%_*}"
+			fstack 1
+			throw $_EX $cod "$@"
+		fi
+	fi
 	verbose=${verbose[2]:-2}
-	((DEBUG>=DBG_LVL+dbglvl[2]+1)) && fstack 1
+	if (($#)); then
+		cod=$1; shift
+		((DEBUG>=DBG_LVL+dbglvl[2]+1)) && fstack 1
+	else
+		cod=$last
+		fstack 1
+	fi
 	[[ -n $ABORT ]] && $ABORT $_EX_TYPE $cod "$@"
-	((verbose+cod>=2)) && techo -c lred -r - ${_EX:-ERROR} $cod: "$@"
+	((verbose+cod>=4)) && techo -c lred -r - ${_EX:-ERROR} $cod: "${@}"
 
 	#@TODO $ZSH_EVAL_CONTEXT =~ toplevel* , does not seem to work
 	((EXIT)) && [[ ! -o interactive ]] && exit $cod
 
 	if (($#_EX)); then
-		autoload throw
-		throw "$_EX $cod $@"
+		throw $_EX $cod "$@"
 	elif [[ -z $noexception ]]; then
-		autoload throw
-		throw "$cod $@"
+		throw $cod "$@"
 	fi
 	return $cod
 }
@@ -247,54 +276,54 @@ function typeOf()
 	local name ret tpath all result
 	local integer i=2
 	zparseopts -D -M - a=all p=p
+
 	name=$1
-	if [[ ! -f $name ]]; then
-		ret=($(which -w $all $p $name))
 
-		for ((i=2 ; $+ret[i] ; i+=2)); do
-			type=$ret[i]
-
-			if [[ $type == 'none' ]]; then
-				echo 'none'
-				return 1
-			fi
-
-			if [[ $type == 'command' ]]; then
-				tpath=$(which -p $name)
-				isScript $tpath && type='script'
-			fi
-
-			result+=($type:$tpath)
-		done
-		echo ${(z)${(@u)result//:/ }}
+	if [[ $(getpath $name) != '.' || $name == ./* ]]; then # full path given
+		tpath=$(getfullpath $name)
+		if isScript $tpath; then
+			type='script'
+		elif [[ -x $tpath ]]; then
+			type='command'
+		else
+			echo 'none'
+			return 1
+		fi
+		
+		echo $type $tpath
 		return 0
 	fi
-	
-	tpath=$name
-	
-	if isScript $tpath; then
-		type='script'
-	elif [[ -x $tpath ]]; then
-		type='command'
-	else
-		echo 'none'
-		return 1
-	fi
-	
-	echo $type $tpath
-	return 0
+
+	ret=($(which -w $all $p $name))
+
+	for ((i=2 ; $+ret[i] ; i+=2)); do
+		type=$ret[i]
+
+		if [[ $type == 'none' ]]; then
+			echo 'none'
+			return 1
+		fi
+
+		if [[ $type == 'command' ]]; then
+			tpath=$(which -p $name)
+			isScript $tpath && type='script'
+		fi
+
+		result+=($type:$tpath)
+	done
+	echo ${(z)${(@u)result//:/ }}
 }
 
 function zindent()
 {
-	local f
+	integer f
 	[[ $# -gt 1 ]] && {
 		f=1
 		echo "function $1()\n{"
 		shift
 	}
 	echo "$@" | sed -E 's/^([^{}])/\t\1/g'
-	[[ -n $f ]] && echo "}"
+	((f)) && echo "}"
 }
 
 function parseErrors()
@@ -693,7 +722,7 @@ function libmonitor()
 		fi
 		((lastt = t))
 		killall -HUP zsh
-	done < <(inotifywait -m -q -e modify -r --format '%e %f %T' --timefmt '%s' $ZSH_LIBS || echo "exit $?")
+	done < <(inotifywait -m -q -e modify -r --format '%e %f %T' --timefmt '%s' "${(z)ZSH_LIBS:P}" || echo "exit $?")
 	return $name
 }
 
diff --git a/zsh_libs/zsh_sql b/zsh_libs/zsh_sql
--- a/zsh_libs/zsh_sql
+++ b/zsh_libs/zsh_sql
@@ -8,13 +8,18 @@ DB_DATA_DIR=/var/lib/mysql
 DBNAME='idiomus'
 
 typeset -gA sqlPass=(
+	# user  pass
 	'sparc' 'my!7866'
 	'idiomus' '#58dhAms$3xx'
 )
 typeset -gA sqlUser=(
+	# root user
 	'root' 'sparc'
+	# Dbname    User
 	'idiomus' 'idiomus'
 )
+
+typeset -gA rowIndex
 
 # get last modification time of dbname(s)
 # usage: dbtstamp dbname
@@ -25,20 +30,37 @@ function dbtstamp()
 		awk '{print $6,$7,$8}' | sort --numeric-sort
 }
 
+function todosql__()
+{
+	sql --ssh maquina 'SELECT review_version_id, sequence, length, texts, timestamps, status FROM review_track WHERE review_version_id=184 ORDER BY updated_at' | {          
+		read cols ; while IFS=$'\t\t' read -r version_id sequence length texts timestamps _status ; do 
+			sqlQuote -v _texts $texts; sqlQuote -v _timestamps $timestamps
+			sql "insert into review_track (review_version_id,sequence, length, texts, timestamps,status) values ($version_id, $sequence, $length, '$_texts', '$_timestamps', '$_status')"
+		done
+	}
+}
+
+function sqlQuote()
+{
+	zparseopts -D -M - v:=var
+
+	typeset -g "$var[2]=${1//(#m)[\']/\\$MATCH}"
+}
+
 # execute mysql command
 # sql [-d dbname] [-f file.sql] SELECT ...
 function sql()
 {
 	local file name nodb verbose user pass silent host ret _out opts
-	local _colsOut _cols p _idVar
+	local _colsOut _cols p _idVar _raw
 	integer i _id
 	typeset -g sql
-	zparseopts -D -M - f:=file d:=name n=nodb v=verbose u:=user p:=pass s=silent \
-		-ssh:=host o:=_out c:=_colsOut -columns:=c -id:=_idVar
+ #s=silent 
+	zparseopts -D -M - f:=file d:=name n=nodb v=verbose u:=user p:=pass \
+		-ssh:=host o:=_out c:=_colsOut -columns:=c -id:=_idVar r=_raw
 
 	sql="$*"
 
-	opts=($silent)
 	if (($#file)); then
 		[[ -f $file[2] ]] || abort --ex FileIoEx_NotFound 127 $(getfullpath $file[2])
 	fi
@@ -49,6 +71,7 @@ function sql()
 		OPT_CHK file -f for remote
 		#(($#file)) && file=$file[2]
 		if (($#_out)); then
+			#@TODO
 			ssh $host[2] "noglob sql $opts ${(qqq)sql}" 2>&p | \
 				awkWrapper -F '\\t' --inc printFields -E - - - - 'printFields(1,-1)'
 		else
@@ -56,6 +79,7 @@ function sql()
 		fi
 		ret=$?
 	else
+		opts=(-B $_raw)  # $silent
 		[[ -n $nodb ]] || usedb $name[2]
 		if [[ -n $db ]]; then
 			user=${user[2]:-${sqlUser[$db]:-$root}}
@@ -68,14 +92,15 @@ function sql()
 		if (($#_out)); then
 			i=1
 			_out=$_out[2]
-			#@TODO: no error handling: redirect stderr to null
+			unset $_out$i
+			rowIndex[$_out]=0
+			#@TODO: no error handling mode: redirect stderr to null
+			(($#verbose)) && techo -r -c head mysql $opts -e $sql $db
 			{
 				# column names
-				if IFS=$'\t\t' read -A _cols; then
-					# read rows into associative arrays: row1, row2, ..., rowN
-					#	with column names as keys
+				if IFS=$'\t\t' read -r -A _cols; then
 					typeset -ga $_out$i
-					while IFS=$'\t\t' read -A $_out$i; do
+					while IFS=$'\t\t' read -r -A $_out$i; do
 						((i++)); typeset -ga $_out$i
 					done
 					unset $_out$i
@@ -100,7 +125,7 @@ function sql()
 			#@TODO: no error handling: redirect stderr to null
 			if (($#file)); then
 				if [[ -f $file[2] ]]; then
-					(($#verbose)) && techo -c head mysql ${(qq)opts} ${(qq)sql} $db '<' $file[2]
+					(($#verbose)) && techo -r -c head mysql ${(qq)opts} ${(qq)sql} $db '<' $file[2]
 					mysql $opts $sql $db 2>&p < $file[2]
 				else
 					techo -c err "File not found$C_: $file[2]"
@@ -110,10 +135,10 @@ function sql()
 				if (($#_idVar)); then
 					# sql+="; SELECT ROW_COUNT(), LAST_INSERT_ID()"
 					sql+="; SELECT LAST_INSERT_ID()"
-					(($#verbose)) && techo -c head mysql ${(qq)opts} -s -e ${(qq)sql} $db
+					(($#verbose)) && techo -r -c head mysql $opts -s -e $sql $db
 					_id=$(mysql $opts -s -e $sql $db) 2>&p
 				else
-					(($#verbose)) && techo -c head mysql ${(qq)opts} -e ${(qq)sql} $db
+					(($#verbose)) && techo -r -c head mysql $opts -e $sql $db
 					mysql $opts -e $sql $db 2>&p
 				fi
 			fi
@@ -152,15 +177,26 @@ function sql()
 			else
 				ret=2
 			fi
-			(($#verbose)) && sqlError -v $errCode $sqlState $line $m
+			#(($#verbose)) && sqlError -v $errCode $sqlState $line $m
+			sqlError -v $errCode $sqlState $line $m
 			#@TODO this is going to run once per terminal. Wanted: once total.
 			#@idea run this part only on current terminal, if there is one focused.
 		else
 			techo $errCode $sqlState $line $tmp
-			DEBUG=9 abort 99 'Unknown error'
+			DEBUG=9 abort --ex SqlEx_Unknown 99 'Unknown error'
 		fi
-		abort --ex $Ex $ret "$errCode $sqlState $line $m" # - $msg"
+		abort ${verbose:+-v3} --ex $Ex $ret $errCode $sqlState $line $m # - $msg"
 	}
+}
+
+function sqlFetch()
+{
+	integer N
+	(($+rowIndex[$1])) || return 1
+	((N=++rowIndex[$1]))
+	local var=$1$N
+	((${(P)+var})) || return 1
+	set -A $1 "${(P@)var}"
 }
 
 # Pretty print error messages.
@@ -183,14 +219,16 @@ function sqlError()
 		;;
 		1064) msg+="Syntax error near $C[warn]'$@'"
 		;;
-		1452) msg+="Constraint violation $C[warn]$3$C_: $C[warn]$2.$4$C_ REFERENCES $C[warn]$5.$6"
+		145[12]) msg+="Constraint violation $C[warn]$3$C_: $C[warn]$2.$4$C_ REFERENCES $C[warn]$5.$6"
 		;;
-		*) local _args=($C[warn]$^@$C_)
-			printf $C[lred]$msg"$(perror -s $cod)$C_\n" $_args
+		*) local _args=("$@")
+			# printf -v _args $msg"$(perror -s $cod)" $C[warn]$^_args$C_
+			printf -v _args $msg"$(perror -s $cod)" $_args
+			techo -c lred $_args
 			return
 		;;
 	esac
-	echo $C[lred]$msg$C_
+	techo -c lred $msg
 }
 
 # Parses error string and returns error codes and relevant arguments.
@@ -201,7 +239,7 @@ function parseSqlErrors()
 {
 	_dbg_trap $0
 	local data
-	while read data; do
+	while read -r data; do
 		[[ $data == 'EOF' ]] && return
 		if [[ $data =~ $'^ERROR ([0-9]{4}) \\(([0-9A-Z]{5})\\) at line ([0-9]+): (.*)' ]]; then
 			local msg rx errCode sqlState msgFormat line
@@ -222,10 +260,10 @@ function parseSqlErrors()
 			1064)
 				msgFormat="near '(.*)'"
 				;;
-			1452)
-				msgFormat="^[^(]+\\(\`([^\`]+)\`.\`([^\`]+)\`, CONSTRAINT \`([^\`]+)\` FOREIGN KEY \\(\`([^\`]+)\`\\) REFERENCES \`([^\`]+)\` \\(\`([^\`]+)\`"
+			145[12])
+				msgFormat='^[^(]+\(`([^`]+)`.`([^`]+)`, CONSTRAINT `([^`]+)` FOREIGN KEY \(([^)]+)\) REFERENCES `([^`]+)` \(([^)]+)\)'
+				#msgFormat="^[^(]+\\(\`([^\`]+)\`.\`([^\`]+)\`, CONSTRAINT \`([^\`]+)\` FOREIGN KEY \\(\`([^\`]+)\`\\) REFERENCES \`([^\`]+)\` \\(\`([^\`]+)\`"
 			#	msgFormat="Cannot add or update a child row: a foreign key constraint fails (`¬tbl¬`.`#¬sql¬`, CONSTRAINT `#¬fk¬` FOREIGN KEY (`¬col¬`) REFERENCES `¬tbl¬` (`¬col¬`))"
-			#	;;
 	#ERROR 1452 (23000) at line 1: Cannot add or update a child row: a foreign key constraint fails (`idiomus`.`#sql-426_49`, CONSTRAINT `#sql-426_49_ibfk_1` FOREIGN KEY (`review_id`) REFERENCES `review` (`review_id`))
 				;;
 			*)
@@ -247,12 +285,12 @@ function parseSqlErrors()
 			esac
 
 			if [[ $msg =~ $msgFormat ]]; then
-				print -Pr $errCode $sqlState $line ${(@qqq)match} - $msg
+				print -Pr $errCode $sqlState $line ${(@qqq)match} - #@ $msg
 			else
 				techo -c lred "$C[warn]$errCode$C_ ($sqlState)\n" \
 					"Message format doesn't match line"
 				techo "format: $msgFormat"
-				print -Pr $errCode $sqlState $line - $msg
+				print -Pr $errCode $sqlState $line - #@ $msg
 			fi
 		else
 			techo -c lred $data
@@ -277,7 +315,7 @@ function usedb()
 			if [[ -o interactive ]]; then
 				(($#search)) || search=(-S $1)
 			else
-				abort --ex SQLEX_DBERROR 127 1049 42000 1 $1
+				abort --ex SqlEx_DbError 127 1049 42000 1 $1
 			fi
 		}
 	fi
